# sample action usage
name    = "endpoint_health_check"
timeout = "30s"

break_glass_role = ""

role = "{{ .nuon.install.id }}-custom-role-2"

[[triggers]]
type = "manual"

[[steps]]
name    = "role-check"
inline_contents = """
#!/usr/bin/env sh

set -e
set -o pipefail
set -u

aws sts get-caller-identity
"""

[steps.env_vars]
INGRESS_NAME      = "{{.nuon.install.id}}-public"
INGRESS_NAMESPACE = "whoami"

