package templates

import "strings"

func logTemplates() []Template {
	return []Template{
		{
			Key:         "terraform-apply",
			Description: "Terraform apply output creating AWS resources",
			Category:    "logs",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform"},
			Contents: strings.Join([]string{
				"Terraform v1.7.5",
				"Initializing plugins and modules...",
				"",
				"aws_s3_bucket.main: Creating...",
				"aws_s3_bucket.main: Creation complete after 2s [id=nuon-app-data-prod]",
				"aws_s3_bucket_versioning.main: Creating...",
				"aws_s3_bucket_versioning.main: Creation complete after 1s [id=nuon-app-data-prod]",
				"aws_s3_bucket_server_side_encryption_configuration.main: Creating...",
				"aws_s3_bucket_server_side_encryption_configuration.main: Creation complete after 1s [id=nuon-app-data-prod]",
				"aws_iam_role.app_role: Creating...",
				"aws_iam_role.app_role: Creation complete after 2s [id=nuon-app-role-prod]",
				"aws_iam_role_policy_attachment.s3_access: Creating...",
				"aws_iam_role_policy_attachment.s3_access: Creation complete after 1s [id=nuon-app-role-prod-20240315120000]",
				"aws_security_group.app: Creating...",
				"aws_security_group.app: Creation complete after 3s [id=sg-0abc123def456]",
				"aws_security_group_rule.ingress: Creating...",
				"aws_security_group_rule.ingress: Creation complete after 1s [id=sgrule-abc123]",
				"",
				"Apply complete! Resources: 6 added, 0 changed, 0 destroyed.",
				"",
				"Outputs:",
				"",
				`bucket_arn = "arn:aws:s3:::nuon-app-data-prod"`,
				`role_arn = "arn:aws:iam::123456789012:role/nuon-app-role-prod"`,
			}, "\n"),
		},
		{
			Key:         "terraform-plan",
			Description: "Terraform plan output showing resource changes",
			Category:    "logs",
			JobTypes:    []string{"sandbox-terraform-plan"},
			Contents: strings.Join([]string{
				"Terraform v1.7.5",
				"Refreshing Terraform state in-memory prior to plan...",
				"",
				"------------------------------------------------------------------------",
				"",
				"An execution plan has been generated and is shown below.",
				"Resource actions are indicated with the following symbols:",
				"  + create",
				"  ~ update in-place",
				"",
				"Terraform will perform the following actions:",
				"",
				`  # aws_s3_bucket.main will be created`,
				`  + resource "aws_s3_bucket" "main" {`,
				`      + arn            = (known after apply)`,
				`      + bucket         = "nuon-app-data-prod"`,
				`      + force_destroy  = false`,
				`      + id             = (known after apply)`,
				`      + tags           = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "terraform"`,
				`        }`,
				`    }`,
				"",
				`  # aws_iam_role.app_role will be created`,
				`  + resource "aws_iam_role" "app_role" {`,
				`      + arn                = (known after apply)`,
				`      + name               = "nuon-app-role-prod"`,
				`      + assume_role_policy = jsonencode({...})`,
				`    }`,
				"",
				"Plan: 2 to add, 0 to change, 0 to destroy.",
			}, "\n"),
		},
		{
			Key:         "helm",
			Description: "Helm install/upgrade output",
			Category:    "logs",
			JobTypes:    []string{"helm-chart-deploy"},
			Contents: strings.Join([]string{
				`Release "app-release" does not exist. Installing it now.`,
				"NAME: app-release",
				"LAST DEPLOYED: Mon Mar 15 12:00:00 2024",
				"NAMESPACE: default",
				"STATUS: deployed",
				"REVISION: 1",
				"TEST SUITE: None",
				"NOTES:",
				"  Application has been deployed successfully.",
				"  ",
				"  To access the application:",
				`    export POD_NAME=$(kubectl get pods -l app=app-release -o jsonpath="{.items[0].metadata.name}")`,
				"    kubectl port-forward $POD_NAME 8080:8080",
				"  ",
				"  Service endpoint: http://app-release.default.svc.cluster.local:8080",
				"",
				"coalesce.go:286: warning: destination for env is a table. Ignoring non-table value ([])",
				"",
				"HOOKS:",
				"---",
				"# Source: app/templates/tests/test-connection.yaml",
				"apiVersion: v1",
				"kind: Pod",
				"metadata:",
				`  name: "app-release-test-connection"`,
			}, "\n"),
		},
		{
			Key:         "kubernetes-manifest",
			Description: "kubectl apply output",
			Category:    "logs",
			JobTypes:    []string{"kubernetes-manifest-deploy"},
			Contents: strings.Join([]string{
				"namespace/app-prod created",
				"serviceaccount/app-sa created",
				"configmap/app-config created",
				"secret/app-secrets created",
				"deployment.apps/app-deployment created",
				"service/app-service created",
				"ingress.networking.k8s.io/app-ingress created",
				"horizontalpodautoscaler.autoscaling/app-hpa created",
				"",
				`Waiting for deployment "app-deployment" rollout to finish...`,
				"  1 of 3 updated replicas are available...",
				"  2 of 3 updated replicas are available...",
				"  3 of 3 updated replicas are available...",
				`deployment "app-deployment" successfully rolled out`,
			}, "\n"),
		},
		{
			Key:         "docker-build",
			Description: "Docker build output with layer caching",
			Category:    "logs",
			JobTypes:    []string{"docker-build", "container-image-build"},
			Contents: strings.Join([]string{
				"#1 [internal] load build definition from Dockerfile",
				"#1 transferring dockerfile: 847B done",
				"#1 DONE 0.0s",
				"",
				"#2 [internal] load .dockerignore",
				"#2 transferring context: 52B done",
				"#2 DONE 0.0s",
				"",
				"#3 [internal] load metadata for docker.io/library/golang:1.22-alpine",
				"#3 DONE 1.2s",
				"",
				"#4 [build 1/6] FROM docker.io/library/golang:1.22-alpine@sha256:abc123",
				"#4 CACHED",
				"",
				"#5 [build 2/6] WORKDIR /app",
				"#5 CACHED",
				"",
				"#6 [build 3/6] COPY go.mod go.sum ./",
				"#6 DONE 0.1s",
				"",
				"#7 [build 4/6] RUN go mod download",
				"#7 DONE 12.3s",
				"",
				"#8 [build 5/6] COPY . .",
				"#8 DONE 0.5s",
				"",
				"#9 [build 6/6] RUN CGO_ENABLED=0 go build -o /app/server .",
				"#9 DONE 28.7s",
				"",
				"#10 [runtime 1/2] COPY --from=build /app/server /usr/local/bin/",
				"#10 DONE 0.1s",
				"",
				"#11 exporting to image",
				"#11 exporting layers",
				"#11 writing image sha256:def456 done",
				"#11 naming to docker.io/library/app:latest done",
				"#11 DONE 0.2s",
			}, "\n"),
		},
		{
			Key:         "pulumi",
			Description: "Pulumi up output creating resources",
			Category:    "logs",
			JobTypes:    []string{"pulumi-deploy"},
			Contents: strings.Join([]string{
				"Updating (prod)",
				"",
				"View Live: https://app.pulumi.com/nuon/app/prod/updates/42",
				"",
				"     Type                          Name              Status",
				" +   pulumi:pulumi:Stack            app-prod          created",
				" +   ├─ aws:s3:Bucket               app-data          created",
				" +   ├─ aws:s3:BucketPolicy         app-data-policy   created",
				" +   ├─ aws:iam:Role                 app-role          created",
				" +   ├─ aws:iam:RolePolicy           app-policy        created",
				" +   └─ aws:cloudfront:Distribution  app-cdn           created",
				"",
				"Outputs:",
				`    bucketName  : "app-data-a1b2c3d"`,
				`    cdnDomain   : "d1234567.cloudfront.net"`,
				`    roleArn     : "arn:aws:iam::123456789012:role/app-role-prod"`,
				"",
				"Resources:",
				"    + 6 created",
				"",
				"Duration: 45s",
			}, "\n"),
		},
		{
			Key:         "oci-sync",
			Description: "OCI artifact sync output",
			Category:    "logs",
			JobTypes:    []string{"oci-sync"},
			Contents: strings.Join([]string{
				"Pulling artifact from registry...",
				"Resolved digest: sha256:abc123def456",
				"Downloading layer 1/3: config (256 bytes)",
				"Downloading layer 2/3: application/vnd.oci.image.layer.v1.tar+gzip (12.4 MB)",
				"Downloading layer 3/3: application/vnd.oci.image.layer.v1.tar+gzip (3.2 MB)",
				"Download complete.",
				"",
				"Verifying artifact integrity...",
				"Checksum verified: OK",
				"",
				"Pushing artifact to target registry...",
				"Uploading layer 1/3: config",
				"Uploading layer 2/3: application/vnd.oci.image.layer.v1.tar+gzip",
				"Uploading layer 3/3: application/vnd.oci.image.layer.v1.tar+gzip",
				"Pushed successfully to target.",
				"",
				"Artifact synced: sha256:abc123def456",
			}, "\n"),
		},
		{
			Key:         "bash",
			Description: "Bash script execution output for actions",
			Category:    "logs",
			JobTypes:    []string{"actions-workflow"},
			Contents: strings.Join([]string{
				`$ echo "Starting deployment workflow..."`,
				"Starting deployment workflow...",
				"",
				"$ npm run build",
				"> app@1.0.0 build",
				"> next build",
				"",
				"  ▲ Next.js 14.1.0",
				"  - Environments: .env.production",
				"",
				"   Creating an optimized production build ...",
				"   Compiled successfully",
				"   Linting and checking validity of types ...",
				"   Collecting page data ...",
				"   Generating static pages (0/12) ...",
				"   Generating static pages (3/12)",
				"   Generating static pages (6/12)",
				"   Generating static pages (9/12)",
				"   Generating static pages (12/12)",
				"   Finalizing page optimization ...",
				"",
				"Route (app)                    Size     First Load JS",
				"┌ ○ /                          5.42 kB        87.2 kB",
				"├ ○ /about                     3.18 kB        84.9 kB",
				"└ ○ /api/health                0 B            81.7 kB",
				"",
				"○  (Static)  prerendered as static content",
				"",
				`$ echo "Build completed successfully"`,
				"Build completed successfully",
				"",
				"$ aws s3 sync ./out s3://app-bucket/latest/",
				"upload: out/index.html to s3://app-bucket/latest/index.html",
				"upload: out/about.html to s3://app-bucket/latest/about.html",
				"upload: out/_next/static/chunks/main.js to s3://app-bucket/latest/_next/static/chunks/main.js",
				"",
				`$ echo "Deployment complete!"`,
				"Deployment complete!",
			}, "\n"),
		},
		// Resource-specific terraform log templates
		{
			Key:         "terraform-apply-rds",
			Description: "Terraform apply output creating RDS Postgres instance with supporting resources",
			Category:    "logs",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform"},
			Contents: strings.Join([]string{
				"Terraform v1.7.5",
				"Initializing plugins and modules...",
				"",
				"aws_db_subnet_group.main: Creating...",
				"aws_db_subnet_group.main: Creation complete after 1s [id=nuon-app-db-subnet-group]",
				"aws_db_parameter_group.main: Creating...",
				"aws_db_parameter_group.main: Creation complete after 1s [id=nuon-app-db-params]",
				"aws_security_group.rds: Creating...",
				"aws_security_group.rds: Creation complete after 3s [id=sg-0rds456def789abc]",
				"aws_security_group_rule.rds_ingress: Creating...",
				"aws_security_group_rule.rds_ingress: Creation complete after 1s [id=sgrule-rds123]",
				"aws_db_instance.main: Creating...",
				"aws_db_instance.main: Still creating... [30s elapsed]",
				"aws_db_instance.main: Still creating... [1m0s elapsed]",
				"aws_db_instance.main: Still creating... [1m30s elapsed]",
				"aws_db_instance.main: Still creating... [2m0s elapsed]",
				"aws_db_instance.main: Still creating... [2m30s elapsed]",
				"aws_db_instance.main: Still creating... [3m0s elapsed]",
				"aws_db_instance.main: Still creating... [3m30s elapsed]",
				"aws_db_instance.main: Still creating... [4m0s elapsed]",
				"aws_db_instance.main: Still creating... [4m30s elapsed]",
				"aws_db_instance.main: Creation complete after 5m12s [id=nuon-app-db-prod]",
				"",
				"Apply complete! Resources: 4 added, 0 changed, 0 destroyed.",
				"",
				"Outputs:",
				"",
				`db_endpoint     = "nuon-app-db-prod.abc123xyz.us-west-2.rds.amazonaws.com:5432"`,
				`db_name         = "appdb"`,
				`db_instance_id  = "nuon-app-db-prod"`,
				`security_group_id = "sg-0rds456def789abc"`,
			}, "\n"),
		},
		{
			Key:         "terraform-apply-ecs",
			Description: "Terraform apply output creating ECS Fargate cluster and service",
			Category:    "logs",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform"},
			Contents: strings.Join([]string{
				"Terraform v1.7.5",
				"Initializing plugins and modules...",
				"",
				"aws_ecs_cluster.main: Creating...",
				"aws_ecs_cluster.main: Creation complete after 8s [id=arn:aws:ecs:us-west-2:123456789012:cluster/nuon-app-prod]",
				"aws_lb_target_group.app: Creating...",
				"aws_lb_target_group.app: Creation complete after 2s [id=arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/nuon-app-tg/abc123def456]",
				"aws_ecs_task_definition.app: Creating...",
				"aws_ecs_task_definition.app: Creation complete after 3s [id=nuon-app]",
				"aws_ecs_service.app: Creating...",
				"aws_ecs_service.app: Still creating... [10s elapsed]",
				"aws_ecs_service.app: Still creating... [20s elapsed]",
				"aws_ecs_service.app: Creation complete after 25s [id=arn:aws:ecs:us-west-2:123456789012:service/nuon-app-prod/nuon-app-svc]",
				"",
				"Apply complete! Resources: 4 added, 0 changed, 0 destroyed.",
				"",
				"Outputs:",
				"",
				`cluster_arn         = "arn:aws:ecs:us-west-2:123456789012:cluster/nuon-app-prod"`,
				`service_name        = "nuon-app-svc"`,
				`task_definition_arn = "arn:aws:ecs:us-west-2:123456789012:task-definition/nuon-app:1"`,
				`target_group_arn    = "arn:aws:elasticloadbalancing:us-west-2:123456789012:targetgroup/nuon-app-tg/abc123def456"`,
			}, "\n"),
		},
		{
			Key:         "terraform-apply-lambda",
			Description: "Terraform apply output creating Lambda function with IAM role",
			Category:    "logs",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform"},
			Contents: strings.Join([]string{
				"Terraform v1.7.5",
				"Initializing plugins and modules...",
				"",
				"aws_iam_role.lambda_exec: Creating...",
				"aws_iam_role.lambda_exec: Creation complete after 2s [id=nuon-app-lambda-exec]",
				"aws_iam_role_policy_attachment.lambda_basic: Creating...",
				"aws_iam_role_policy_attachment.lambda_basic: Creation complete after 1s [id=nuon-app-lambda-exec-20240315120000]",
				"aws_cloudwatch_log_group.lambda: Creating...",
				"aws_cloudwatch_log_group.lambda: Creation complete after 1s [id=/aws/lambda/nuon-app-handler]",
				"aws_lambda_function.main: Creating...",
				"aws_lambda_function.main: Still creating... [5s elapsed]",
				"aws_lambda_function.main: Creation complete after 8s [id=nuon-app-handler]",
				"",
				"Apply complete! Resources: 3 added, 0 changed, 0 destroyed.",
				"",
				"Outputs:",
				"",
				`function_name = "nuon-app-handler"`,
				`function_arn  = "arn:aws:lambda:us-west-2:123456789012:function:nuon-app-handler"`,
				`invoke_url    = "https://abc123xyz.execute-api.us-west-2.amazonaws.com/prod"`,
				`log_group     = "/aws/lambda/nuon-app-handler"`,
			}, "\n"),
		},
		{
			Key:         "terraform-apply-vpc",
			Description: "Terraform apply output creating VPC with subnets and NAT gateway",
			Category:    "logs",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform"},
			Contents: strings.Join([]string{
				"Terraform v1.7.5",
				"Initializing plugins and modules...",
				"",
				"aws_vpc.main: Creating...",
				"aws_vpc.main: Creation complete after 3s [id=vpc-0abc123def456]",
				"aws_subnet.public[0]: Creating...",
				"aws_subnet.public[1]: Creating...",
				"aws_subnet.public[2]: Creating...",
				"aws_subnet.private[0]: Creating...",
				"aws_subnet.private[1]: Creating...",
				"aws_subnet.private[2]: Creating...",
				"aws_subnet.public[0]: Creation complete after 2s [id=subnet-0pub1aaa]",
				"aws_subnet.public[1]: Creation complete after 2s [id=subnet-0pub2bbb]",
				"aws_subnet.public[2]: Creation complete after 2s [id=subnet-0pub3ccc]",
				"aws_subnet.private[0]: Creation complete after 2s [id=subnet-0prv1ddd]",
				"aws_subnet.private[1]: Creation complete after 2s [id=subnet-0prv2eee]",
				"aws_subnet.private[2]: Creation complete after 3s [id=subnet-0prv3fff]",
				"aws_internet_gateway.main: Creating...",
				"aws_internet_gateway.main: Creation complete after 2s [id=igw-0abc123def456]",
				"aws_eip.nat: Creating...",
				"aws_eip.nat: Creation complete after 1s [id=eipalloc-0abc123]",
				"aws_nat_gateway.main: Creating...",
				"aws_nat_gateway.main: Still creating... [30s elapsed]",
				"aws_nat_gateway.main: Still creating... [1m0s elapsed]",
				"aws_nat_gateway.main: Creation complete after 1m32s [id=nat-0abc123def456]",
				"aws_route_table.public: Creating...",
				"aws_route_table.public: Creation complete after 2s [id=rtb-0pub123]",
				"aws_route_table.private: Creating...",
				"aws_route_table.private: Creation complete after 2s [id=rtb-0prv456]",
				"",
				"Apply complete! Resources: 6 added, 0 changed, 0 destroyed.",
				"",
				"Outputs:",
				"",
				`vpc_id             = "vpc-0abc123def456"`,
				`vpc_cidr           = "10.0.0.0/16"`,
				`public_subnet_ids  = ["subnet-0pub1aaa", "subnet-0pub2bbb", "subnet-0pub3ccc"]`,
				`private_subnet_ids = ["subnet-0prv1ddd", "subnet-0prv2eee", "subnet-0prv3fff"]`,
				`nat_gateway_ip     = "54.123.45.67"`,
			}, "\n"),
		},
		{
			Key:         "terraform-apply-s3-detailed",
			Description: "Terraform apply output creating S3 bucket with versioning, encryption, and lifecycle",
			Category:    "logs",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform"},
			Contents: strings.Join([]string{
				"Terraform v1.7.5",
				"Initializing plugins and modules...",
				"",
				"aws_s3_bucket.main: Creating...",
				"aws_s3_bucket.main: Creation complete after 2s [id=nuon-app-data-prod]",
				"aws_s3_bucket_versioning.main: Creating...",
				"aws_s3_bucket_versioning.main: Creation complete after 1s [id=nuon-app-data-prod]",
				"aws_s3_bucket_server_side_encryption_configuration.main: Creating...",
				"aws_s3_bucket_server_side_encryption_configuration.main: Creation complete after 1s [id=nuon-app-data-prod]",
				"aws_s3_bucket_public_access_block.main: Creating...",
				"aws_s3_bucket_public_access_block.main: Creation complete after 1s [id=nuon-app-data-prod]",
				"aws_s3_bucket_lifecycle_configuration.main: Creating...",
				"aws_s3_bucket_lifecycle_configuration.main: Creation complete after 1s [id=nuon-app-data-prod]",
				"",
				"Apply complete! Resources: 5 added, 0 changed, 0 destroyed.",
				"",
				"Outputs:",
				"",
				`bucket_arn            = "arn:aws:s3:::nuon-app-data-prod"`,
				`bucket_name           = "nuon-app-data-prod"`,
				`bucket_domain_name    = "nuon-app-data-prod.s3.amazonaws.com"`,
				`versioning_enabled    = true`,
				`encryption_algorithm  = "aws:kms"`,
			}, "\n"),
		},
		// Noop log variants
		{
			Key:         "terraform-noop-logs",
			Description: "Terraform apply output with no changes",
			Category:    "logs",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform"},
			IsNoop:      true,
			Contents: strings.Join([]string{
				"Terraform v1.7.5",
				"Initializing plugins and modules...",
				"",
				"No changes. Your infrastructure matches the configuration.",
				"",
				"Terraform has compared your real infrastructure against your configuration",
				"and found no differences, so no changes are needed.",
				"",
				"Apply complete! Resources: 0 added, 0 changed, 0 destroyed.",
			}, "\n"),
		},
		{
			Key:         "helm-noop-logs",
			Description: "Helm upgrade output with no changes",
			Category:    "logs",
			JobTypes:    []string{"helm-chart-deploy"},
			IsNoop:      true,
			Contents: strings.Join([]string{
				`Release "app-release" has been upgraded. Happy Helming!`,
				"NAME: app-release",
				"LAST DEPLOYED: Mon Mar 15 12:00:00 2024",
				"NAMESPACE: default",
				"STATUS: deployed",
				"REVISION: 3",
				"TEST SUITE: None",
				"",
				"Release has no changes.",
			}, "\n"),
		},
		{
			Key:         "kube-noop-logs",
			Description: "kubectl apply output with no changes",
			Category:    "logs",
			JobTypes:    []string{"kubernetes-manifest-deploy"},
			IsNoop:      true,
			Contents: strings.Join([]string{
				"deployment.apps/app-deployment unchanged",
				"service/app-service unchanged",
				"configmap/app-config unchanged",
				"horizontalpodautoscaler.autoscaling/app-hpa unchanged",
				"",
				"All resources unchanged.",
			}, "\n"),
		},
		{
			Key:         "pulumi-noop-logs",
			Description: "Pulumi up output with no changes",
			Category:    "logs",
			JobTypes:    []string{"pulumi-deploy"},
			IsNoop:      true,
			Contents: strings.Join([]string{
				"Updating (prod)",
				"",
				"View Live: https://app.pulumi.com/nuon/app/prod/updates/43",
				"",
				"     Type                 Name          Status",
				"     pulumi:pulumi:Stack   app-prod",
				"",
				"Resources:",
				"    5 unchanged",
				"",
				"Duration: 3s",
				"",
				"No changes. 5 resources unchanged.",
			}, "\n"),
		},
	}
}
