package templates

import "strings"

// planDisplayTemplates returns all human-readable plan display templates.
// These match the format of `terraform show planfile` text output.
func planDisplayTemplates() []Template {
	return []Template{
		{
			Key:         "terraform-display-noop",
			Description: "Terraform plan display with no changes",
			Category:    "plan_displays",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform", "sandbox-terraform-plan"},
			IsNoop:      true,
			Contents: strings.Join([]string{
				"No changes. Your infrastructure matches the configuration.",
				"",
				"Terraform has compared your real infrastructure against your configuration",
				"and found no differences, so no changes are needed.",
			}, "\n"),
		},
		{
			Key:         "terraform-display-apply",
			Description: "Terraform plan display creating S3 bucket and IAM role",
			Category:    "plan_displays",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform", "sandbox-terraform-plan"},
			Contents: strings.Join([]string{
				"Terraform will perform the following actions:",
				"",
				`  # aws_s3_bucket.main will be created`,
				`  + resource "aws_s3_bucket" "main" {`,
				`      + arn                         = (known after apply)`,
				`      + bucket                      = "nuon-app-data-prod"`,
				`      + bucket_domain_name          = (known after apply)`,
				`      + bucket_regional_domain_name = (known after apply)`,
				`      + force_destroy               = false`,
				`      + id                          = (known after apply)`,
				`      + region                      = (known after apply)`,
				`      + tags                        = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`      + tags_all                    = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`    }`,
				"",
				`  # aws_iam_role.app_role will be created`,
				`  + resource "aws_iam_role" "app_role" {`,
				`      + arn                   = (known after apply)`,
				`      + create_date           = (known after apply)`,
				`      + force_detach_policies = false`,
				`      + id                    = (known after apply)`,
				`      + name                  = "nuon-app-role-prod"`,
				`      + unique_id             = (known after apply)`,
				`      + tags                  = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`    }`,
				"",
				"Plan: 2 to add, 0 to change, 0 to destroy.",
			}, "\n"),
		},
		{
			Key:         "terraform-display-destroy",
			Description: "Terraform plan display destroying S3 bucket and IAM role",
			Category:    "plan_displays",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform", "sandbox-terraform-plan"},
			Contents: strings.Join([]string{
				"Terraform will perform the following actions:",
				"",
				`  # aws_s3_bucket.data will be destroyed`,
				`  - resource "aws_s3_bucket" "data" {`,
				`      - arn                         = "arn:aws:s3:::nuon-app-data-prod" -> null`,
				`      - bucket                      = "nuon-app-data-prod" -> null`,
				`      - bucket_domain_name          = "nuon-app-data-prod.s3.amazonaws.com" -> null`,
				`      - id                          = "nuon-app-data-prod" -> null`,
				`      - region                      = "us-west-2" -> null`,
				`      - tags                        = {`,
				`          - "Environment" = "production"`,
				`          - "ManagedBy"   = "nuon"`,
				`        } -> null`,
				`    }`,
				"",
				`  # aws_iam_role.app_role will be destroyed`,
				`  - resource "aws_iam_role" "app_role" {`,
				`      - arn                   = "arn:aws:iam::123456789012:role/nuon-app-role" -> null`,
				`      - name                  = "nuon-app-role" -> null`,
				`      - id                    = "nuon-app-role" -> null`,
				`    }`,
				"",
				"Plan: 0 to add, 0 to change, 2 to destroy.",
			}, "\n"),
		},
		{
			Key:         "terraform-display-apply-rds",
			Description: "Terraform plan display creating RDS Postgres instance with supporting resources",
			Category:    "plan_displays",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform", "sandbox-terraform-plan"},
			Contents: strings.Join([]string{
				"Terraform will perform the following actions:",
				"",
				`  # aws_db_subnet_group.main will be created`,
				`  + resource "aws_db_subnet_group" "main" {`,
				`      + arn                     = (known after apply)`,
				`      + id                      = (known after apply)`,
				`      + name                    = "nuon-app-db-subnet-group"`,
				`      + subnet_ids              = [`,
				`          + "subnet-0abc123",`,
				`          + "subnet-0def456",`,
				`          + "subnet-0ghi789",`,
				`        ]`,
				`      + tags                    = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`    }`,
				"",
				`  # aws_db_parameter_group.main will be created`,
				`  + resource "aws_db_parameter_group" "main" {`,
				`      + arn    = (known after apply)`,
				`      + id     = (known after apply)`,
				`      + name   = "nuon-app-db-params"`,
				`      + family = "postgres15"`,
				`    }`,
				"",
				`  # aws_security_group.rds will be created`,
				`  + resource "aws_security_group" "rds" {`,
				`      + arn         = (known after apply)`,
				`      + id          = (known after apply)`,
				`      + name        = "nuon-app-rds-sg"`,
				`      + vpc_id      = "vpc-0abc123def456"`,
				`    }`,
				"",
				`  # aws_db_instance.main will be created`,
				`  + resource "aws_db_instance" "main" {`,
				`      + address                        = (known after apply)`,
				`      + allocated_storage               = 20`,
				`      + arn                             = (known after apply)`,
				`      + backup_retention_period         = 7`,
				`      + db_name                         = "appdb"`,
				`      + deletion_protection             = true`,
				`      + endpoint                        = (known after apply)`,
				`      + engine                          = "postgres"`,
				`      + engine_version                  = "15.4"`,
				`      + id                              = (known after apply)`,
				`      + identifier                      = "nuon-app-db-prod"`,
				`      + instance_class                  = "db.t3.medium"`,
				`      + max_allocated_storage           = 100`,
				`      + multi_az                        = false`,
				`      + port                            = 5432`,
				`      + publicly_accessible             = false`,
				`      + skip_final_snapshot             = false`,
				`      + storage_encrypted               = true`,
				`      + storage_type                    = "gp3"`,
				`      + username                        = "appuser"`,
				`      + tags                            = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`    }`,
				"",
				"Plan: 4 to add, 0 to change, 0 to destroy.",
			}, "\n"),
		},
		{
			Key:         "terraform-display-apply-ecs",
			Description: "Terraform plan display creating ECS Fargate cluster and service",
			Category:    "plan_displays",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform", "sandbox-terraform-plan"},
			Contents: strings.Join([]string{
				"Terraform will perform the following actions:",
				"",
				`  # aws_ecs_cluster.main will be created`,
				`  + resource "aws_ecs_cluster" "main" {`,
				`      + arn  = (known after apply)`,
				`      + id   = (known after apply)`,
				`      + name = "nuon-app-prod"`,
				`      + setting {`,
				`          + name  = "containerInsights"`,
				`          + value = "enabled"`,
				`        }`,
				`      + tags = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`    }`,
				"",
				`  # aws_ecs_task_definition.app will be created`,
				`  + resource "aws_ecs_task_definition" "app" {`,
				`      + arn                      = (known after apply)`,
				`      + cpu                      = "256"`,
				`      + execution_role_arn        = "arn:aws:iam::123456789012:role/ecsTaskExecutionRole"`,
				`      + family                   = "nuon-app"`,
				`      + id                       = (known after apply)`,
				`      + memory                   = "512"`,
				`      + network_mode             = "awsvpc"`,
				`      + requires_compatibilities = ["FARGATE"]`,
				`      + revision                 = (known after apply)`,
				`    }`,
				"",
				`  # aws_ecs_service.app will be created`,
				`  + resource "aws_ecs_service" "app" {`,
				`      + cluster         = (known after apply)`,
				`      + desired_count   = 2`,
				`      + id              = (known after apply)`,
				`      + launch_type     = "FARGATE"`,
				`      + name            = "nuon-app-svc"`,
				`      + platform_version = "LATEST"`,
				`    }`,
				"",
				`  # aws_lb_target_group.app will be created`,
				`  + resource "aws_lb_target_group" "app" {`,
				`      + arn         = (known after apply)`,
				`      + id          = (known after apply)`,
				`      + name        = "nuon-app-tg"`,
				`      + port        = 8080`,
				`      + protocol    = "HTTP"`,
				`      + target_type = "ip"`,
				`      + vpc_id      = "vpc-0abc123def456"`,
				`    }`,
				"",
				"Plan: 4 to add, 0 to change, 0 to destroy.",
			}, "\n"),
		},
		{
			Key:         "terraform-display-apply-lambda",
			Description: "Terraform plan display creating Lambda function with IAM role",
			Category:    "plan_displays",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform", "sandbox-terraform-plan"},
			Contents: strings.Join([]string{
				"Terraform will perform the following actions:",
				"",
				`  # aws_iam_role.lambda_exec will be created`,
				`  + resource "aws_iam_role" "lambda_exec" {`,
				`      + arn                   = (known after apply)`,
				`      + create_date           = (known after apply)`,
				`      + id                    = (known after apply)`,
				`      + name                  = "nuon-app-lambda-exec"`,
				`      + unique_id             = (known after apply)`,
				`    }`,
				"",
				`  # aws_cloudwatch_log_group.lambda will be created`,
				`  + resource "aws_cloudwatch_log_group" "lambda" {`,
				`      + arn               = (known after apply)`,
				`      + id                = (known after apply)`,
				`      + name              = "/aws/lambda/nuon-app-handler"`,
				`      + retention_in_days = 14`,
				`    }`,
				"",
				`  # aws_lambda_function.main will be created`,
				`  + resource "aws_lambda_function" "main" {`,
				`      + architectures    = ["arm64"]`,
				`      + arn              = (known after apply)`,
				`      + function_name    = "nuon-app-handler"`,
				`      + handler          = "bootstrap"`,
				`      + id               = (known after apply)`,
				`      + invoke_arn       = (known after apply)`,
				`      + memory_size      = 128`,
				`      + runtime          = "provided.al2023"`,
				`      + source_code_hash = (known after apply)`,
				`      + timeout          = 30`,
				`      + tags             = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`    }`,
				"",
				"Plan: 3 to add, 0 to change, 0 to destroy.",
			}, "\n"),
		},
		{
			Key:         "terraform-display-apply-vpc",
			Description: "Terraform plan display creating VPC with subnets and NAT gateway",
			Category:    "plan_displays",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform", "sandbox-terraform-plan"},
			Contents: strings.Join([]string{
				"Terraform will perform the following actions:",
				"",
				`  # aws_vpc.main will be created`,
				`  + resource "aws_vpc" "main" {`,
				`      + arn                  = (known after apply)`,
				`      + cidr_block           = "10.0.0.0/16"`,
				`      + enable_dns_hostnames = true`,
				`      + enable_dns_support   = true`,
				`      + id                   = (known after apply)`,
				`      + tags                 = {`,
				`          + "Name"        = "nuon-app-vpc"`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`    }`,
				"",
				`  # aws_subnet.public[0] will be created`,
				`  + resource "aws_subnet" "public" {`,
				`      + arn                 = (known after apply)`,
				`      + availability_zone   = "us-west-2a"`,
				`      + cidr_block          = "10.0.1.0/24"`,
				`      + id                  = (known after apply)`,
				`      + map_public_ip_on_launch = true`,
				`      + vpc_id              = (known after apply)`,
				`    }`,
				"",
				`  # aws_subnet.private[0] will be created`,
				`  + resource "aws_subnet" "private" {`,
				`      + arn               = (known after apply)`,
				`      + availability_zone = "us-west-2a"`,
				`      + cidr_block        = "10.0.10.0/24"`,
				`      + id                = (known after apply)`,
				`      + vpc_id            = (known after apply)`,
				`    }`,
				"",
				`  # aws_internet_gateway.main will be created`,
				`  + resource "aws_internet_gateway" "main" {`,
				`      + arn    = (known after apply)`,
				`      + id     = (known after apply)`,
				`      + vpc_id = (known after apply)`,
				`      + tags   = {`,
				`          + "Name" = "nuon-app-igw"`,
				`        }`,
				`    }`,
				"",
				`  # aws_eip.nat will be created`,
				`  + resource "aws_eip" "nat" {`,
				`      + allocation_id = (known after apply)`,
				`      + domain        = "vpc"`,
				`      + id            = (known after apply)`,
				`      + public_ip     = (known after apply)`,
				`    }`,
				"",
				`  # aws_nat_gateway.main will be created`,
				`  + resource "aws_nat_gateway" "main" {`,
				`      + allocation_id     = (known after apply)`,
				`      + connectivity_type = "public"`,
				`      + id                = (known after apply)`,
				`      + public_ip         = (known after apply)`,
				`      + subnet_id         = (known after apply)`,
				`      + tags              = {`,
				`          + "Name" = "nuon-app-nat"`,
				`        }`,
				`    }`,
				"",
				"Plan: 6 to add, 0 to change, 0 to destroy.",
			}, "\n"),
		},
		{
			Key:         "terraform-display-apply-s3-detailed",
			Description: "Terraform plan display creating S3 bucket with versioning, encryption, and lifecycle",
			Category:    "plan_displays",
			JobTypes:    []string{"terraform-deploy", "sandbox-terraform", "sandbox-terraform-plan"},
			Contents: strings.Join([]string{
				"Terraform will perform the following actions:",
				"",
				`  # aws_s3_bucket.main will be created`,
				`  + resource "aws_s3_bucket" "main" {`,
				`      + arn            = (known after apply)`,
				`      + bucket         = "nuon-app-data-prod"`,
				`      + id             = (known after apply)`,
				`      + region         = (known after apply)`,
				`      + tags           = {`,
				`          + "Environment" = "production"`,
				`          + "ManagedBy"   = "nuon"`,
				`        }`,
				`    }`,
				"",
				`  # aws_s3_bucket_versioning.main will be created`,
				`  + resource "aws_s3_bucket_versioning" "main" {`,
				`      + bucket = (known after apply)`,
				`      + id     = (known after apply)`,
				`      + versioning_configuration {`,
				`          + mfa_delete = "Disabled"`,
				`          + status     = "Enabled"`,
				`        }`,
				`    }`,
				"",
				`  # aws_s3_bucket_server_side_encryption_configuration.main will be created`,
				`  + resource "aws_s3_bucket_server_side_encryption_configuration" "main" {`,
				`      + bucket = (known after apply)`,
				`      + id     = (known after apply)`,
				`      + rule {`,
				`          + apply_server_side_encryption_by_default {`,
				`              + sse_algorithm = "aws:kms"`,
				`            }`,
				`        }`,
				`    }`,
				"",
				`  # aws_s3_bucket_public_access_block.main will be created`,
				`  + resource "aws_s3_bucket_public_access_block" "main" {`,
				`      + block_public_acls       = true`,
				`      + block_public_policy     = true`,
				`      + bucket                  = (known after apply)`,
				`      + id                      = (known after apply)`,
				`      + ignore_public_acls      = true`,
				`      + restrict_public_buckets = true`,
				`    }`,
				"",
				`  # aws_s3_bucket_lifecycle_configuration.main will be created`,
				`  + resource "aws_s3_bucket_lifecycle_configuration" "main" {`,
				`      + bucket = (known after apply)`,
				`      + id     = (known after apply)`,
				`      + rule {`,
				`          + id     = "archive-old-versions"`,
				`          + status = "Enabled"`,
				`          + noncurrent_version_transition {`,
				`              + noncurrent_days = 30`,
				`              + storage_class   = "GLACIER"`,
				`            }`,
				`        }`,
				`    }`,
				"",
				"Plan: 5 to add, 0 to change, 0 to destroy.",
			}, "\n"),
		},
	}
}
