// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// NewAddAppComponentLabelsParams creates a new AddAppComponentLabelsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddAppComponentLabelsParams() *AddAppComponentLabelsParams {
	return &AddAppComponentLabelsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddAppComponentLabelsParamsWithTimeout creates a new AddAppComponentLabelsParams object
// with the ability to set a timeout on a request.
func NewAddAppComponentLabelsParamsWithTimeout(timeout time.Duration) *AddAppComponentLabelsParams {
	return &AddAppComponentLabelsParams{
		timeout: timeout,
	}
}

// NewAddAppComponentLabelsParamsWithContext creates a new AddAppComponentLabelsParams object
// with the ability to set a context for a request.
func NewAddAppComponentLabelsParamsWithContext(ctx context.Context) *AddAppComponentLabelsParams {
	return &AddAppComponentLabelsParams{
		Context: ctx,
	}
}

// NewAddAppComponentLabelsParamsWithHTTPClient creates a new AddAppComponentLabelsParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddAppComponentLabelsParamsWithHTTPClient(client *http.Client) *AddAppComponentLabelsParams {
	return &AddAppComponentLabelsParams{
		HTTPClient: client,
	}
}

/*
AddAppComponentLabelsParams contains all the parameters to send to the API endpoint

	for the add app component labels operation.

	Typically these are written to a http.Request.
*/
type AddAppComponentLabelsParams struct {

	/* AppID.

	   app ID
	*/
	AppID string

	/* ComponentID.

	   component ID
	*/
	ComponentID string

	/* Req.

	   Input
	*/
	Req *models.ServiceAddComponentLabelsRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add app component labels params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddAppComponentLabelsParams) WithDefaults() *AddAppComponentLabelsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add app component labels params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddAppComponentLabelsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add app component labels params
func (o *AddAppComponentLabelsParams) WithTimeout(timeout time.Duration) *AddAppComponentLabelsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add app component labels params
func (o *AddAppComponentLabelsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add app component labels params
func (o *AddAppComponentLabelsParams) WithContext(ctx context.Context) *AddAppComponentLabelsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add app component labels params
func (o *AddAppComponentLabelsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add app component labels params
func (o *AddAppComponentLabelsParams) WithHTTPClient(client *http.Client) *AddAppComponentLabelsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add app component labels params
func (o *AddAppComponentLabelsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the add app component labels params
func (o *AddAppComponentLabelsParams) WithAppID(appID string) *AddAppComponentLabelsParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the add app component labels params
func (o *AddAppComponentLabelsParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithComponentID adds the componentID to the add app component labels params
func (o *AddAppComponentLabelsParams) WithComponentID(componentID string) *AddAppComponentLabelsParams {
	o.SetComponentID(componentID)
	return o
}

// SetComponentID adds the componentId to the add app component labels params
func (o *AddAppComponentLabelsParams) SetComponentID(componentID string) {
	o.ComponentID = componentID
}

// WithReq adds the req to the add app component labels params
func (o *AddAppComponentLabelsParams) WithReq(req *models.ServiceAddComponentLabelsRequest) *AddAppComponentLabelsParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the add app component labels params
func (o *AddAppComponentLabelsParams) SetReq(req *models.ServiceAddComponentLabelsRequest) {
	o.Req = req
}

// WriteToRequest writes these params to a swagger request
func (o *AddAppComponentLabelsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_id
	if err := r.SetPathParam("app_id", o.AppID); err != nil {
		return err
	}

	// path param component_id
	if err := r.SetPathParam("component_id", o.ComponentID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
