// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// CheckVCSConnectionStatusReader is a Reader for the CheckVCSConnectionStatus structure.
type CheckVCSConnectionStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CheckVCSConnectionStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewCheckVCSConnectionStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCheckVCSConnectionStatusBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCheckVCSConnectionStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCheckVCSConnectionStatusForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCheckVCSConnectionStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCheckVCSConnectionStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/vcs/connections/{connection_id}/check-status] CheckVCSConnectionStatus", response, response.Code())
	}
}

// NewCheckVCSConnectionStatusOK creates a CheckVCSConnectionStatusOK with default headers values
func NewCheckVCSConnectionStatusOK() *CheckVCSConnectionStatusOK {
	return &CheckVCSConnectionStatusOK{}
}

/*
CheckVCSConnectionStatusOK describes a response with status code 200, with default header values.

OK
*/
type CheckVCSConnectionStatusOK struct {
	Payload *models.ServiceVCSConnectionStatusResponse
}

// IsSuccess returns true when this check v c s connection status o k response has a 2xx status code
func (o *CheckVCSConnectionStatusOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this check v c s connection status o k response has a 3xx status code
func (o *CheckVCSConnectionStatusOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check v c s connection status o k response has a 4xx status code
func (o *CheckVCSConnectionStatusOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this check v c s connection status o k response has a 5xx status code
func (o *CheckVCSConnectionStatusOK) IsServerError() bool {
	return false
}

// IsCode returns true when this check v c s connection status o k response a status code equal to that given
func (o *CheckVCSConnectionStatusOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the check v c s connection status o k response
func (o *CheckVCSConnectionStatusOK) Code() int {
	return 200
}

func (o *CheckVCSConnectionStatusOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusOK %s", 200, payload)
}

func (o *CheckVCSConnectionStatusOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusOK %s", 200, payload)
}

func (o *CheckVCSConnectionStatusOK) GetPayload() *models.ServiceVCSConnectionStatusResponse {
	return o.Payload
}

func (o *CheckVCSConnectionStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceVCSConnectionStatusResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCheckVCSConnectionStatusBadRequest creates a CheckVCSConnectionStatusBadRequest with default headers values
func NewCheckVCSConnectionStatusBadRequest() *CheckVCSConnectionStatusBadRequest {
	return &CheckVCSConnectionStatusBadRequest{}
}

/*
CheckVCSConnectionStatusBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CheckVCSConnectionStatusBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this check v c s connection status bad request response has a 2xx status code
func (o *CheckVCSConnectionStatusBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check v c s connection status bad request response has a 3xx status code
func (o *CheckVCSConnectionStatusBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check v c s connection status bad request response has a 4xx status code
func (o *CheckVCSConnectionStatusBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this check v c s connection status bad request response has a 5xx status code
func (o *CheckVCSConnectionStatusBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this check v c s connection status bad request response a status code equal to that given
func (o *CheckVCSConnectionStatusBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the check v c s connection status bad request response
func (o *CheckVCSConnectionStatusBadRequest) Code() int {
	return 400
}

func (o *CheckVCSConnectionStatusBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusBadRequest %s", 400, payload)
}

func (o *CheckVCSConnectionStatusBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusBadRequest %s", 400, payload)
}

func (o *CheckVCSConnectionStatusBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CheckVCSConnectionStatusBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCheckVCSConnectionStatusUnauthorized creates a CheckVCSConnectionStatusUnauthorized with default headers values
func NewCheckVCSConnectionStatusUnauthorized() *CheckVCSConnectionStatusUnauthorized {
	return &CheckVCSConnectionStatusUnauthorized{}
}

/*
CheckVCSConnectionStatusUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CheckVCSConnectionStatusUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this check v c s connection status unauthorized response has a 2xx status code
func (o *CheckVCSConnectionStatusUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check v c s connection status unauthorized response has a 3xx status code
func (o *CheckVCSConnectionStatusUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check v c s connection status unauthorized response has a 4xx status code
func (o *CheckVCSConnectionStatusUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this check v c s connection status unauthorized response has a 5xx status code
func (o *CheckVCSConnectionStatusUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this check v c s connection status unauthorized response a status code equal to that given
func (o *CheckVCSConnectionStatusUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the check v c s connection status unauthorized response
func (o *CheckVCSConnectionStatusUnauthorized) Code() int {
	return 401
}

func (o *CheckVCSConnectionStatusUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusUnauthorized %s", 401, payload)
}

func (o *CheckVCSConnectionStatusUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusUnauthorized %s", 401, payload)
}

func (o *CheckVCSConnectionStatusUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CheckVCSConnectionStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCheckVCSConnectionStatusForbidden creates a CheckVCSConnectionStatusForbidden with default headers values
func NewCheckVCSConnectionStatusForbidden() *CheckVCSConnectionStatusForbidden {
	return &CheckVCSConnectionStatusForbidden{}
}

/*
CheckVCSConnectionStatusForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CheckVCSConnectionStatusForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this check v c s connection status forbidden response has a 2xx status code
func (o *CheckVCSConnectionStatusForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check v c s connection status forbidden response has a 3xx status code
func (o *CheckVCSConnectionStatusForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check v c s connection status forbidden response has a 4xx status code
func (o *CheckVCSConnectionStatusForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this check v c s connection status forbidden response has a 5xx status code
func (o *CheckVCSConnectionStatusForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this check v c s connection status forbidden response a status code equal to that given
func (o *CheckVCSConnectionStatusForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the check v c s connection status forbidden response
func (o *CheckVCSConnectionStatusForbidden) Code() int {
	return 403
}

func (o *CheckVCSConnectionStatusForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusForbidden %s", 403, payload)
}

func (o *CheckVCSConnectionStatusForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusForbidden %s", 403, payload)
}

func (o *CheckVCSConnectionStatusForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CheckVCSConnectionStatusForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCheckVCSConnectionStatusNotFound creates a CheckVCSConnectionStatusNotFound with default headers values
func NewCheckVCSConnectionStatusNotFound() *CheckVCSConnectionStatusNotFound {
	return &CheckVCSConnectionStatusNotFound{}
}

/*
CheckVCSConnectionStatusNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CheckVCSConnectionStatusNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this check v c s connection status not found response has a 2xx status code
func (o *CheckVCSConnectionStatusNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check v c s connection status not found response has a 3xx status code
func (o *CheckVCSConnectionStatusNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check v c s connection status not found response has a 4xx status code
func (o *CheckVCSConnectionStatusNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this check v c s connection status not found response has a 5xx status code
func (o *CheckVCSConnectionStatusNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this check v c s connection status not found response a status code equal to that given
func (o *CheckVCSConnectionStatusNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the check v c s connection status not found response
func (o *CheckVCSConnectionStatusNotFound) Code() int {
	return 404
}

func (o *CheckVCSConnectionStatusNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusNotFound %s", 404, payload)
}

func (o *CheckVCSConnectionStatusNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusNotFound %s", 404, payload)
}

func (o *CheckVCSConnectionStatusNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CheckVCSConnectionStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCheckVCSConnectionStatusInternalServerError creates a CheckVCSConnectionStatusInternalServerError with default headers values
func NewCheckVCSConnectionStatusInternalServerError() *CheckVCSConnectionStatusInternalServerError {
	return &CheckVCSConnectionStatusInternalServerError{}
}

/*
CheckVCSConnectionStatusInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CheckVCSConnectionStatusInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this check v c s connection status internal server error response has a 2xx status code
func (o *CheckVCSConnectionStatusInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this check v c s connection status internal server error response has a 3xx status code
func (o *CheckVCSConnectionStatusInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this check v c s connection status internal server error response has a 4xx status code
func (o *CheckVCSConnectionStatusInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this check v c s connection status internal server error response has a 5xx status code
func (o *CheckVCSConnectionStatusInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this check v c s connection status internal server error response a status code equal to that given
func (o *CheckVCSConnectionStatusInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the check v c s connection status internal server error response
func (o *CheckVCSConnectionStatusInternalServerError) Code() int {
	return 500
}

func (o *CheckVCSConnectionStatusInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusInternalServerError %s", 500, payload)
}

func (o *CheckVCSConnectionStatusInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/vcs/connections/{connection_id}/check-status][%d] checkVCSConnectionStatusInternalServerError %s", 500, payload)
}

func (o *CheckVCSConnectionStatusInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CheckVCSConnectionStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
