// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// NewCreateRunbookConfigParams creates a new CreateRunbookConfigParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateRunbookConfigParams() *CreateRunbookConfigParams {
	return &CreateRunbookConfigParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateRunbookConfigParamsWithTimeout creates a new CreateRunbookConfigParams object
// with the ability to set a timeout on a request.
func NewCreateRunbookConfigParamsWithTimeout(timeout time.Duration) *CreateRunbookConfigParams {
	return &CreateRunbookConfigParams{
		timeout: timeout,
	}
}

// NewCreateRunbookConfigParamsWithContext creates a new CreateRunbookConfigParams object
// with the ability to set a context for a request.
func NewCreateRunbookConfigParamsWithContext(ctx context.Context) *CreateRunbookConfigParams {
	return &CreateRunbookConfigParams{
		Context: ctx,
	}
}

// NewCreateRunbookConfigParamsWithHTTPClient creates a new CreateRunbookConfigParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateRunbookConfigParamsWithHTTPClient(client *http.Client) *CreateRunbookConfigParams {
	return &CreateRunbookConfigParams{
		HTTPClient: client,
	}
}

/*
CreateRunbookConfigParams contains all the parameters to send to the API endpoint

	for the create runbook config operation.

	Typically these are written to a http.Request.
*/
type CreateRunbookConfigParams struct {

	/* AppID.

	   app ID
	*/
	AppID string

	/* Req.

	   Input
	*/
	Req *models.ServiceCreateRunbookConfigRequest

	/* RunbookID.

	   runbook ID
	*/
	RunbookID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create runbook config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRunbookConfigParams) WithDefaults() *CreateRunbookConfigParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create runbook config params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateRunbookConfigParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create runbook config params
func (o *CreateRunbookConfigParams) WithTimeout(timeout time.Duration) *CreateRunbookConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create runbook config params
func (o *CreateRunbookConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create runbook config params
func (o *CreateRunbookConfigParams) WithContext(ctx context.Context) *CreateRunbookConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create runbook config params
func (o *CreateRunbookConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create runbook config params
func (o *CreateRunbookConfigParams) WithHTTPClient(client *http.Client) *CreateRunbookConfigParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create runbook config params
func (o *CreateRunbookConfigParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the create runbook config params
func (o *CreateRunbookConfigParams) WithAppID(appID string) *CreateRunbookConfigParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the create runbook config params
func (o *CreateRunbookConfigParams) SetAppID(appID string) {
	o.AppID = appID
}

// WithReq adds the req to the create runbook config params
func (o *CreateRunbookConfigParams) WithReq(req *models.ServiceCreateRunbookConfigRequest) *CreateRunbookConfigParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the create runbook config params
func (o *CreateRunbookConfigParams) SetReq(req *models.ServiceCreateRunbookConfigRequest) {
	o.Req = req
}

// WithRunbookID adds the runbookID to the create runbook config params
func (o *CreateRunbookConfigParams) WithRunbookID(runbookID string) *CreateRunbookConfigParams {
	o.SetRunbookID(runbookID)
	return o
}

// SetRunbookID adds the runbookId to the create runbook config params
func (o *CreateRunbookConfigParams) SetRunbookID(runbookID string) {
	o.RunbookID = runbookID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateRunbookConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param app_id
	if err := r.SetPathParam("app_id", o.AppID); err != nil {
		return err
	}
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	// path param runbook_id
	if err := r.SetPathParam("runbook_id", o.RunbookID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
