// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// DeleteAppBranchReader is a Reader for the DeleteAppBranch structure.
type DeleteAppBranchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAppBranchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAppBranchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAppBranchBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAppBranchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteAppBranchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteAppBranchNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAppBranchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}] DeleteAppBranch", response, response.Code())
	}
}

// NewDeleteAppBranchOK creates a DeleteAppBranchOK with default headers values
func NewDeleteAppBranchOK() *DeleteAppBranchOK {
	return &DeleteAppBranchOK{}
}

/*
DeleteAppBranchOK describes a response with status code 200, with default header values.

OK
*/
type DeleteAppBranchOK struct {
	Payload models.AppEmptyResponse
}

// IsSuccess returns true when this delete app branch o k response has a 2xx status code
func (o *DeleteAppBranchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete app branch o k response has a 3xx status code
func (o *DeleteAppBranchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete app branch o k response has a 4xx status code
func (o *DeleteAppBranchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete app branch o k response has a 5xx status code
func (o *DeleteAppBranchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete app branch o k response a status code equal to that given
func (o *DeleteAppBranchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete app branch o k response
func (o *DeleteAppBranchOK) Code() int {
	return 200
}

func (o *DeleteAppBranchOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchOK %s", 200, payload)
}

func (o *DeleteAppBranchOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchOK %s", 200, payload)
}

func (o *DeleteAppBranchOK) GetPayload() models.AppEmptyResponse {
	return o.Payload
}

func (o *DeleteAppBranchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAppBranchBadRequest creates a DeleteAppBranchBadRequest with default headers values
func NewDeleteAppBranchBadRequest() *DeleteAppBranchBadRequest {
	return &DeleteAppBranchBadRequest{}
}

/*
DeleteAppBranchBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type DeleteAppBranchBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this delete app branch bad request response has a 2xx status code
func (o *DeleteAppBranchBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete app branch bad request response has a 3xx status code
func (o *DeleteAppBranchBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete app branch bad request response has a 4xx status code
func (o *DeleteAppBranchBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete app branch bad request response has a 5xx status code
func (o *DeleteAppBranchBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete app branch bad request response a status code equal to that given
func (o *DeleteAppBranchBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete app branch bad request response
func (o *DeleteAppBranchBadRequest) Code() int {
	return 400
}

func (o *DeleteAppBranchBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchBadRequest %s", 400, payload)
}

func (o *DeleteAppBranchBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchBadRequest %s", 400, payload)
}

func (o *DeleteAppBranchBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *DeleteAppBranchBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAppBranchUnauthorized creates a DeleteAppBranchUnauthorized with default headers values
func NewDeleteAppBranchUnauthorized() *DeleteAppBranchUnauthorized {
	return &DeleteAppBranchUnauthorized{}
}

/*
DeleteAppBranchUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type DeleteAppBranchUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this delete app branch unauthorized response has a 2xx status code
func (o *DeleteAppBranchUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete app branch unauthorized response has a 3xx status code
func (o *DeleteAppBranchUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete app branch unauthorized response has a 4xx status code
func (o *DeleteAppBranchUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete app branch unauthorized response has a 5xx status code
func (o *DeleteAppBranchUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete app branch unauthorized response a status code equal to that given
func (o *DeleteAppBranchUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete app branch unauthorized response
func (o *DeleteAppBranchUnauthorized) Code() int {
	return 401
}

func (o *DeleteAppBranchUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchUnauthorized %s", 401, payload)
}

func (o *DeleteAppBranchUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchUnauthorized %s", 401, payload)
}

func (o *DeleteAppBranchUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *DeleteAppBranchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAppBranchForbidden creates a DeleteAppBranchForbidden with default headers values
func NewDeleteAppBranchForbidden() *DeleteAppBranchForbidden {
	return &DeleteAppBranchForbidden{}
}

/*
DeleteAppBranchForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteAppBranchForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this delete app branch forbidden response has a 2xx status code
func (o *DeleteAppBranchForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete app branch forbidden response has a 3xx status code
func (o *DeleteAppBranchForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete app branch forbidden response has a 4xx status code
func (o *DeleteAppBranchForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete app branch forbidden response has a 5xx status code
func (o *DeleteAppBranchForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this delete app branch forbidden response a status code equal to that given
func (o *DeleteAppBranchForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the delete app branch forbidden response
func (o *DeleteAppBranchForbidden) Code() int {
	return 403
}

func (o *DeleteAppBranchForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchForbidden %s", 403, payload)
}

func (o *DeleteAppBranchForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchForbidden %s", 403, payload)
}

func (o *DeleteAppBranchForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *DeleteAppBranchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAppBranchNotFound creates a DeleteAppBranchNotFound with default headers values
func NewDeleteAppBranchNotFound() *DeleteAppBranchNotFound {
	return &DeleteAppBranchNotFound{}
}

/*
DeleteAppBranchNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteAppBranchNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this delete app branch not found response has a 2xx status code
func (o *DeleteAppBranchNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete app branch not found response has a 3xx status code
func (o *DeleteAppBranchNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete app branch not found response has a 4xx status code
func (o *DeleteAppBranchNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete app branch not found response has a 5xx status code
func (o *DeleteAppBranchNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete app branch not found response a status code equal to that given
func (o *DeleteAppBranchNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete app branch not found response
func (o *DeleteAppBranchNotFound) Code() int {
	return 404
}

func (o *DeleteAppBranchNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchNotFound %s", 404, payload)
}

func (o *DeleteAppBranchNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchNotFound %s", 404, payload)
}

func (o *DeleteAppBranchNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *DeleteAppBranchNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAppBranchInternalServerError creates a DeleteAppBranchInternalServerError with default headers values
func NewDeleteAppBranchInternalServerError() *DeleteAppBranchInternalServerError {
	return &DeleteAppBranchInternalServerError{}
}

/*
DeleteAppBranchInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteAppBranchInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this delete app branch internal server error response has a 2xx status code
func (o *DeleteAppBranchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete app branch internal server error response has a 3xx status code
func (o *DeleteAppBranchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete app branch internal server error response has a 4xx status code
func (o *DeleteAppBranchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete app branch internal server error response has a 5xx status code
func (o *DeleteAppBranchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete app branch internal server error response a status code equal to that given
func (o *DeleteAppBranchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete app branch internal server error response
func (o *DeleteAppBranchInternalServerError) Code() int {
	return 500
}

func (o *DeleteAppBranchInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchInternalServerError %s", 500, payload)
}

func (o *DeleteAppBranchInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /v1/apps/{app_id}/branches/{app_branch_id}][%d] deleteAppBranchInternalServerError %s", 500, payload)
}

func (o *DeleteAppBranchInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *DeleteAppBranchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
