// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPolicyReportParams creates a new GetPolicyReportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPolicyReportParams() *GetPolicyReportParams {
	return &GetPolicyReportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPolicyReportParamsWithTimeout creates a new GetPolicyReportParams object
// with the ability to set a timeout on a request.
func NewGetPolicyReportParamsWithTimeout(timeout time.Duration) *GetPolicyReportParams {
	return &GetPolicyReportParams{
		timeout: timeout,
	}
}

// NewGetPolicyReportParamsWithContext creates a new GetPolicyReportParams object
// with the ability to set a context for a request.
func NewGetPolicyReportParamsWithContext(ctx context.Context) *GetPolicyReportParams {
	return &GetPolicyReportParams{
		Context: ctx,
	}
}

// NewGetPolicyReportParamsWithHTTPClient creates a new GetPolicyReportParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPolicyReportParamsWithHTTPClient(client *http.Client) *GetPolicyReportParams {
	return &GetPolicyReportParams{
		HTTPClient: client,
	}
}

/*
GetPolicyReportParams contains all the parameters to send to the API endpoint

	for the get policy report operation.

	Typically these are written to a http.Request.
*/
type GetPolicyReportParams struct {

	/* ReportID.

	   policy report ID
	*/
	ReportID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get policy report params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPolicyReportParams) WithDefaults() *GetPolicyReportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get policy report params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPolicyReportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get policy report params
func (o *GetPolicyReportParams) WithTimeout(timeout time.Duration) *GetPolicyReportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get policy report params
func (o *GetPolicyReportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get policy report params
func (o *GetPolicyReportParams) WithContext(ctx context.Context) *GetPolicyReportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get policy report params
func (o *GetPolicyReportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get policy report params
func (o *GetPolicyReportParams) WithHTTPClient(client *http.Client) *GetPolicyReportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get policy report params
func (o *GetPolicyReportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReportID adds the reportID to the get policy report params
func (o *GetPolicyReportParams) WithReportID(reportID string) *GetPolicyReportParams {
	o.SetReportID(reportID)
	return o
}

// SetReportID adds the reportId to the get policy report params
func (o *GetPolicyReportParams) SetReportID(reportID string) {
	o.ReportID = reportID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPolicyReportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param report_id
	if err := r.SetPathParam("report_id", o.ReportID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
