// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// GetRunbooksReader is a Reader for the GetRunbooks structure.
type GetRunbooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRunbooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetRunbooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/apps/{app_id}/runbooks] GetRunbooks", response, response.Code())
	}
}

// NewGetRunbooksOK creates a GetRunbooksOK with default headers values
func NewGetRunbooksOK() *GetRunbooksOK {
	return &GetRunbooksOK{}
}

/*
GetRunbooksOK describes a response with status code 200, with default header values.

OK
*/
type GetRunbooksOK struct {
	Payload []*models.AppRunbook
}

// IsSuccess returns true when this get runbooks o k response has a 2xx status code
func (o *GetRunbooksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get runbooks o k response has a 3xx status code
func (o *GetRunbooksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get runbooks o k response has a 4xx status code
func (o *GetRunbooksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get runbooks o k response has a 5xx status code
func (o *GetRunbooksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get runbooks o k response a status code equal to that given
func (o *GetRunbooksOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get runbooks o k response
func (o *GetRunbooksOK) Code() int {
	return 200
}

func (o *GetRunbooksOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/runbooks][%d] getRunbooksOK %s", 200, payload)
}

func (o *GetRunbooksOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/runbooks][%d] getRunbooksOK %s", 200, payload)
}

func (o *GetRunbooksOK) GetPayload() []*models.AppRunbook {
	return o.Payload
}

func (o *GetRunbooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
