// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstallRunbookRunParams creates a new GetInstallRunbookRunParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallRunbookRunParams() *GetInstallRunbookRunParams {
	return &GetInstallRunbookRunParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallRunbookRunParamsWithTimeout creates a new GetInstallRunbookRunParams object
// with the ability to set a timeout on a request.
func NewGetInstallRunbookRunParamsWithTimeout(timeout time.Duration) *GetInstallRunbookRunParams {
	return &GetInstallRunbookRunParams{
		timeout: timeout,
	}
}

// NewGetInstallRunbookRunParamsWithContext creates a new GetInstallRunbookRunParams object
// with the ability to set a context for a request.
func NewGetInstallRunbookRunParamsWithContext(ctx context.Context) *GetInstallRunbookRunParams {
	return &GetInstallRunbookRunParams{
		Context: ctx,
	}
}

// NewGetInstallRunbookRunParamsWithHTTPClient creates a new GetInstallRunbookRunParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallRunbookRunParamsWithHTTPClient(client *http.Client) *GetInstallRunbookRunParams {
	return &GetInstallRunbookRunParams{
		HTTPClient: client,
	}
}

/*
GetInstallRunbookRunParams contains all the parameters to send to the API endpoint

	for the get install runbook run operation.

	Typically these are written to a http.Request.
*/
type GetInstallRunbookRunParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* RunID.

	   run ID
	*/
	RunID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get install runbook run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallRunbookRunParams) WithDefaults() *GetInstallRunbookRunParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get install runbook run params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallRunbookRunParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get install runbook run params
func (o *GetInstallRunbookRunParams) WithTimeout(timeout time.Duration) *GetInstallRunbookRunParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install runbook run params
func (o *GetInstallRunbookRunParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install runbook run params
func (o *GetInstallRunbookRunParams) WithContext(ctx context.Context) *GetInstallRunbookRunParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install runbook run params
func (o *GetInstallRunbookRunParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install runbook run params
func (o *GetInstallRunbookRunParams) WithHTTPClient(client *http.Client) *GetInstallRunbookRunParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install runbook run params
func (o *GetInstallRunbookRunParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get install runbook run params
func (o *GetInstallRunbookRunParams) WithInstallID(installID string) *GetInstallRunbookRunParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get install runbook run params
func (o *GetInstallRunbookRunParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithRunID adds the runID to the get install runbook run params
func (o *GetInstallRunbookRunParams) WithRunID(runID string) *GetInstallRunbookRunParams {
	o.SetRunID(runID)
	return o
}

// SetRunID adds the runId to the get install runbook run params
func (o *GetInstallRunbookRunParams) SetRunID(runID string) {
	o.RunID = runID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallRunbookRunParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	// path param run_id
	if err := r.SetPathParam("run_id", o.RunID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
