// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetVCSConnectionWebhookSubscriptionParams creates a new GetVCSConnectionWebhookSubscriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetVCSConnectionWebhookSubscriptionParams() *GetVCSConnectionWebhookSubscriptionParams {
	return &GetVCSConnectionWebhookSubscriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetVCSConnectionWebhookSubscriptionParamsWithTimeout creates a new GetVCSConnectionWebhookSubscriptionParams object
// with the ability to set a timeout on a request.
func NewGetVCSConnectionWebhookSubscriptionParamsWithTimeout(timeout time.Duration) *GetVCSConnectionWebhookSubscriptionParams {
	return &GetVCSConnectionWebhookSubscriptionParams{
		timeout: timeout,
	}
}

// NewGetVCSConnectionWebhookSubscriptionParamsWithContext creates a new GetVCSConnectionWebhookSubscriptionParams object
// with the ability to set a context for a request.
func NewGetVCSConnectionWebhookSubscriptionParamsWithContext(ctx context.Context) *GetVCSConnectionWebhookSubscriptionParams {
	return &GetVCSConnectionWebhookSubscriptionParams{
		Context: ctx,
	}
}

// NewGetVCSConnectionWebhookSubscriptionParamsWithHTTPClient creates a new GetVCSConnectionWebhookSubscriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetVCSConnectionWebhookSubscriptionParamsWithHTTPClient(client *http.Client) *GetVCSConnectionWebhookSubscriptionParams {
	return &GetVCSConnectionWebhookSubscriptionParams{
		HTTPClient: client,
	}
}

/*
GetVCSConnectionWebhookSubscriptionParams contains all the parameters to send to the API endpoint

	for the get v c s connection webhook subscription operation.

	Typically these are written to a http.Request.
*/
type GetVCSConnectionWebhookSubscriptionParams struct {

	/* ConnectionID.

	   connection ID
	*/
	ConnectionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v c s connection webhook subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetVCSConnectionWebhookSubscriptionParams) WithDefaults() *GetVCSConnectionWebhookSubscriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v c s connection webhook subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetVCSConnectionWebhookSubscriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v c s connection webhook subscription params
func (o *GetVCSConnectionWebhookSubscriptionParams) WithTimeout(timeout time.Duration) *GetVCSConnectionWebhookSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v c s connection webhook subscription params
func (o *GetVCSConnectionWebhookSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v c s connection webhook subscription params
func (o *GetVCSConnectionWebhookSubscriptionParams) WithContext(ctx context.Context) *GetVCSConnectionWebhookSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v c s connection webhook subscription params
func (o *GetVCSConnectionWebhookSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v c s connection webhook subscription params
func (o *GetVCSConnectionWebhookSubscriptionParams) WithHTTPClient(client *http.Client) *GetVCSConnectionWebhookSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v c s connection webhook subscription params
func (o *GetVCSConnectionWebhookSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithConnectionID adds the connectionID to the get v c s connection webhook subscription params
func (o *GetVCSConnectionWebhookSubscriptionParams) WithConnectionID(connectionID string) *GetVCSConnectionWebhookSubscriptionParams {
	o.SetConnectionID(connectionID)
	return o
}

// SetConnectionID adds the connectionId to the get v c s connection webhook subscription params
func (o *GetVCSConnectionWebhookSubscriptionParams) SetConnectionID(connectionID string) {
	o.ConnectionID = connectionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetVCSConnectionWebhookSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param connection_id
	if err := r.SetPathParam("connection_id", o.ConnectionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
