// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetOrgFeaturesParams creates a new GetOrgFeaturesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetOrgFeaturesParams() *GetOrgFeaturesParams {
	return &GetOrgFeaturesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetOrgFeaturesParamsWithTimeout creates a new GetOrgFeaturesParams object
// with the ability to set a timeout on a request.
func NewGetOrgFeaturesParamsWithTimeout(timeout time.Duration) *GetOrgFeaturesParams {
	return &GetOrgFeaturesParams{
		timeout: timeout,
	}
}

// NewGetOrgFeaturesParamsWithContext creates a new GetOrgFeaturesParams object
// with the ability to set a context for a request.
func NewGetOrgFeaturesParamsWithContext(ctx context.Context) *GetOrgFeaturesParams {
	return &GetOrgFeaturesParams{
		Context: ctx,
	}
}

// NewGetOrgFeaturesParamsWithHTTPClient creates a new GetOrgFeaturesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetOrgFeaturesParamsWithHTTPClient(client *http.Client) *GetOrgFeaturesParams {
	return &GetOrgFeaturesParams{
		HTTPClient: client,
	}
}

/*
GetOrgFeaturesParams contains all the parameters to send to the API endpoint

	for the get org features operation.

	Typically these are written to a http.Request.
*/
type GetOrgFeaturesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get org features params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgFeaturesParams) WithDefaults() *GetOrgFeaturesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get org features params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetOrgFeaturesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get org features params
func (o *GetOrgFeaturesParams) WithTimeout(timeout time.Duration) *GetOrgFeaturesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get org features params
func (o *GetOrgFeaturesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get org features params
func (o *GetOrgFeaturesParams) WithContext(ctx context.Context) *GetOrgFeaturesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get org features params
func (o *GetOrgFeaturesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get org features params
func (o *GetOrgFeaturesParams) WithHTTPClient(client *http.Client) *GetOrgFeaturesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get org features params
func (o *GetOrgFeaturesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetOrgFeaturesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
