// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetInstallRunbooksParams creates a new GetInstallRunbooksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallRunbooksParams() *GetInstallRunbooksParams {
	return &GetInstallRunbooksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallRunbooksParamsWithTimeout creates a new GetInstallRunbooksParams object
// with the ability to set a timeout on a request.
func NewGetInstallRunbooksParamsWithTimeout(timeout time.Duration) *GetInstallRunbooksParams {
	return &GetInstallRunbooksParams{
		timeout: timeout,
	}
}

// NewGetInstallRunbooksParamsWithContext creates a new GetInstallRunbooksParams object
// with the ability to set a context for a request.
func NewGetInstallRunbooksParamsWithContext(ctx context.Context) *GetInstallRunbooksParams {
	return &GetInstallRunbooksParams{
		Context: ctx,
	}
}

// NewGetInstallRunbooksParamsWithHTTPClient creates a new GetInstallRunbooksParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallRunbooksParamsWithHTTPClient(client *http.Client) *GetInstallRunbooksParams {
	return &GetInstallRunbooksParams{
		HTTPClient: client,
	}
}

/*
GetInstallRunbooksParams contains all the parameters to send to the API endpoint

	for the get install runbooks operation.

	Typically these are written to a http.Request.
*/
type GetInstallRunbooksParams struct {

	/* InstallID.

	   install ID
	*/
	InstallID string

	/* Limit.

	   limit

	   Default: 10
	*/
	Limit *int64

	/* Offset.

	   offset
	*/
	Offset *int64

	/* Q.

	   search by runbook name or ID
	*/
	Q *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get install runbooks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallRunbooksParams) WithDefaults() *GetInstallRunbooksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get install runbooks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallRunbooksParams) SetDefaults() {
	var (
		limitDefault = int64(10)

		offsetDefault = int64(0)
	)

	val := GetInstallRunbooksParams{
		Limit:  &limitDefault,
		Offset: &offsetDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get install runbooks params
func (o *GetInstallRunbooksParams) WithTimeout(timeout time.Duration) *GetInstallRunbooksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install runbooks params
func (o *GetInstallRunbooksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install runbooks params
func (o *GetInstallRunbooksParams) WithContext(ctx context.Context) *GetInstallRunbooksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install runbooks params
func (o *GetInstallRunbooksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install runbooks params
func (o *GetInstallRunbooksParams) WithHTTPClient(client *http.Client) *GetInstallRunbooksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install runbooks params
func (o *GetInstallRunbooksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get install runbooks params
func (o *GetInstallRunbooksParams) WithInstallID(installID string) *GetInstallRunbooksParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get install runbooks params
func (o *GetInstallRunbooksParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithLimit adds the limit to the get install runbooks params
func (o *GetInstallRunbooksParams) WithLimit(limit *int64) *GetInstallRunbooksParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get install runbooks params
func (o *GetInstallRunbooksParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get install runbooks params
func (o *GetInstallRunbooksParams) WithOffset(offset *int64) *GetInstallRunbooksParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get install runbooks params
func (o *GetInstallRunbooksParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithQ adds the q to the get install runbooks params
func (o *GetInstallRunbooksParams) WithQ(q *string) *GetInstallRunbooksParams {
	o.SetQ(q)
	return o
}

// SetQ adds the q to the get install runbooks params
func (o *GetInstallRunbooksParams) SetQ(q *string) {
	o.Q = q
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallRunbooksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.Q != nil {

		// query param q
		var qrQ string

		if o.Q != nil {
			qrQ = *o.Q
		}
		qQ := qrQ
		if qQ != "" {

			if err := r.SetQueryParam("q", qQ); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
