// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetPolicyValidationReportsParams creates a new GetPolicyValidationReportsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetPolicyValidationReportsParams() *GetPolicyValidationReportsParams {
	return &GetPolicyValidationReportsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetPolicyValidationReportsParamsWithTimeout creates a new GetPolicyValidationReportsParams object
// with the ability to set a timeout on a request.
func NewGetPolicyValidationReportsParamsWithTimeout(timeout time.Duration) *GetPolicyValidationReportsParams {
	return &GetPolicyValidationReportsParams{
		timeout: timeout,
	}
}

// NewGetPolicyValidationReportsParamsWithContext creates a new GetPolicyValidationReportsParams object
// with the ability to set a context for a request.
func NewGetPolicyValidationReportsParamsWithContext(ctx context.Context) *GetPolicyValidationReportsParams {
	return &GetPolicyValidationReportsParams{
		Context: ctx,
	}
}

// NewGetPolicyValidationReportsParamsWithHTTPClient creates a new GetPolicyValidationReportsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetPolicyValidationReportsParamsWithHTTPClient(client *http.Client) *GetPolicyValidationReportsParams {
	return &GetPolicyValidationReportsParams{
		HTTPClient: client,
	}
}

/*
GetPolicyValidationReportsParams contains all the parameters to send to the API endpoint

	for the get policy validation reports operation.

	Typically these are written to a http.Request.
*/
type GetPolicyValidationReportsParams struct {

	/* Format.

	   export format: opa, sarif, html (default: opa)
	*/
	Format *string

	/* ValidationID.

	   policy validation ID
	*/
	ValidationID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get policy validation reports params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPolicyValidationReportsParams) WithDefaults() *GetPolicyValidationReportsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get policy validation reports params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetPolicyValidationReportsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) WithTimeout(timeout time.Duration) *GetPolicyValidationReportsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) WithContext(ctx context.Context) *GetPolicyValidationReportsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) WithHTTPClient(client *http.Client) *GetPolicyValidationReportsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFormat adds the format to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) WithFormat(format *string) *GetPolicyValidationReportsParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) SetFormat(format *string) {
	o.Format = format
}

// WithValidationID adds the validationID to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) WithValidationID(validationID string) *GetPolicyValidationReportsParams {
	o.SetValidationID(validationID)
	return o
}

// SetValidationID adds the validationId to the get policy validation reports params
func (o *GetPolicyValidationReportsParams) SetValidationID(validationID string) {
	o.ValidationID = validationID
}

// WriteToRequest writes these params to a swagger request
func (o *GetPolicyValidationReportsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Format != nil {

		// query param format
		var qrFormat string

		if o.Format != nil {
			qrFormat = *o.Format
		}
		qFormat := qrFormat
		if qFormat != "" {

			if err := r.SetQueryParam("format", qFormat); err != nil {
				return err
			}
		}
	}

	// path param validation_id
	if err := r.SetPathParam("validation_id", o.ValidationID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
