// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// GetAppBranchRunsReader is a Reader for the GetAppBranchRuns structure.
type GetAppBranchRunsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppBranchRunsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAppBranchRunsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAppBranchRunsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAppBranchRunsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAppBranchRunsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAppBranchRunsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAppBranchRunsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs] GetAppBranchRuns", response, response.Code())
	}
}

// NewGetAppBranchRunsOK creates a GetAppBranchRunsOK with default headers values
func NewGetAppBranchRunsOK() *GetAppBranchRunsOK {
	return &GetAppBranchRunsOK{}
}

/*
GetAppBranchRunsOK describes a response with status code 200, with default header values.

OK
*/
type GetAppBranchRunsOK struct {
	Payload []*models.AppWorkflow
}

// IsSuccess returns true when this get app branch runs o k response has a 2xx status code
func (o *GetAppBranchRunsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get app branch runs o k response has a 3xx status code
func (o *GetAppBranchRunsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app branch runs o k response has a 4xx status code
func (o *GetAppBranchRunsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get app branch runs o k response has a 5xx status code
func (o *GetAppBranchRunsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get app branch runs o k response a status code equal to that given
func (o *GetAppBranchRunsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get app branch runs o k response
func (o *GetAppBranchRunsOK) Code() int {
	return 200
}

func (o *GetAppBranchRunsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsOK %s", 200, payload)
}

func (o *GetAppBranchRunsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsOK %s", 200, payload)
}

func (o *GetAppBranchRunsOK) GetPayload() []*models.AppWorkflow {
	return o.Payload
}

func (o *GetAppBranchRunsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppBranchRunsBadRequest creates a GetAppBranchRunsBadRequest with default headers values
func NewGetAppBranchRunsBadRequest() *GetAppBranchRunsBadRequest {
	return &GetAppBranchRunsBadRequest{}
}

/*
GetAppBranchRunsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAppBranchRunsBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app branch runs bad request response has a 2xx status code
func (o *GetAppBranchRunsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app branch runs bad request response has a 3xx status code
func (o *GetAppBranchRunsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app branch runs bad request response has a 4xx status code
func (o *GetAppBranchRunsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get app branch runs bad request response has a 5xx status code
func (o *GetAppBranchRunsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get app branch runs bad request response a status code equal to that given
func (o *GetAppBranchRunsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get app branch runs bad request response
func (o *GetAppBranchRunsBadRequest) Code() int {
	return 400
}

func (o *GetAppBranchRunsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsBadRequest %s", 400, payload)
}

func (o *GetAppBranchRunsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsBadRequest %s", 400, payload)
}

func (o *GetAppBranchRunsBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppBranchRunsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppBranchRunsUnauthorized creates a GetAppBranchRunsUnauthorized with default headers values
func NewGetAppBranchRunsUnauthorized() *GetAppBranchRunsUnauthorized {
	return &GetAppBranchRunsUnauthorized{}
}

/*
GetAppBranchRunsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAppBranchRunsUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app branch runs unauthorized response has a 2xx status code
func (o *GetAppBranchRunsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app branch runs unauthorized response has a 3xx status code
func (o *GetAppBranchRunsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app branch runs unauthorized response has a 4xx status code
func (o *GetAppBranchRunsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get app branch runs unauthorized response has a 5xx status code
func (o *GetAppBranchRunsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get app branch runs unauthorized response a status code equal to that given
func (o *GetAppBranchRunsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get app branch runs unauthorized response
func (o *GetAppBranchRunsUnauthorized) Code() int {
	return 401
}

func (o *GetAppBranchRunsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsUnauthorized %s", 401, payload)
}

func (o *GetAppBranchRunsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsUnauthorized %s", 401, payload)
}

func (o *GetAppBranchRunsUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppBranchRunsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppBranchRunsForbidden creates a GetAppBranchRunsForbidden with default headers values
func NewGetAppBranchRunsForbidden() *GetAppBranchRunsForbidden {
	return &GetAppBranchRunsForbidden{}
}

/*
GetAppBranchRunsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAppBranchRunsForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app branch runs forbidden response has a 2xx status code
func (o *GetAppBranchRunsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app branch runs forbidden response has a 3xx status code
func (o *GetAppBranchRunsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app branch runs forbidden response has a 4xx status code
func (o *GetAppBranchRunsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get app branch runs forbidden response has a 5xx status code
func (o *GetAppBranchRunsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get app branch runs forbidden response a status code equal to that given
func (o *GetAppBranchRunsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get app branch runs forbidden response
func (o *GetAppBranchRunsForbidden) Code() int {
	return 403
}

func (o *GetAppBranchRunsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsForbidden %s", 403, payload)
}

func (o *GetAppBranchRunsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsForbidden %s", 403, payload)
}

func (o *GetAppBranchRunsForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppBranchRunsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppBranchRunsNotFound creates a GetAppBranchRunsNotFound with default headers values
func NewGetAppBranchRunsNotFound() *GetAppBranchRunsNotFound {
	return &GetAppBranchRunsNotFound{}
}

/*
GetAppBranchRunsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAppBranchRunsNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app branch runs not found response has a 2xx status code
func (o *GetAppBranchRunsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app branch runs not found response has a 3xx status code
func (o *GetAppBranchRunsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app branch runs not found response has a 4xx status code
func (o *GetAppBranchRunsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get app branch runs not found response has a 5xx status code
func (o *GetAppBranchRunsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get app branch runs not found response a status code equal to that given
func (o *GetAppBranchRunsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get app branch runs not found response
func (o *GetAppBranchRunsNotFound) Code() int {
	return 404
}

func (o *GetAppBranchRunsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsNotFound %s", 404, payload)
}

func (o *GetAppBranchRunsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsNotFound %s", 404, payload)
}

func (o *GetAppBranchRunsNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppBranchRunsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAppBranchRunsInternalServerError creates a GetAppBranchRunsInternalServerError with default headers values
func NewGetAppBranchRunsInternalServerError() *GetAppBranchRunsInternalServerError {
	return &GetAppBranchRunsInternalServerError{}
}

/*
GetAppBranchRunsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAppBranchRunsInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get app branch runs internal server error response has a 2xx status code
func (o *GetAppBranchRunsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get app branch runs internal server error response has a 3xx status code
func (o *GetAppBranchRunsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get app branch runs internal server error response has a 4xx status code
func (o *GetAppBranchRunsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get app branch runs internal server error response has a 5xx status code
func (o *GetAppBranchRunsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get app branch runs internal server error response a status code equal to that given
func (o *GetAppBranchRunsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get app branch runs internal server error response
func (o *GetAppBranchRunsInternalServerError) Code() int {
	return 500
}

func (o *GetAppBranchRunsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsInternalServerError %s", 500, payload)
}

func (o *GetAppBranchRunsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/apps/{app_id}/branches/{app_branch_id}/runs][%d] getAppBranchRunsInternalServerError %s", 500, payload)
}

func (o *GetAppBranchRunsInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAppBranchRunsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
