// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetQueueSignalParams creates a new GetQueueSignalParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetQueueSignalParams() *GetQueueSignalParams {
	return &GetQueueSignalParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetQueueSignalParamsWithTimeout creates a new GetQueueSignalParams object
// with the ability to set a timeout on a request.
func NewGetQueueSignalParamsWithTimeout(timeout time.Duration) *GetQueueSignalParams {
	return &GetQueueSignalParams{
		timeout: timeout,
	}
}

// NewGetQueueSignalParamsWithContext creates a new GetQueueSignalParams object
// with the ability to set a context for a request.
func NewGetQueueSignalParamsWithContext(ctx context.Context) *GetQueueSignalParams {
	return &GetQueueSignalParams{
		Context: ctx,
	}
}

// NewGetQueueSignalParamsWithHTTPClient creates a new GetQueueSignalParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetQueueSignalParamsWithHTTPClient(client *http.Client) *GetQueueSignalParams {
	return &GetQueueSignalParams{
		HTTPClient: client,
	}
}

/*
GetQueueSignalParams contains all the parameters to send to the API endpoint

	for the get queue signal operation.

	Typically these are written to a http.Request.
*/
type GetQueueSignalParams struct {

	/* QueueID.

	   Queue ID
	*/
	QueueID string

	/* SignalID.

	   Signal ID
	*/
	SignalID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get queue signal params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetQueueSignalParams) WithDefaults() *GetQueueSignalParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get queue signal params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetQueueSignalParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get queue signal params
func (o *GetQueueSignalParams) WithTimeout(timeout time.Duration) *GetQueueSignalParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get queue signal params
func (o *GetQueueSignalParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get queue signal params
func (o *GetQueueSignalParams) WithContext(ctx context.Context) *GetQueueSignalParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get queue signal params
func (o *GetQueueSignalParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get queue signal params
func (o *GetQueueSignalParams) WithHTTPClient(client *http.Client) *GetQueueSignalParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get queue signal params
func (o *GetQueueSignalParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQueueID adds the queueID to the get queue signal params
func (o *GetQueueSignalParams) WithQueueID(queueID string) *GetQueueSignalParams {
	o.SetQueueID(queueID)
	return o
}

// SetQueueID adds the queueId to the get queue signal params
func (o *GetQueueSignalParams) SetQueueID(queueID string) {
	o.QueueID = queueID
}

// WithSignalID adds the signalID to the get queue signal params
func (o *GetQueueSignalParams) WithSignalID(signalID string) *GetQueueSignalParams {
	o.SetSignalID(signalID)
	return o
}

// SetSignalID adds the signalId to the get queue signal params
func (o *GetQueueSignalParams) SetSignalID(signalID string) {
	o.SignalID = signalID
}

// WriteToRequest writes these params to a swagger request
func (o *GetQueueSignalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param queue_id
	if err := r.SetPathParam("queue_id", o.QueueID); err != nil {
		return err
	}

	// path param signal_id
	if err := r.SetPathParam("signal_id", o.SignalID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
