// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// GetAvailableRolesReader is a Reader for the GetAvailableRoles structure.
type GetAvailableRolesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAvailableRolesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAvailableRolesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAvailableRolesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAvailableRolesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAvailableRolesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAvailableRolesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAvailableRolesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /v1/installs/{install_id}/available-roles] GetAvailableRoles", response, response.Code())
	}
}

// NewGetAvailableRolesOK creates a GetAvailableRolesOK with default headers values
func NewGetAvailableRolesOK() *GetAvailableRolesOK {
	return &GetAvailableRolesOK{}
}

/*
GetAvailableRolesOK describes a response with status code 200, with default header values.

OK
*/
type GetAvailableRolesOK struct {
	Payload *models.ServiceAvailableRolesResponse
}

// IsSuccess returns true when this get available roles o k response has a 2xx status code
func (o *GetAvailableRolesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get available roles o k response has a 3xx status code
func (o *GetAvailableRolesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available roles o k response has a 4xx status code
func (o *GetAvailableRolesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get available roles o k response has a 5xx status code
func (o *GetAvailableRolesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get available roles o k response a status code equal to that given
func (o *GetAvailableRolesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get available roles o k response
func (o *GetAvailableRolesOK) Code() int {
	return 200
}

func (o *GetAvailableRolesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesOK %s", 200, payload)
}

func (o *GetAvailableRolesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesOK %s", 200, payload)
}

func (o *GetAvailableRolesOK) GetPayload() *models.ServiceAvailableRolesResponse {
	return o.Payload
}

func (o *GetAvailableRolesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceAvailableRolesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAvailableRolesBadRequest creates a GetAvailableRolesBadRequest with default headers values
func NewGetAvailableRolesBadRequest() *GetAvailableRolesBadRequest {
	return &GetAvailableRolesBadRequest{}
}

/*
GetAvailableRolesBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetAvailableRolesBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get available roles bad request response has a 2xx status code
func (o *GetAvailableRolesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available roles bad request response has a 3xx status code
func (o *GetAvailableRolesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available roles bad request response has a 4xx status code
func (o *GetAvailableRolesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get available roles bad request response has a 5xx status code
func (o *GetAvailableRolesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get available roles bad request response a status code equal to that given
func (o *GetAvailableRolesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get available roles bad request response
func (o *GetAvailableRolesBadRequest) Code() int {
	return 400
}

func (o *GetAvailableRolesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesBadRequest %s", 400, payload)
}

func (o *GetAvailableRolesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesBadRequest %s", 400, payload)
}

func (o *GetAvailableRolesBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAvailableRolesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAvailableRolesUnauthorized creates a GetAvailableRolesUnauthorized with default headers values
func NewGetAvailableRolesUnauthorized() *GetAvailableRolesUnauthorized {
	return &GetAvailableRolesUnauthorized{}
}

/*
GetAvailableRolesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetAvailableRolesUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get available roles unauthorized response has a 2xx status code
func (o *GetAvailableRolesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available roles unauthorized response has a 3xx status code
func (o *GetAvailableRolesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available roles unauthorized response has a 4xx status code
func (o *GetAvailableRolesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get available roles unauthorized response has a 5xx status code
func (o *GetAvailableRolesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get available roles unauthorized response a status code equal to that given
func (o *GetAvailableRolesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get available roles unauthorized response
func (o *GetAvailableRolesUnauthorized) Code() int {
	return 401
}

func (o *GetAvailableRolesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesUnauthorized %s", 401, payload)
}

func (o *GetAvailableRolesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesUnauthorized %s", 401, payload)
}

func (o *GetAvailableRolesUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAvailableRolesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAvailableRolesForbidden creates a GetAvailableRolesForbidden with default headers values
func NewGetAvailableRolesForbidden() *GetAvailableRolesForbidden {
	return &GetAvailableRolesForbidden{}
}

/*
GetAvailableRolesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetAvailableRolesForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get available roles forbidden response has a 2xx status code
func (o *GetAvailableRolesForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available roles forbidden response has a 3xx status code
func (o *GetAvailableRolesForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available roles forbidden response has a 4xx status code
func (o *GetAvailableRolesForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get available roles forbidden response has a 5xx status code
func (o *GetAvailableRolesForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get available roles forbidden response a status code equal to that given
func (o *GetAvailableRolesForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get available roles forbidden response
func (o *GetAvailableRolesForbidden) Code() int {
	return 403
}

func (o *GetAvailableRolesForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesForbidden %s", 403, payload)
}

func (o *GetAvailableRolesForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesForbidden %s", 403, payload)
}

func (o *GetAvailableRolesForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAvailableRolesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAvailableRolesNotFound creates a GetAvailableRolesNotFound with default headers values
func NewGetAvailableRolesNotFound() *GetAvailableRolesNotFound {
	return &GetAvailableRolesNotFound{}
}

/*
GetAvailableRolesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetAvailableRolesNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get available roles not found response has a 2xx status code
func (o *GetAvailableRolesNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available roles not found response has a 3xx status code
func (o *GetAvailableRolesNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available roles not found response has a 4xx status code
func (o *GetAvailableRolesNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get available roles not found response has a 5xx status code
func (o *GetAvailableRolesNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get available roles not found response a status code equal to that given
func (o *GetAvailableRolesNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get available roles not found response
func (o *GetAvailableRolesNotFound) Code() int {
	return 404
}

func (o *GetAvailableRolesNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesNotFound %s", 404, payload)
}

func (o *GetAvailableRolesNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesNotFound %s", 404, payload)
}

func (o *GetAvailableRolesNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAvailableRolesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAvailableRolesInternalServerError creates a GetAvailableRolesInternalServerError with default headers values
func NewGetAvailableRolesInternalServerError() *GetAvailableRolesInternalServerError {
	return &GetAvailableRolesInternalServerError{}
}

/*
GetAvailableRolesInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetAvailableRolesInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this get available roles internal server error response has a 2xx status code
func (o *GetAvailableRolesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get available roles internal server error response has a 3xx status code
func (o *GetAvailableRolesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get available roles internal server error response has a 4xx status code
func (o *GetAvailableRolesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get available roles internal server error response has a 5xx status code
func (o *GetAvailableRolesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get available roles internal server error response a status code equal to that given
func (o *GetAvailableRolesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get available roles internal server error response
func (o *GetAvailableRolesInternalServerError) Code() int {
	return 500
}

func (o *GetAvailableRolesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesInternalServerError %s", 500, payload)
}

func (o *GetAvailableRolesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/installs/{install_id}/available-roles][%d] getAvailableRolesInternalServerError %s", 500, payload)
}

func (o *GetAvailableRolesInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *GetAvailableRolesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
