// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetCurrentOrgFeaturesReader is a Reader for the GetCurrentOrgFeatures structure.
type GetCurrentOrgFeaturesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCurrentOrgFeaturesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetCurrentOrgFeaturesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /v1/orgs/current/features] GetCurrentOrgFeatures", response, response.Code())
	}
}

// NewGetCurrentOrgFeaturesOK creates a GetCurrentOrgFeaturesOK with default headers values
func NewGetCurrentOrgFeaturesOK() *GetCurrentOrgFeaturesOK {
	return &GetCurrentOrgFeaturesOK{}
}

/*
GetCurrentOrgFeaturesOK describes a response with status code 200, with default header values.

OK
*/
type GetCurrentOrgFeaturesOK struct {
	Payload map[string]bool
}

// IsSuccess returns true when this get current org features o k response has a 2xx status code
func (o *GetCurrentOrgFeaturesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get current org features o k response has a 3xx status code
func (o *GetCurrentOrgFeaturesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get current org features o k response has a 4xx status code
func (o *GetCurrentOrgFeaturesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get current org features o k response has a 5xx status code
func (o *GetCurrentOrgFeaturesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get current org features o k response a status code equal to that given
func (o *GetCurrentOrgFeaturesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get current org features o k response
func (o *GetCurrentOrgFeaturesOK) Code() int {
	return 200
}

func (o *GetCurrentOrgFeaturesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/orgs/current/features][%d] getCurrentOrgFeaturesOK %s", 200, payload)
}

func (o *GetCurrentOrgFeaturesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1/orgs/current/features][%d] getCurrentOrgFeaturesOK %s", 200, payload)
}

func (o *GetCurrentOrgFeaturesOK) GetPayload() map[string]bool {
	return o.Payload
}

func (o *GetCurrentOrgFeaturesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
