// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// ResendOrgInviteReader is a Reader for the ResendOrgInvite structure.
type ResendOrgInviteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ResendOrgInviteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewResendOrgInviteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewResendOrgInviteBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewResendOrgInviteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewResendOrgInviteForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewResendOrgInviteNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewResendOrgInviteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/orgs/current/invites/{invite_id}/resend] ResendOrgInvite", response, response.Code())
	}
}

// NewResendOrgInviteOK creates a ResendOrgInviteOK with default headers values
func NewResendOrgInviteOK() *ResendOrgInviteOK {
	return &ResendOrgInviteOK{}
}

/*
ResendOrgInviteOK describes a response with status code 200, with default header values.

OK
*/
type ResendOrgInviteOK struct {
	Payload *models.AppOrgInvite
}

// IsSuccess returns true when this resend org invite o k response has a 2xx status code
func (o *ResendOrgInviteOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this resend org invite o k response has a 3xx status code
func (o *ResendOrgInviteOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resend org invite o k response has a 4xx status code
func (o *ResendOrgInviteOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this resend org invite o k response has a 5xx status code
func (o *ResendOrgInviteOK) IsServerError() bool {
	return false
}

// IsCode returns true when this resend org invite o k response a status code equal to that given
func (o *ResendOrgInviteOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the resend org invite o k response
func (o *ResendOrgInviteOK) Code() int {
	return 200
}

func (o *ResendOrgInviteOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteOK %s", 200, payload)
}

func (o *ResendOrgInviteOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteOK %s", 200, payload)
}

func (o *ResendOrgInviteOK) GetPayload() *models.AppOrgInvite {
	return o.Payload
}

func (o *ResendOrgInviteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppOrgInvite)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewResendOrgInviteBadRequest creates a ResendOrgInviteBadRequest with default headers values
func NewResendOrgInviteBadRequest() *ResendOrgInviteBadRequest {
	return &ResendOrgInviteBadRequest{}
}

/*
ResendOrgInviteBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type ResendOrgInviteBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this resend org invite bad request response has a 2xx status code
func (o *ResendOrgInviteBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resend org invite bad request response has a 3xx status code
func (o *ResendOrgInviteBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resend org invite bad request response has a 4xx status code
func (o *ResendOrgInviteBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this resend org invite bad request response has a 5xx status code
func (o *ResendOrgInviteBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this resend org invite bad request response a status code equal to that given
func (o *ResendOrgInviteBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the resend org invite bad request response
func (o *ResendOrgInviteBadRequest) Code() int {
	return 400
}

func (o *ResendOrgInviteBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteBadRequest %s", 400, payload)
}

func (o *ResendOrgInviteBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteBadRequest %s", 400, payload)
}

func (o *ResendOrgInviteBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *ResendOrgInviteBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewResendOrgInviteUnauthorized creates a ResendOrgInviteUnauthorized with default headers values
func NewResendOrgInviteUnauthorized() *ResendOrgInviteUnauthorized {
	return &ResendOrgInviteUnauthorized{}
}

/*
ResendOrgInviteUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ResendOrgInviteUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this resend org invite unauthorized response has a 2xx status code
func (o *ResendOrgInviteUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resend org invite unauthorized response has a 3xx status code
func (o *ResendOrgInviteUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resend org invite unauthorized response has a 4xx status code
func (o *ResendOrgInviteUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this resend org invite unauthorized response has a 5xx status code
func (o *ResendOrgInviteUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this resend org invite unauthorized response a status code equal to that given
func (o *ResendOrgInviteUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the resend org invite unauthorized response
func (o *ResendOrgInviteUnauthorized) Code() int {
	return 401
}

func (o *ResendOrgInviteUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteUnauthorized %s", 401, payload)
}

func (o *ResendOrgInviteUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteUnauthorized %s", 401, payload)
}

func (o *ResendOrgInviteUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *ResendOrgInviteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewResendOrgInviteForbidden creates a ResendOrgInviteForbidden with default headers values
func NewResendOrgInviteForbidden() *ResendOrgInviteForbidden {
	return &ResendOrgInviteForbidden{}
}

/*
ResendOrgInviteForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ResendOrgInviteForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this resend org invite forbidden response has a 2xx status code
func (o *ResendOrgInviteForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resend org invite forbidden response has a 3xx status code
func (o *ResendOrgInviteForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resend org invite forbidden response has a 4xx status code
func (o *ResendOrgInviteForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this resend org invite forbidden response has a 5xx status code
func (o *ResendOrgInviteForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this resend org invite forbidden response a status code equal to that given
func (o *ResendOrgInviteForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the resend org invite forbidden response
func (o *ResendOrgInviteForbidden) Code() int {
	return 403
}

func (o *ResendOrgInviteForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteForbidden %s", 403, payload)
}

func (o *ResendOrgInviteForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteForbidden %s", 403, payload)
}

func (o *ResendOrgInviteForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *ResendOrgInviteForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewResendOrgInviteNotFound creates a ResendOrgInviteNotFound with default headers values
func NewResendOrgInviteNotFound() *ResendOrgInviteNotFound {
	return &ResendOrgInviteNotFound{}
}

/*
ResendOrgInviteNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ResendOrgInviteNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this resend org invite not found response has a 2xx status code
func (o *ResendOrgInviteNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resend org invite not found response has a 3xx status code
func (o *ResendOrgInviteNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resend org invite not found response has a 4xx status code
func (o *ResendOrgInviteNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this resend org invite not found response has a 5xx status code
func (o *ResendOrgInviteNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this resend org invite not found response a status code equal to that given
func (o *ResendOrgInviteNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the resend org invite not found response
func (o *ResendOrgInviteNotFound) Code() int {
	return 404
}

func (o *ResendOrgInviteNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteNotFound %s", 404, payload)
}

func (o *ResendOrgInviteNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteNotFound %s", 404, payload)
}

func (o *ResendOrgInviteNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *ResendOrgInviteNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewResendOrgInviteInternalServerError creates a ResendOrgInviteInternalServerError with default headers values
func NewResendOrgInviteInternalServerError() *ResendOrgInviteInternalServerError {
	return &ResendOrgInviteInternalServerError{}
}

/*
ResendOrgInviteInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type ResendOrgInviteInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this resend org invite internal server error response has a 2xx status code
func (o *ResendOrgInviteInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this resend org invite internal server error response has a 3xx status code
func (o *ResendOrgInviteInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this resend org invite internal server error response has a 4xx status code
func (o *ResendOrgInviteInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this resend org invite internal server error response has a 5xx status code
func (o *ResendOrgInviteInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this resend org invite internal server error response a status code equal to that given
func (o *ResendOrgInviteInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the resend org invite internal server error response
func (o *ResendOrgInviteInternalServerError) Code() int {
	return 500
}

func (o *ResendOrgInviteInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteInternalServerError %s", 500, payload)
}

func (o *ResendOrgInviteInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/orgs/current/invites/{invite_id}/resend][%d] resendOrgInviteInternalServerError %s", 500, payload)
}

func (o *ResendOrgInviteInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *ResendOrgInviteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
