// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// SlackSlashCommandReader is a Reader for the SlackSlashCommand structure.
type SlackSlashCommandReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SlackSlashCommandReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSlackSlashCommandOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /slack/commands/nuon] SlackSlashCommand", response, response.Code())
	}
}

// NewSlackSlashCommandOK creates a SlackSlashCommandOK with default headers values
func NewSlackSlashCommandOK() *SlackSlashCommandOK {
	return &SlackSlashCommandOK{}
}

/*
SlackSlashCommandOK describes a response with status code 200, with default header values.

OK
*/
type SlackSlashCommandOK struct {
	Payload *models.ServiceSlashResponse
}

// IsSuccess returns true when this slack slash command o k response has a 2xx status code
func (o *SlackSlashCommandOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this slack slash command o k response has a 3xx status code
func (o *SlackSlashCommandOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this slack slash command o k response has a 4xx status code
func (o *SlackSlashCommandOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this slack slash command o k response has a 5xx status code
func (o *SlackSlashCommandOK) IsServerError() bool {
	return false
}

// IsCode returns true when this slack slash command o k response a status code equal to that given
func (o *SlackSlashCommandOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the slack slash command o k response
func (o *SlackSlashCommandOK) Code() int {
	return 200
}

func (o *SlackSlashCommandOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /slack/commands/nuon][%d] slackSlashCommandOK %s", 200, payload)
}

func (o *SlackSlashCommandOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /slack/commands/nuon][%d] slackSlashCommandOK %s", 200, payload)
}

func (o *SlackSlashCommandOK) GetPayload() *models.ServiceSlashResponse {
	return o.Payload
}

func (o *SlackSlashCommandOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceSlashResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
