// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// UpdateNotebookCellReader is a Reader for the UpdateNotebookCell structure.
type UpdateNotebookCellReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateNotebookCellReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateNotebookCellOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/installs/{install_id}/notebooks/{notebook_id}/cells/{cell_id}] UpdateNotebookCell", response, response.Code())
	}
}

// NewUpdateNotebookCellOK creates a UpdateNotebookCellOK with default headers values
func NewUpdateNotebookCellOK() *UpdateNotebookCellOK {
	return &UpdateNotebookCellOK{}
}

/*
UpdateNotebookCellOK describes a response with status code 200, with default header values.

OK
*/
type UpdateNotebookCellOK struct {
	Payload *models.AppNotebookCell
}

// IsSuccess returns true when this update notebook cell o k response has a 2xx status code
func (o *UpdateNotebookCellOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update notebook cell o k response has a 3xx status code
func (o *UpdateNotebookCellOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update notebook cell o k response has a 4xx status code
func (o *UpdateNotebookCellOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update notebook cell o k response has a 5xx status code
func (o *UpdateNotebookCellOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update notebook cell o k response a status code equal to that given
func (o *UpdateNotebookCellOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update notebook cell o k response
func (o *UpdateNotebookCellOK) Code() int {
	return 200
}

func (o *UpdateNotebookCellOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/installs/{install_id}/notebooks/{notebook_id}/cells/{cell_id}][%d] updateNotebookCellOK %s", 200, payload)
}

func (o *UpdateNotebookCellOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/installs/{install_id}/notebooks/{notebook_id}/cells/{cell_id}][%d] updateNotebookCellOK %s", 200, payload)
}

func (o *UpdateNotebookCellOK) GetPayload() *models.AppNotebookCell {
	return o.Payload
}

func (o *UpdateNotebookCellOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppNotebookCell)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
