// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-go/models"
)

// UpdateRunbookReader is a Reader for the UpdateRunbook structure.
type UpdateRunbookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateRunbookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateRunbookOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUpdateRunbookBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewUpdateRunbookUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUpdateRunbookForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUpdateRunbookNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewUpdateRunbookInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}] UpdateRunbook", response, response.Code())
	}
}

// NewUpdateRunbookOK creates a UpdateRunbookOK with default headers values
func NewUpdateRunbookOK() *UpdateRunbookOK {
	return &UpdateRunbookOK{}
}

/*
UpdateRunbookOK describes a response with status code 200, with default header values.

OK
*/
type UpdateRunbookOK struct {
	Payload *models.AppRunbook
}

// IsSuccess returns true when this update runbook o k response has a 2xx status code
func (o *UpdateRunbookOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this update runbook o k response has a 3xx status code
func (o *UpdateRunbookOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update runbook o k response has a 4xx status code
func (o *UpdateRunbookOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this update runbook o k response has a 5xx status code
func (o *UpdateRunbookOK) IsServerError() bool {
	return false
}

// IsCode returns true when this update runbook o k response a status code equal to that given
func (o *UpdateRunbookOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the update runbook o k response
func (o *UpdateRunbookOK) Code() int {
	return 200
}

func (o *UpdateRunbookOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookOK %s", 200, payload)
}

func (o *UpdateRunbookOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookOK %s", 200, payload)
}

func (o *UpdateRunbookOK) GetPayload() *models.AppRunbook {
	return o.Payload
}

func (o *UpdateRunbookOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppRunbook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateRunbookBadRequest creates a UpdateRunbookBadRequest with default headers values
func NewUpdateRunbookBadRequest() *UpdateRunbookBadRequest {
	return &UpdateRunbookBadRequest{}
}

/*
UpdateRunbookBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type UpdateRunbookBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update runbook bad request response has a 2xx status code
func (o *UpdateRunbookBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update runbook bad request response has a 3xx status code
func (o *UpdateRunbookBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update runbook bad request response has a 4xx status code
func (o *UpdateRunbookBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this update runbook bad request response has a 5xx status code
func (o *UpdateRunbookBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this update runbook bad request response a status code equal to that given
func (o *UpdateRunbookBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the update runbook bad request response
func (o *UpdateRunbookBadRequest) Code() int {
	return 400
}

func (o *UpdateRunbookBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookBadRequest %s", 400, payload)
}

func (o *UpdateRunbookBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookBadRequest %s", 400, payload)
}

func (o *UpdateRunbookBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateRunbookBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateRunbookUnauthorized creates a UpdateRunbookUnauthorized with default headers values
func NewUpdateRunbookUnauthorized() *UpdateRunbookUnauthorized {
	return &UpdateRunbookUnauthorized{}
}

/*
UpdateRunbookUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type UpdateRunbookUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update runbook unauthorized response has a 2xx status code
func (o *UpdateRunbookUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update runbook unauthorized response has a 3xx status code
func (o *UpdateRunbookUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update runbook unauthorized response has a 4xx status code
func (o *UpdateRunbookUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this update runbook unauthorized response has a 5xx status code
func (o *UpdateRunbookUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this update runbook unauthorized response a status code equal to that given
func (o *UpdateRunbookUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the update runbook unauthorized response
func (o *UpdateRunbookUnauthorized) Code() int {
	return 401
}

func (o *UpdateRunbookUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookUnauthorized %s", 401, payload)
}

func (o *UpdateRunbookUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookUnauthorized %s", 401, payload)
}

func (o *UpdateRunbookUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateRunbookUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateRunbookForbidden creates a UpdateRunbookForbidden with default headers values
func NewUpdateRunbookForbidden() *UpdateRunbookForbidden {
	return &UpdateRunbookForbidden{}
}

/*
UpdateRunbookForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type UpdateRunbookForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update runbook forbidden response has a 2xx status code
func (o *UpdateRunbookForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update runbook forbidden response has a 3xx status code
func (o *UpdateRunbookForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update runbook forbidden response has a 4xx status code
func (o *UpdateRunbookForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this update runbook forbidden response has a 5xx status code
func (o *UpdateRunbookForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this update runbook forbidden response a status code equal to that given
func (o *UpdateRunbookForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the update runbook forbidden response
func (o *UpdateRunbookForbidden) Code() int {
	return 403
}

func (o *UpdateRunbookForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookForbidden %s", 403, payload)
}

func (o *UpdateRunbookForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookForbidden %s", 403, payload)
}

func (o *UpdateRunbookForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateRunbookForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateRunbookNotFound creates a UpdateRunbookNotFound with default headers values
func NewUpdateRunbookNotFound() *UpdateRunbookNotFound {
	return &UpdateRunbookNotFound{}
}

/*
UpdateRunbookNotFound describes a response with status code 404, with default header values.

Not Found
*/
type UpdateRunbookNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update runbook not found response has a 2xx status code
func (o *UpdateRunbookNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update runbook not found response has a 3xx status code
func (o *UpdateRunbookNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update runbook not found response has a 4xx status code
func (o *UpdateRunbookNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this update runbook not found response has a 5xx status code
func (o *UpdateRunbookNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this update runbook not found response a status code equal to that given
func (o *UpdateRunbookNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the update runbook not found response
func (o *UpdateRunbookNotFound) Code() int {
	return 404
}

func (o *UpdateRunbookNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookNotFound %s", 404, payload)
}

func (o *UpdateRunbookNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookNotFound %s", 404, payload)
}

func (o *UpdateRunbookNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateRunbookNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewUpdateRunbookInternalServerError creates a UpdateRunbookInternalServerError with default headers values
func NewUpdateRunbookInternalServerError() *UpdateRunbookInternalServerError {
	return &UpdateRunbookInternalServerError{}
}

/*
UpdateRunbookInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type UpdateRunbookInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this update runbook internal server error response has a 2xx status code
func (o *UpdateRunbookInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this update runbook internal server error response has a 3xx status code
func (o *UpdateRunbookInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this update runbook internal server error response has a 4xx status code
func (o *UpdateRunbookInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this update runbook internal server error response has a 5xx status code
func (o *UpdateRunbookInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this update runbook internal server error response a status code equal to that given
func (o *UpdateRunbookInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the update runbook internal server error response
func (o *UpdateRunbookInternalServerError) Code() int {
	return 500
}

func (o *UpdateRunbookInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookInternalServerError %s", 500, payload)
}

func (o *UpdateRunbookInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /v1/apps/{app_id}/runbooks/{runbook_id}][%d] updateRunbookInternalServerError %s", 500, payload)
}

func (o *UpdateRunbookInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *UpdateRunbookInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
