import { ComponentProps, ElementType } from 'react'
import { FaAws, FaGithub } from 'react-icons/fa'
import {
  SiAwslambda,
  SiDocker,
  SiGooglecloud,
  SiHelm,
  SiKubernetes,
  SiOpencontainersinitiative,
  SiPulumi,
  SiTerraform,
} from 'react-icons/si'
import { VscAzure } from 'react-icons/vsc'
import {
  AppWindowIcon,
  ArchiveIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowLineRightIcon,
  ArrowRightIcon,
  ArrowsClockwiseIcon,
  ArrowsCounterClockwiseIcon,
  ArrowsOutIcon,
  ArrowSquareOutIcon,
  ArrowUpIcon,
  ArrowURightUpIcon,
  BellIcon,
  BookIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  BoxArrowDownIcon,
  BoxArrowUpIcon,
  BracketsCurlyIcon,
  BugIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  CardsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CaretUpDownIcon,
  ChartBarIcon,
  ChartLineIcon,
  ChatCircleIcon,
  CheckIcon,
  CheckCircleIcon,
  ClockIcon,
  ClockClockwiseIcon,
  ClockCounterClockwiseIcon,
  CloudIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CloudCheckIcon,
  CodeBlockIcon,
  CopyIcon,
  CornersOutIcon,
  CpuIcon,
  CreditCardIcon,
  CrownIcon,
  CubeIcon,
  DatabaseIcon,
  DotsSixVerticalIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  DownloadIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EraserIcon,
  EyeIcon,
  EyeSlashIcon,
  FadersIcon,
  FileArrowDownIcon,
  FileCloudIcon,
  FileCodeIcon,
  FileCsvIcon,
  FileDashedIcon,
  FileLockIcon,
  FileTextIcon,
  FileZipIcon,
  FlaskIcon,
  FloppyDiskIcon,
  FolderOpenIcon,
  FunnelIcon,
  FunnelSimpleIcon,
  GearIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitForkIcon,
  GithubLogoIcon,
  GlobeIcon,
  GraphIcon,
  GridFourIcon,
  HammerIcon,
  HardDriveIcon,
  HardDrivesIcon,
  HeartbeatIcon,
  HouseIcon,
  HouseSimpleIcon,
  InfoIcon,
  KeyIcon,
  LayoutIcon,
  LightningIcon,
  LinkIcon,
  LinkedinLogoIcon,
  ListIcon,
  ListBulletsIcon,
  ListChecksIcon,
  ListDashesIcon,
  LockIcon,
  LockKeyIcon,
  LockKeyOpenIcon,
  LockOpenIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  NetworkXIcon,
  PackageIcon,
  PaletteIcon,
  PencilIcon,
  PencilSimpleIcon,
  PencilSimpleLineIcon,
  PhoneIcon,
  PlayIcon,
  PlusIcon,
  PlusCircleIcon,
  PowerIcon,
  PulseIcon,
  QuestionIcon,
  RocketIcon,
  ScalesIcon,
  ScanIcon,
  ShareIcon,
  ShieldIcon,
  ShieldCheckIcon,
  ShippingContainerIcon,
  ShuffleIcon,
  SidebarSimpleIcon,
  SignOutIcon,
  SignpostIcon,
  SkipForwardIcon,
  SlackLogoIcon,
  SlidersIcon,
  SlidersHorizontalIcon,
  SneakerMoveIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SparkleIcon,
  SplitHorizontalIcon,
  SquareIcon,
  SquaresFourIcon,
  StackIcon,
  StackMinusIcon,
  StackSimpleIcon,
  StopIcon,
  StopCircleIcon,
  TableIcon,
  TagIcon,
  TerminalIcon,
  TerminalWindowIcon,
  TestTubeIcon,
  TextAaIcon,
  TimerIcon,
  TrashIcon,
  TreeStructureIcon,
  UploadIcon,
  UserIcon,
  UserCheckIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  UsersThreeIcon,
  WarningIcon,
  WarningCircleIcon,
  WarningOctagonIcon,
  WebhooksLogoIcon,
  XIcon,
  XCircleIcon,
  XLogoIcon,
  ArrowsInLineVerticalIcon,
  ArrowsOutLineVerticalIcon,
  BellSlashIcon,
  ClockCountdownIcon,
  CornersInIcon,
  MinusCircleIcon,
  ProhibitIcon,
  RepeatIcon,
  ToggleLeftIcon,
  ToggleRightIcon,
} from '@phosphor-icons/react'
import type { IconProps as PhosphorIconProps } from '@phosphor-icons/react'
import { Loading } from './Loading'
import { AWSColor, AzureColor, GCPColor } from './CloudPlatformColorIcons'
import type { TTheme } from '@/types'
import { cn } from '@/utils/classnames'

const customIcons = {
  AWS: FaAws,
  AWSColor,
  AWSLambda: SiAwslambda,
  Azure: VscAzure,
  AzureColor,
  Docker: SiDocker,
  GCP: SiGooglecloud,
  GCPColor,
  GitHub: FaGithub,
  Helm: SiHelm,
  Kubernetes: SiKubernetes,
  Loading: Loading,
  OCI: SiOpencontainersinitiative,
  Pulumi: SiPulumi,
  Terraform: SiTerraform,
} as const

const phosphorIcons = {
  AppWindowIcon,
  ArchiveIcon,
  ArrowClockwiseIcon,
  ArrowCounterClockwiseIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowLineRightIcon,
  ArrowRightIcon,
  ArrowsClockwiseIcon,
  ArrowsCounterClockwiseIcon,
  ArrowsOutIcon,
  ArrowSquareOutIcon,
  ArrowUpIcon,
  ArrowURightUpIcon,
  BellIcon,
  BookIcon,
  BookOpenIcon,
  BookOpenTextIcon,
  BoxArrowDownIcon,
  BoxArrowUpIcon,
  BracketsCurlyIcon,
  BugIcon,
  BuildingsIcon,
  CalendarBlankIcon,
  CardsIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretUpIcon,
  CaretUpDownIcon,
  ChartBarIcon,
  ChartLineIcon,
  ChatCircleIcon,
  CheckIcon,
  CheckCircleIcon,
  ClockIcon,
  ClockClockwiseIcon,
  ClockCounterClockwiseIcon,
  CloudIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CloudCheckIcon,
  CodeBlockIcon,
  CopyIcon,
  CornersOutIcon,
  CpuIcon,
  CreditCardIcon,
  CrownIcon,
  CubeIcon,
  DatabaseIcon,
  DotsSixVerticalIcon,
  DotsThreeIcon,
  DotsThreeVerticalIcon,
  DownloadIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  EraserIcon,
  EyeIcon,
  EyeSlashIcon,
  FadersIcon,
  FileArrowDownIcon,
  FileCloudIcon,
  FileCodeIcon,
  FileCsvIcon,
  FileDashedIcon,
  FileLockIcon,
  FileTextIcon,
  FileZipIcon,
  FlaskIcon,
  FloppyDiskIcon,
  FolderOpenIcon,
  FunnelIcon,
  FunnelSimpleIcon,
  GearIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitForkIcon,
  GithubLogoIcon,
  GlobeIcon,
  GraphIcon,
  GridFourIcon,
  HammerIcon,
  HardDriveIcon,
  HardDrivesIcon,
  HeartbeatIcon,
  HouseIcon,
  HouseSimpleIcon,
  InfoIcon,
  KeyIcon,
  LayoutIcon,
  LightningIcon,
  LinkIcon,
  LinkedinLogoIcon,
  ListIcon,
  ListBulletsIcon,
  ListChecksIcon,
  ListDashesIcon,
  LockIcon,
  LockKeyIcon,
  LockKeyOpenIcon,
  LockOpenIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  NetworkXIcon,
  PackageIcon,
  PaletteIcon,
  PencilIcon,
  PencilSimpleIcon,
  PencilSimpleLineIcon,
  PhoneIcon,
  PlayIcon,
  PlusIcon,
  PlusCircleIcon,
  PowerIcon,
  PulseIcon,
  QuestionIcon,
  RocketIcon,
  ScalesIcon,
  ScanIcon,
  ShareIcon,
  ShieldIcon,
  ShieldCheckIcon,
  ShippingContainerIcon,
  ShuffleIcon,
  SidebarSimpleIcon,
  SignOutIcon,
  SignpostIcon,
  SkipForwardIcon,
  SlackLogoIcon,
  SlidersIcon,
  SlidersHorizontalIcon,
  SneakerMoveIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SparkleIcon,
  SplitHorizontalIcon,
  SquareIcon,
  SquaresFourIcon,
  StackIcon,
  StackMinusIcon,
  StackSimpleIcon,
  StopIcon,
  StopCircleIcon,
  TableIcon,
  TagIcon,
  TerminalIcon,
  TerminalWindowIcon,
  TestTubeIcon,
  TextAaIcon,
  TimerIcon,
  TrashIcon,
  TreeStructureIcon,
  UploadIcon,
  UserIcon,
  UserCheckIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  UsersThreeIcon,
  WarningIcon,
  WarningCircleIcon,
  WarningOctagonIcon,
  WebhooksLogoIcon,
  XIcon,
  XCircleIcon,
  XLogoIcon,
  ArrowsInLineVerticalIcon,
  ArrowsOutLineVerticalIcon,
  BellSlashIcon,
  ClockCountdownIcon,
  CornersInIcon,
  MinusCircleIcon,
  ProhibitIcon,
  RepeatIcon,
  ToggleLeftIcon,
  ToggleRightIcon,
} as const

type CustomIconVariant = keyof typeof customIcons
type PhosphorIconVariant = keyof typeof phosphorIcons

export type TIconVariant = PhosphorIconVariant | CustomIconVariant

const THEME_CLASSES: Record<TTheme, string> = {
  default: '',
  neutral: 'text-cool-grey-600 dark:text-white/70',
  info: 'text-blue-800 dark:text-blue-600',
  warn: 'text-orange-800 dark:text-orange-600',
  error: 'text-red-800 dark:text-red-500',
  success: 'text-green-800 dark:text-green-500',
  brand: 'text-primary-600 dark:text-primary-500',
}

interface IconProps extends Omit<PhosphorIconProps, 'ref'> {
  variant: TIconVariant
  theme?: TTheme
}

export const Icon = ({
  variant,
  size = 16,
  weight = 'regular',
  theme = 'default',
  className,
  ...props
}: IconProps) => {
  const themeClass = cn(THEME_CLASSES[theme], className)

  if (variant in customIcons) {
    const CustomIcon = customIcons[variant as CustomIconVariant]
    return <CustomIcon size={size} className={themeClass} />
  }

  const IconComponent = phosphorIcons[variant as PhosphorIconVariant] as
    | ElementType
    | undefined

  if (!IconComponent) {
    if (process.env.NODE_ENV === 'development') {
      console.warn(
        `Icon variant "${variant}" not found. Add it to the phosphorIcons map in client/components/common/Icon.tsx:\n` +
          `  1. Add: import { ${variant} } from '@phosphor-icons/react'\n` +
          `  2. Add: ${variant} to the phosphorIcons object`,
      )
    }
    return null
  }

  return <IconComponent size={size} weight={weight} className={themeClass} {...props} />
}
