package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/nuonco/nuon/services/ctl-api/docs/admin"
	"github.com/nuonco/nuon/services/ctl-api/docs/public"
	"github.com/nuonco/nuon/services/ctl-api/docs/runner"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// SwaggerSpec represents the structure of a Swagger/OpenAPI 2.0 specification
type SwaggerSpec struct {
	Paths map[string]PathItem `json:"paths"`
}

// PathItem represents a path in the swagger spec
type PathItem struct {
	Get    *Operation `json:"get,omitempty"`
	Post   *Operation `json:"post,omitempty"`
	Put    *Operation `json:"put,omitempty"`
	Patch  *Operation `json:"patch,omitempty"`
	Delete *Operation `json:"delete,omitempty"`
}

// Operation represents an HTTP operation (GET, POST, etc.)
type Operation struct {
	OperationID string      `json:"operationId"`
	Summary     string      `json:"summary"`
	Parameters  []Parameter `json:"parameters,omitempty"`
}

// Parameter represents a parameter in an operation
type Parameter struct {
	Name        string `json:"name"`
	In          string `json:"in"`
	Type        string `json:"type"`
	Description string `json:"description"`
}

// TestSwaggerPaginationConsistency validates that all GET endpoints with 'page' parameter:
// 1. Also have 'offset' and 'limit' parameters for consistent pagination
// 2. Do NOT have 'x-nuon-pagination-enabled' parameter (which conflicts with standard pagination)
//
// IMPORTANT FOR CI: This test uses pre-generated swagger specs from docs/*/docs.go files.
// These are generated by `go generate` and must be up-to-date. To ensure specs are fresh:
//
//	In CI: Run `go generate` before running tests
//	Example: go generate && go test -v ./...
//
// This design choice ensures:
// - Fast test execution (~10ms vs 2+ minutes for real-time parsing)
// - Reliable CI without timeouts
// - Tests catch annotation errors as long as go generate is run first
func TestSwaggerPaginationConsistency(t *testing.T) {
	// Define the swagger specs to test - using pre-generated in-memory specs
	specs := []struct {
		name     string
		specJSON string
	}{
		{
			name:     "public",
			specJSON: public.SwaggerInfo.ReadDoc(),
		},
		{
			name:     "admin",
			specJSON: admin.SwaggerInfoadmin.ReadDoc(),
		},
		{
			name:     "runner",
			specJSON: runner.SwaggerInforunner.ReadDoc(),
		},
	}

	for _, spec := range specs {
		t.Run(spec.name, func(t *testing.T) {
			// Parse the swagger spec
			swaggerSpec := parseSwaggerSpec(t, spec.specJSON, spec.name)

			// Track violations for clear error reporting
			var violations []string

			// Iterate through all paths
			for path, pathItem := range swaggerSpec.Paths {
				// Only check GET endpoints
				if pathItem.Get != nil {
					violation := checkPaginationParams(path, pathItem.Get)
					if violation != "" {
						violations = append(violations, violation)
					}
				}
			}

			// Assert no violations found
			if len(violations) > 0 {
				errorMsg := fmt.Sprintf("Found %d pagination consistency violation(s) in %s spec:\n", len(violations), spec.name)
				for _, v := range violations {
					errorMsg += fmt.Sprintf("  - %s\n", v)
				}
				assert.Fail(t, errorMsg)
			}
		})
	}
}

// checkPaginationParams checks if a GET operation has consistent pagination parameters
// Returns an error message if validation fails, empty string if valid
func checkPaginationParams(path string, operation *Operation) string {
	paramMap := make(map[string]bool)
	allParamMap := make(map[string]bool)

	// Build a map of query parameter names and all parameter names
	for _, param := range operation.Parameters {
		allParamMap[param.Name] = true
		if param.In == "query" {
			paramMap[param.Name] = true
		}
	}

	// If 'page' parameter exists, ensure 'offset' and 'limit' also exist
	if paramMap["page"] {
		missingParams := []string{}

		if !paramMap["offset"] {
			missingParams = append(missingParams, "offset")
		}
		if !paramMap["limit"] {
			missingParams = append(missingParams, "limit")
		}

		if len(missingParams) > 0 {
			return fmt.Sprintf("GET %s (operation: %s) has 'page' parameter but missing: %v",
				path, operation.OperationID, missingParams)
		}

		// Ensure x-nuon-pagination-enabled is NOT present when using standard pagination
		if allParamMap["x-nuon-pagination-enabled"] {
			return fmt.Sprintf("GET %s (operation: %s) uses standard pagination (page/offset/limit) but also has 'x-nuon-pagination-enabled' parameter, which should not be used together",
				path, operation.OperationID)
		}
	}

	return ""
}

// parseSwaggerSpec parses a swagger JSON string into a SwaggerSpec struct
func parseSwaggerSpec(t *testing.T, specJSON string, specName string) *SwaggerSpec {
	// Parse the JSON
	var spec SwaggerSpec
	err := json.Unmarshal([]byte(specJSON), &spec)
	require.NoError(t, err, "Failed to parse swagger spec JSON for %s", specName)

	return &spec
}

// TestSwaggerSpecsExist validates that all required swagger spec files exist
func TestSwaggerSpecsExist(t *testing.T) {
	specs := []string{
		"docs/public/swagger.json",
		"docs/public/docs.go",
		"docs/admin/admin_swagger.json",
		"docs/admin/admin_docs.go",
		"docs/runner/runner_swagger.json",
		"docs/runner/runner_docs.go",
	}

	for _, spec := range specs {
		t.Run(spec, func(t *testing.T) {
			absPath, err := filepath.Abs(spec)
			require.NoError(t, err)

			info, err := os.Stat(absPath)
			require.NoError(t, err, "Swagger spec file does not exist: %s. Run 'go generate' to create it.", absPath)
			require.False(t, info.IsDir(), "Expected file but found directory: %s", absPath)
		})
	}
}
