// Package allsignals imports all signal packages to trigger their init() registrations
// into the signal catalog. Import this package in any binary that needs the full catalog.
package allsignals

import (
	// apps signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/branches/appconfig"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/branches/builds"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/branches/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/branches/deploygrouptoqueue"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/branches/fetchcommit"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/branches/run"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/branches/sandboxbuild"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/deprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/polldependencies"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/provision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/reprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/sandboxbuild"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/v2/updatesandbox"

	// general signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/general/signals/v2/promotion"

	// components signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/build"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/configcreated"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/delete"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/inlinebuild"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/polldependencies"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/provision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/queuebuild"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/restart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/v2/updatecomponenttype"

	// installs signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/actionworkflowrun"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/appconfigupdated"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/awaitinstallstackversionrun"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/awaitrunnerhealthy"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/componentdeployapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/componentdeployplanonly"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/componentdeploysyncandplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/componentsyncimage"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/componentteardownapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/componentteardownsyncandplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/deprovisiondns"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/deprovisionsandboxapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/deprovisionsandboxplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/driftcheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/driftchecksandbox"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/driftdetected"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/executeactionworkflow"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/forgotten"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/generateinstallstackversion"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/generatestate"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/generateworkflowsteps"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/polldependencies"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/provisiondns"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/provisionrunner"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/provisionsandboxapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/provisionsandboxplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/reprovisionrunner"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/reprovisionsandboxapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/reprovisionsandboxplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/restart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/restartchildren"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/syncsecrets"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/updated"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/updateinstallstackoutputs"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/workflowapproveall"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/workflowstepapprovalrequest"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/v2/workflowstepapprovalresponse"

	// onboarding signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/onboarding/signals/create_app"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/onboarding/signals/create_install"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/onboarding/signals/create_org"

	// orgs signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/delete"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/deprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/enable_feature_flags"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/force_restart_queues"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/force_sandbox_mode"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/invite_accepted"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/invite_created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/provision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/queue_migration"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/reprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/restart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/restart_queues"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/v2/restart_runners"

	// runners signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/delete"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/deprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/flushorphanedjobs"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/forcedelete"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/forceshutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/gracefulshutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/healthcheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/installstackversionrun"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/mngrestart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/mngshutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/mngshutdownvm"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/mngupdate"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/offlinecheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/oninactive"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/processhealthcheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/processinit"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/processjob"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/processshutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/provision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/provisionserviceaccount"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/reprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/reprovisionserviceaccount"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/restart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/triggershutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/updatetag"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/v2/updateversion"

	// vcs signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/vcs/signals/v2/healthcheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/vcs/signals/v2/webhook_subscription"

	// flow signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/pkg/flow/signals/executeflow"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/pkg/flow/signals/executeworkflowstep"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/pkg/flow/signals/executeworkflowstepgroup"
)
