// Package allsignals imports all signal packages to trigger their init() registrations
// into the signal catalog. Import this package in any binary that needs the full catalog.
package allsignals

import (
	// apps signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/branches/appconfig"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/branches/builds"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/branches/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/branches/deploygrouptoqueue"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/branches/fetchcommit"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/branches/run"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/branches/sandboxbuild"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/customstacks"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/deprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/polldependencies"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/provision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/reprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/sandboxbuild"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/apps/signals/updatesandbox"

	// general signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/general/signals/promotion"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/general/signals/slack_auto_link"

	// components signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/build"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/configcreated"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/delete"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/inlinebuild"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/polldependencies"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/provision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/queuebuild"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/restart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/components/signals/updatecomponenttype"

	// installs signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/actionworkflowrun"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/appconfigupdated"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/awaitinstallstackversionrun"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/awaitrunnerhealthy"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/componentdeployapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/componentdeployplanonly"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/componentdeploysyncandplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/componentsyncimage"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/componentteardownapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/componentteardownsyncandplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/deprovisiondns"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/deprovisionsandboxapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/deprovisionsandboxplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/driftcheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/driftchecksandbox"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/driftdetected"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/executeactionworkflow"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/forgotten"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/generateinstallstackversion"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/generatestate"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/generateworkflowsteps"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/polldependencies"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/provisiondns"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/provisionrunner"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/provisionsandboxapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/provisionsandboxplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/reprovisionrunner"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/reprovisionsandboxapplyplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/reprovisionsandboxplan"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/restart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/restartchildren"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/syncsecrets"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/updated"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/updateinstallstackoutputs"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/workflowapproveall"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/workflowstepapprovalrequest"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/installs/signals/workflowstepapprovalresponse"

	// onboarding signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/onboarding/signals/create_app"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/onboarding/signals/create_install"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/onboarding/signals/create_org"

	// orgs signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/clear_org_queues"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/delete"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/deprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/enable_feature_flags"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/force_restart_queues"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/force_sandbox_mode"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/invite_accepted"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/invite_created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/provision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/queue_migration"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/remove_old_runner_processes"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/reprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/restart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/restart_queues"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/restart_runners"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/orgs/signals/terminate_workflows"

	// runners signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/created"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/delete"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/deprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/flushorphanedjobs"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/forcedelete"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/forceshutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/gracefulshutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/installstackversionrun"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/mngrestart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/mngshutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/mngshutdownvm"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/mngupdate"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/offlinecheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/oninactive"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/processhealthcheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/processinit"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/processjob"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/processshutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/provision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/provisionserviceaccount"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/reprovision"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/reprovisionserviceaccount"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/restart"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/triggershutdown"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/updatetag"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/runners/signals/updateversion"

	// vcs signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/vcs/signals/healthcheck"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/app/vcs/signals/webhook_subscription"

	// flow signals
	_ "github.com/nuonco/nuon/services/ctl-api/internal/pkg/flow/signals/executeflow"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/pkg/flow/signals/executeworkflowstep"
	_ "github.com/nuonco/nuon/services/ctl-api/internal/pkg/flow/signals/executeworkflowstepgroup"
)
