// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppOnboarding app onboarding
//
// swagger:model app.Onboarding
type AppOnboarding struct {

	// account id
	AccountID string `json:"account_id,omitempty"`

	// app attributes
	AppAttributes []string `json:"app_attributes"`

	// app branch id
	AppBranchID string `json:"app_branch_id,omitempty"`

	// app id
	AppID string `json:"app_id,omitempty"`

	// Step 2: Your Stack
	AppType string `json:"app_type,omitempty"`

	// cloud provider
	CloudProvider string `json:"cloud_provider,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// current step
	CurrentStep string `json:"current_step,omitempty"`

	// example app slug
	ExampleAppSlug string `json:"example_app_slug,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// install id
	InstallID string `json:"install_id,omitempty"`

	// Step 3: Install
	InstallMode string `json:"install_mode,omitempty"`

	// Step 1: Organization
	OrgID string `json:"org_id,omitempty"`

	// status
	Status string `json:"status,omitempty"`

	// step error
	StepError string `json:"step_error,omitempty"`

	// Async step status (for queue-based signal processing)
	StepStatus string `json:"step_status,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// workflow id
	WorkflowID string `json:"workflow_id,omitempty"`
}

// Validate validates this app onboarding
func (m *AppOnboarding) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app onboarding based on context it is used
func (m *AppOnboarding) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppOnboarding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppOnboarding) UnmarshalBinary(b []byte) error {
	var res AppOnboarding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
