// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AppInstallStateGenerateSource app install state generate source
//
// swagger:model app.InstallStateGenerateSource
type AppInstallStateGenerateSource string

func NewAppInstallStateGenerateSource(value AppInstallStateGenerateSource) *AppInstallStateGenerateSource {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AppInstallStateGenerateSource.
func (m AppInstallStateGenerateSource) Pointer() *AppInstallStateGenerateSource {
	return &m
}

const (

	// AppInstallStateGenerateSourceLegacy captures enum value "legacy"
	AppInstallStateGenerateSourceLegacy AppInstallStateGenerateSource = "legacy"

	// AppInstallStateGenerateSourceStateDashManager captures enum value "state-manager"
	AppInstallStateGenerateSourceStateDashManager AppInstallStateGenerateSource = "state-manager"
)

// for schema
var appInstallStateGenerateSourceEnum []any

func init() {
	var res []AppInstallStateGenerateSource
	if err := json.Unmarshal([]byte(`["legacy","state-manager"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appInstallStateGenerateSourceEnum = append(appInstallStateGenerateSourceEnum, v)
	}
}

func (m AppInstallStateGenerateSource) validateAppInstallStateGenerateSourceEnum(path, location string, value AppInstallStateGenerateSource) error {
	if err := validate.EnumCase(path, location, value, appInstallStateGenerateSourceEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this app install state generate source
func (m AppInstallStateGenerateSource) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAppInstallStateGenerateSourceEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this app install state generate source based on context it is used
func (m AppInstallStateGenerateSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
