// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppInstallGroupRun app install group run
//
// swagger:model app.InstallGroupRun
type AppInstallGroupRun struct {

	// app branch run id
	AppBranchRunID string `json:"app_branch_run_id,omitempty"`

	// completed at
	CompletedAt string `json:"completed_at,omitempty"`

	// completed installs
	CompletedInstalls int64 `json:"completed_installs,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// failed installs
	FailedInstalls int64 `json:"failed_installs,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// install group
	InstallGroup *AppAppBranchInstallGroup `json:"install_group,omitempty"`

	// install group id
	InstallGroupID string `json:"install_group_id,omitempty"`

	// install group name
	InstallGroupName string `json:"install_group_name,omitempty"`

	// installs
	Installs []*AppInstallGroupRunInstall `json:"installs"`

	// org id
	OrgID string `json:"org_id,omitempty"`

	// started at
	StartedAt string `json:"started_at,omitempty"`

	// status
	Status *AppCompositeStatus `json:"status,omitempty"`

	// total installs
	TotalInstalls int64 `json:"total_installs,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this app install group run
func (m *AppInstallGroupRun) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInstallGroup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstalls(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInstallGroupRun) validateInstallGroup(formats strfmt.Registry) error {
	if swag.IsZero(m.InstallGroup) { // not required
		return nil
	}

	if m.InstallGroup != nil {
		if err := m.InstallGroup.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("install_group")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("install_group")
			}

			return err
		}
	}

	return nil
}

func (m *AppInstallGroupRun) validateInstalls(formats strfmt.Registry) error {
	if swag.IsZero(m.Installs) { // not required
		return nil
	}

	for i := 0; i < len(m.Installs); i++ {
		if swag.IsZero(m.Installs[i]) { // not required
			continue
		}

		if m.Installs[i] != nil {
			if err := m.Installs[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("installs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("installs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *AppInstallGroupRun) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("status")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("status")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this app install group run based on the context it is used
func (m *AppInstallGroupRun) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInstallGroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstalls(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppInstallGroupRun) contextValidateInstallGroup(ctx context.Context, formats strfmt.Registry) error {

	if m.InstallGroup != nil {

		if swag.IsZero(m.InstallGroup) { // not required
			return nil
		}

		if err := m.InstallGroup.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("install_group")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("install_group")
			}

			return err
		}
	}

	return nil
}

func (m *AppInstallGroupRun) contextValidateInstalls(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Installs); i++ {

		if m.Installs[i] != nil {

			if swag.IsZero(m.Installs[i]) { // not required
				return nil
			}

			if err := m.Installs[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("installs" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("installs" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *AppInstallGroupRun) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {

		if swag.IsZero(m.Status) { // not required
			return nil
		}

		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("status")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("status")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppInstallGroupRun) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppInstallGroupRun) UnmarshalBinary(b []byte) error {
	var res AppInstallGroupRun
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
