// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AppOnboardingAppType app onboarding app type
//
// swagger:model app.OnboardingAppType
type AppOnboardingAppType string

func NewAppOnboardingAppType(value AppOnboardingAppType) *AppOnboardingAppType {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AppOnboardingAppType.
func (m AppOnboardingAppType) Pointer() *AppOnboardingAppType {
	return &m
}

const (

	// AppOnboardingAppTypeCustom captures enum value "custom"
	AppOnboardingAppTypeCustom AppOnboardingAppType = "custom"

	// AppOnboardingAppTypeExample captures enum value "example"
	AppOnboardingAppTypeExample AppOnboardingAppType = "example"
)

// for schema
var appOnboardingAppTypeEnum []any

func init() {
	var res []AppOnboardingAppType
	if err := json.Unmarshal([]byte(`["custom","example"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appOnboardingAppTypeEnum = append(appOnboardingAppTypeEnum, v)
	}
}

func (m AppOnboardingAppType) validateAppOnboardingAppTypeEnum(path, location string, value AppOnboardingAppType) error {
	if err := validate.EnumCase(path, location, value, appOnboardingAppTypeEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this app onboarding app type
func (m AppOnboardingAppType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAppOnboardingAppTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this app onboarding app type based on context it is used
func (m AppOnboardingAppType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
