// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppAppBranchInstallGroup app app branch install group
//
// swagger:model app.AppBranchInstallGroup
type AppAppBranchInstallGroup struct {

	// app branch config id
	AppBranchConfigID string `json:"app_branch_config_id,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// install ids
	InstallIds []string `json:"install_ids"`

	// max parallel
	MaxParallel int64 `json:"max_parallel,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// order
	Order int64 `json:"order,omitempty"`

	// org id
	OrgID string `json:"org_id,omitempty"`

	// requires approval
	RequiresApproval bool `json:"requires_approval,omitempty"`

	// rollback on failure
	RollbackOnFailure bool `json:"rollback_on_failure,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this app app branch install group
func (m *AppAppBranchInstallGroup) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app app branch install group based on context it is used
func (m *AppAppBranchInstallGroup) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppAppBranchInstallGroup) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppAppBranchInstallGroup) UnmarshalBinary(b []byte) error {
	var res AppAppBranchInstallGroup
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
