// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AppInstallActionWorkflowRunStatus app install action workflow run status
//
// swagger:model app.InstallActionWorkflowRunStatus
type AppInstallActionWorkflowRunStatus string

func NewAppInstallActionWorkflowRunStatus(value AppInstallActionWorkflowRunStatus) *AppInstallActionWorkflowRunStatus {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AppInstallActionWorkflowRunStatus.
func (m AppInstallActionWorkflowRunStatus) Pointer() *AppInstallActionWorkflowRunStatus {
	return &m
}

const (

	// AppInstallActionWorkflowRunStatusFinished captures enum value "finished"
	AppInstallActionWorkflowRunStatusFinished AppInstallActionWorkflowRunStatus = "finished"

	// AppInstallActionWorkflowRunStatusQueued captures enum value "queued"
	AppInstallActionWorkflowRunStatusQueued AppInstallActionWorkflowRunStatus = "queued"

	// AppInstallActionWorkflowRunStatusInDashProgress captures enum value "in-progress"
	AppInstallActionWorkflowRunStatusInDashProgress AppInstallActionWorkflowRunStatus = "in-progress"

	// AppInstallActionWorkflowRunStatusError captures enum value "error"
	AppInstallActionWorkflowRunStatusError AppInstallActionWorkflowRunStatus = "error"

	// AppInstallActionWorkflowRunStatusTimedDashOut captures enum value "timed-out"
	AppInstallActionWorkflowRunStatusTimedDashOut AppInstallActionWorkflowRunStatus = "timed-out"

	// AppInstallActionWorkflowRunStatusCancelled captures enum value "cancelled"
	AppInstallActionWorkflowRunStatusCancelled AppInstallActionWorkflowRunStatus = "cancelled"

	// AppInstallActionWorkflowRunStatusUnknown captures enum value "unknown"
	AppInstallActionWorkflowRunStatusUnknown AppInstallActionWorkflowRunStatus = "unknown"

	// AppInstallActionWorkflowRunStatusRetried captures enum value "retried"
	AppInstallActionWorkflowRunStatusRetried AppInstallActionWorkflowRunStatus = "retried"
)

// for schema
var appInstallActionWorkflowRunStatusEnum []any

func init() {
	var res []AppInstallActionWorkflowRunStatus
	if err := json.Unmarshal([]byte(`["finished","queued","in-progress","error","timed-out","cancelled","unknown","retried"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appInstallActionWorkflowRunStatusEnum = append(appInstallActionWorkflowRunStatusEnum, v)
	}
}

func (m AppInstallActionWorkflowRunStatus) validateAppInstallActionWorkflowRunStatusEnum(path, location string, value AppInstallActionWorkflowRunStatus) error {
	if err := validate.EnumCase(path, location, value, appInstallActionWorkflowRunStatusEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this app install action workflow run status
func (m AppInstallActionWorkflowRunStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAppInstallActionWorkflowRunStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this app install action workflow run status based on context it is used
func (m AppInstallActionWorkflowRunStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
