// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppSlackChannelSubscription app slack channel subscription
//
// swagger:model app.SlackChannelSubscription
type AppSlackChannelSubscription struct {

	// channel id
	ChannelID string `json:"channel_id,omitempty"`

	// channel name
	ChannelName string `json:"channel_name,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by account id
	CreatedByAccountID string `json:"created_by_account_id,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// created by slack user id
	CreatedBySlackUserID string `json:"created_by_slack_user_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// Interests is the per-subscription event filter. Stored as JSONB; one
	// shape is shared with webhooks (see internal/pkg/interests). New rows
	// default to AllEvents=true via the create handler when the request omits
	// the field.
	Interests any `json:"interests,omitempty"`

	// Match is the per-subscription routing predicate. Nil = match every
	// event in the org. Non-nil = evaluated by labels.SubscriptionMatch
	// against the dispatch-time labels.EventTargets. swaggertype:"object"
	// keeps the SDK from materialising the full nested type tree.
	Match any `json:"match,omitempty"`

	// OrgID is denormalized from OrgLink for query convenience.
	OrgID string `json:"org_id,omitempty"`

	// org link id
	OrgLinkID string `json:"org_link_id,omitempty"`

	// team id
	TeamID string `json:"team_id,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this app slack channel subscription
func (m *AppSlackChannelSubscription) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app slack channel subscription based on context it is used
func (m *AppSlackChannelSubscription) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppSlackChannelSubscription) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppSlackChannelSubscription) UnmarshalBinary(b []byte) error {
	var res AppSlackChannelSubscription
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
