// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// AppPolicyReportFormat app policy report format
//
// swagger:model app.PolicyReportFormat
type AppPolicyReportFormat string

func NewAppPolicyReportFormat(value AppPolicyReportFormat) *AppPolicyReportFormat {
	return &value
}

// Pointer returns a pointer to a freshly-allocated AppPolicyReportFormat.
func (m AppPolicyReportFormat) Pointer() *AppPolicyReportFormat {
	return &m
}

const (

	// AppPolicyReportFormatOpa captures enum value "opa"
	AppPolicyReportFormatOpa AppPolicyReportFormat = "opa"

	// AppPolicyReportFormatSarif captures enum value "sarif"
	AppPolicyReportFormatSarif AppPolicyReportFormat = "sarif"
)

// for schema
var appPolicyReportFormatEnum []any

func init() {
	var res []AppPolicyReportFormat
	if err := json.Unmarshal([]byte(`["opa","sarif"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appPolicyReportFormatEnum = append(appPolicyReportFormatEnum, v)
	}
}

func (m AppPolicyReportFormat) validateAppPolicyReportFormatEnum(path, location string, value AppPolicyReportFormat) error {
	if err := validate.EnumCase(path, location, value, appPolicyReportFormatEnum, true); err != nil {
		return err
	}
	return nil
}

// Validate validates this app policy report format
func (m AppPolicyReportFormat) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAppPolicyReportFormatEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this app policy report format based on context it is used
func (m AppPolicyReportFormat) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
