// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppRunnerJobPermissionInfo app runner job permission info
//
// swagger:model app.RunnerJobPermissionInfo
type AppRunnerJobPermissionInfo struct {

	// role
	Role string `json:"role,omitempty"`

	// role selection trace
	RoleSelectionTrace []*AppRunnerJobPermissionTraceRecord `json:"role_selection_trace"`

	// role source
	RoleSource string `json:"role_source,omitempty"`
}

// Validate validates this app runner job permission info
func (m *AppRunnerJobPermissionInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRoleSelectionTrace(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppRunnerJobPermissionInfo) validateRoleSelectionTrace(formats strfmt.Registry) error {
	if swag.IsZero(m.RoleSelectionTrace) { // not required
		return nil
	}

	for i := 0; i < len(m.RoleSelectionTrace); i++ {
		if swag.IsZero(m.RoleSelectionTrace[i]) { // not required
			continue
		}

		if m.RoleSelectionTrace[i] != nil {
			if err := m.RoleSelectionTrace[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("role_selection_trace" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("role_selection_trace" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this app runner job permission info based on the context it is used
func (m *AppRunnerJobPermissionInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRoleSelectionTrace(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppRunnerJobPermissionInfo) contextValidateRoleSelectionTrace(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RoleSelectionTrace); i++ {

		if m.RoleSelectionTrace[i] != nil {

			if swag.IsZero(m.RoleSelectionTrace[i]) { // not required
				return nil
			}

			if err := m.RoleSelectionTrace[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("role_selection_trace" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("role_selection_trace" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppRunnerJobPermissionInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppRunnerJobPermissionInfo) UnmarshalBinary(b []byte) error {
	var res AppRunnerJobPermissionInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
