// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceCreateInstallAppConfigUpdateRequest service create install app config update request
//
// swagger:model service.CreateInstallAppConfigUpdateRequest
type ServiceCreateInstallAppConfigUpdateRequest struct {

	// app config id
	// Required: true
	AppConfigID *string `json:"app_config_id"`

	// plan only
	PlanOnly bool `json:"plan_only,omitempty"`
}

// Validate validates this service create install app config update request
func (m *ServiceCreateInstallAppConfigUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAppConfigID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceCreateInstallAppConfigUpdateRequest) validateAppConfigID(formats strfmt.Registry) error {

	if err := validate.Required("app_config_id", "body", m.AppConfigID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this service create install app config update request based on context it is used
func (m *ServiceCreateInstallAppConfigUpdateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceCreateInstallAppConfigUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceCreateInstallAppConfigUpdateRequest) UnmarshalBinary(b []byte) error {
	var res ServiceCreateInstallAppConfigUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
