// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceInstallAppPermissionsConfigResponse service install app permissions config response
//
// swagger:model service.InstallAppPermissionsConfigResponse
type ServiceInstallAppPermissionsConfigResponse struct {

	// break glass roles
	BreakGlassRoles []*ServiceInstallPermissionsRoleStatus `json:"break_glass_roles"`

	// custom roles
	CustomRoles []*ServiceInstallPermissionsRoleStatus `json:"custom_roles"`

	// deprovision role
	DeprovisionRole *ServiceInstallPermissionsRoleStatus `json:"deprovision_role,omitempty"`

	// maintenance role
	MaintenanceRole *ServiceInstallPermissionsRoleStatus `json:"maintenance_role,omitempty"`

	// provision role
	ProvisionRole *ServiceInstallPermissionsRoleStatus `json:"provision_role,omitempty"`
}

// Validate validates this service install app permissions config response
func (m *ServiceInstallAppPermissionsConfigResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBreakGlassRoles(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCustomRoles(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeprovisionRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaintenanceRole(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProvisionRole(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) validateBreakGlassRoles(formats strfmt.Registry) error {
	if swag.IsZero(m.BreakGlassRoles) { // not required
		return nil
	}

	for i := 0; i < len(m.BreakGlassRoles); i++ {
		if swag.IsZero(m.BreakGlassRoles[i]) { // not required
			continue
		}

		if m.BreakGlassRoles[i] != nil {
			if err := m.BreakGlassRoles[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("break_glass_roles" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("break_glass_roles" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) validateCustomRoles(formats strfmt.Registry) error {
	if swag.IsZero(m.CustomRoles) { // not required
		return nil
	}

	for i := 0; i < len(m.CustomRoles); i++ {
		if swag.IsZero(m.CustomRoles[i]) { // not required
			continue
		}

		if m.CustomRoles[i] != nil {
			if err := m.CustomRoles[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("custom_roles" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("custom_roles" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) validateDeprovisionRole(formats strfmt.Registry) error {
	if swag.IsZero(m.DeprovisionRole) { // not required
		return nil
	}

	if m.DeprovisionRole != nil {
		if err := m.DeprovisionRole.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deprovision_role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deprovision_role")
			}

			return err
		}
	}

	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) validateMaintenanceRole(formats strfmt.Registry) error {
	if swag.IsZero(m.MaintenanceRole) { // not required
		return nil
	}

	if m.MaintenanceRole != nil {
		if err := m.MaintenanceRole.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("maintenance_role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("maintenance_role")
			}

			return err
		}
	}

	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) validateProvisionRole(formats strfmt.Registry) error {
	if swag.IsZero(m.ProvisionRole) { // not required
		return nil
	}

	if m.ProvisionRole != nil {
		if err := m.ProvisionRole.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("provision_role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("provision_role")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this service install app permissions config response based on the context it is used
func (m *ServiceInstallAppPermissionsConfigResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBreakGlassRoles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCustomRoles(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDeprovisionRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMaintenanceRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProvisionRole(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) contextValidateBreakGlassRoles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.BreakGlassRoles); i++ {

		if m.BreakGlassRoles[i] != nil {

			if swag.IsZero(m.BreakGlassRoles[i]) { // not required
				return nil
			}

			if err := m.BreakGlassRoles[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("break_glass_roles" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("break_glass_roles" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) contextValidateCustomRoles(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CustomRoles); i++ {

		if m.CustomRoles[i] != nil {

			if swag.IsZero(m.CustomRoles[i]) { // not required
				return nil
			}

			if err := m.CustomRoles[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("custom_roles" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("custom_roles" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) contextValidateDeprovisionRole(ctx context.Context, formats strfmt.Registry) error {

	if m.DeprovisionRole != nil {

		if swag.IsZero(m.DeprovisionRole) { // not required
			return nil
		}

		if err := m.DeprovisionRole.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deprovision_role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deprovision_role")
			}

			return err
		}
	}

	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) contextValidateMaintenanceRole(ctx context.Context, formats strfmt.Registry) error {

	if m.MaintenanceRole != nil {

		if swag.IsZero(m.MaintenanceRole) { // not required
			return nil
		}

		if err := m.MaintenanceRole.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("maintenance_role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("maintenance_role")
			}

			return err
		}
	}

	return nil
}

func (m *ServiceInstallAppPermissionsConfigResponse) contextValidateProvisionRole(ctx context.Context, formats strfmt.Registry) error {

	if m.ProvisionRole != nil {

		if swag.IsZero(m.ProvisionRole) { // not required
			return nil
		}

		if err := m.ProvisionRole.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("provision_role")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("provision_role")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceInstallAppPermissionsConfigResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceInstallAppPermissionsConfigResponse) UnmarshalBinary(b []byte) error {
	var res ServiceInstallAppPermissionsConfigResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
