// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceTriggerAppBranchRunRequest service trigger app branch run request
//
// swagger:model service.TriggerAppBranchRunRequest
type ServiceTriggerAppBranchRunRequest struct {

	// optional - use pre-existing app config (skips VCS fetch + config parse)
	AppConfigID string `json:"app_config_id,omitempty"`

	// optional - use latest if not provided
	ConfigID string `json:"config_id,omitempty"`

	// force run even if no changes detected
	Force bool `json:"force,omitempty"`

	// plan-only preview mode (no apply)
	PlanOnly bool `json:"plan_only,omitempty"`

	// skip builds step (e.g. rollback to existing config with existing builds)
	SkipBuilds bool `json:"skip_builds,omitempty"`
}

// Validate validates this service trigger app branch run request
func (m *ServiceTriggerAppBranchRunRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service trigger app branch run request based on context it is used
func (m *ServiceTriggerAppBranchRunRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceTriggerAppBranchRunRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceTriggerAppBranchRunRequest) UnmarshalBinary(b []byte) error {
	var res ServiceTriggerAppBranchRunRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
