// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceAzureACRImageConfigRequest service azure a c r image config request
//
// swagger:model service.azureACRImageConfigRequest
type ServiceAzureACRImageConfigRequest struct {

	// client id
	ClientID string `json:"client_id,omitempty"`

	// registry url
	RegistryURL string `json:"registry_url,omitempty"`

	// tenant id
	TenantID string `json:"tenant_id,omitempty"`
}

// Validate validates this service azure a c r image config request
func (m *ServiceAzureACRImageConfigRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service azure a c r image config request based on context it is used
func (m *ServiceAzureACRImageConfigRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceAzureACRImageConfigRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceAzureACRImageConfigRequest) UnmarshalBinary(b []byte) error {
	var res ServiceAzureACRImageConfigRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
