// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceInstallPermissionsRoleStatus service install permissions role status
//
// swagger:model service.InstallPermissionsRoleStatus
type ServiceInstallPermissionsRoleStatus struct {

	// app config id
	AppConfigID string `json:"app_config_id,omitempty"`

	// arn
	Arn string `json:"arn,omitempty"`

	// cloud platform
	CloudPlatform string `json:"cloud_platform,omitempty"`

	// cloudformation param name
	CloudformationParamName string `json:"cloudformation_param_name,omitempty"`

	// cloudformation stack name
	CloudformationStackName string `json:"cloudformation_stack_name,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// display name
	DisplayName string `json:"display_name,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// enabled in stack
	EnabledInStack *SQLNullBool `json:"enabled_in_stack,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// org id
	OrgID string `json:"org_id,omitempty"`

	// owner id
	OwnerID string `json:"owner_id,omitempty"`

	// owner type
	OwnerType string `json:"owner_type,omitempty"`

	// permissions boundary
	PermissionsBoundary string `json:"permissions_boundary,omitempty"`

	// policies
	Policies []*AppAppAWSIAMPolicyConfig `json:"policies"`

	// type
	Type AppAWSIAMRoleType `json:"type,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this service install permissions role status
func (m *ServiceInstallPermissionsRoleStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnabledInStack(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePolicies(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceInstallPermissionsRoleStatus) validateEnabledInStack(formats strfmt.Registry) error {
	if swag.IsZero(m.EnabledInStack) { // not required
		return nil
	}

	if m.EnabledInStack != nil {
		if err := m.EnabledInStack.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("enabled_in_stack")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("enabled_in_stack")
			}

			return err
		}
	}

	return nil
}

func (m *ServiceInstallPermissionsRoleStatus) validatePolicies(formats strfmt.Registry) error {
	if swag.IsZero(m.Policies) { // not required
		return nil
	}

	for i := 0; i < len(m.Policies); i++ {
		if swag.IsZero(m.Policies[i]) { // not required
			continue
		}

		if m.Policies[i] != nil {
			if err := m.Policies[i].Validate(formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("policies" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("policies" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ServiceInstallPermissionsRoleStatus) validateType(formats strfmt.Registry) error {
	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := m.Type.Validate(formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("type")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("type")
		}

		return err
	}

	return nil
}

// ContextValidate validate this service install permissions role status based on the context it is used
func (m *ServiceInstallPermissionsRoleStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEnabledInStack(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePolicies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceInstallPermissionsRoleStatus) contextValidateEnabledInStack(ctx context.Context, formats strfmt.Registry) error {

	if m.EnabledInStack != nil {

		if swag.IsZero(m.EnabledInStack) { // not required
			return nil
		}

		if err := m.EnabledInStack.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("enabled_in_stack")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("enabled_in_stack")
			}

			return err
		}
	}

	return nil
}

func (m *ServiceInstallPermissionsRoleStatus) contextValidatePolicies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Policies); i++ {

		if m.Policies[i] != nil {

			if swag.IsZero(m.Policies[i]) { // not required
				return nil
			}

			if err := m.Policies[i].ContextValidate(ctx, formats); err != nil {
				ve := new(errors.Validation)
				if stderrors.As(err, &ve) {
					return ve.ValidateName("policies" + "." + strconv.Itoa(i))
				}
				ce := new(errors.CompositeError)
				if stderrors.As(err, &ce) {
					return ce.ValidateName("policies" + "." + strconv.Itoa(i))
				}

				return err
			}
		}

	}

	return nil
}

func (m *ServiceInstallPermissionsRoleStatus) contextValidateType(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.Type) { // not required
		return nil
	}

	if err := m.Type.ContextValidate(ctx, formats); err != nil {
		ve := new(errors.Validation)
		if stderrors.As(err, &ve) {
			return ve.ValidateName("type")
		}
		ce := new(errors.CompositeError)
		if stderrors.As(err, &ce) {
			return ce.ValidateName("type")
		}

		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceInstallPermissionsRoleStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceInstallPermissionsRoleStatus) UnmarshalBinary(b []byte) error {
	var res ServiceInstallPermissionsRoleStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
