// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceSlackChallengeResponse service slack challenge response
//
// swagger:model service.slackChallengeResponse
type ServiceSlackChallengeResponse struct {

	// challenge
	Challenge string `json:"challenge,omitempty"`
}

// Validate validates this service slack challenge response
func (m *ServiceSlackChallengeResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service slack challenge response based on context it is used
func (m *ServiceSlackChallengeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceSlackChallengeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceSlackChallengeResponse) UnmarshalBinary(b []byte) error {
	var res ServiceSlackChallengeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
