// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceCancelWorkflowError service cancel workflow error
//
// swagger:model service.CancelWorkflowError
type ServiceCancelWorkflowError struct {

	// error
	Error string `json:"error,omitempty"`

	// workflow id
	WorkflowID string `json:"workflow_id,omitempty"`
}

// Validate validates this service cancel workflow error
func (m *ServiceCancelWorkflowError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service cancel workflow error based on context it is used
func (m *ServiceCancelWorkflowError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceCancelWorkflowError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceCancelWorkflowError) UnmarshalBinary(b []byte) error {
	var res ServiceCancelWorkflowError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
