// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceUpdateRunbookRequest service update runbook request
//
// swagger:model service.UpdateRunbookRequest
type ServiceUpdateRunbookRequest struct {

	// description
	Description string `json:"description,omitempty"`

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this service update runbook request
func (m *ServiceUpdateRunbookRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service update runbook request based on context it is used
func (m *ServiceUpdateRunbookRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceUpdateRunbookRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceUpdateRunbookRequest) UnmarshalBinary(b []byte) error {
	var res ServiceUpdateRunbookRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
