// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppKustomizeConfig app kustomize config
//
// swagger:model app.KustomizeConfig
type AppKustomizeConfig struct {

	// Enable Helm chart inflation during kustomize build
	EnableHelm bool `json:"enable_helm,omitempty"`

	// Load restrictor: "none" or "rootOnly" (default: "rootOnly")
	LoadRestrictor string `json:"load_restrictor,omitempty"`

	// Additional patch files to apply after kustomize build
	Patches []string `json:"patches"`

	// Path to kustomization directory (relative to source root)
	Path string `json:"path,omitempty"`
}

// Validate validates this app kustomize config
func (m *AppKustomizeConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app kustomize config based on context it is used
func (m *AppKustomizeConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppKustomizeConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppKustomizeConfig) UnmarshalBinary(b []byte) error {
	var res AppKustomizeConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
