// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AppRunnerGroupSettings app runner group settings
//
// swagger:model app.RunnerGroupSettings
type AppRunnerGroupSettings struct {

	// aws auth method
	// Enum: ["iid","sts"]
	AwsAuthMethod string `json:"aws_auth_method,omitempty"`

	// aws cloudformation stack type
	AwsCloudformationStackType string `json:"aws_cloudformation_stack_type,omitempty"`

	// aws runner specifics runner-v2
	AwsInstanceType string `json:"aws_instance_type,omitempty"`

	// Deprecated: instance refresh is now handled by a backend cron, not ASG MaxInstanceLifetime.
	AwsMaxInstanceLifetime int64 `json:"aws_max_instance_lifetime,omitempty"`

	// aws tags
	AwsTags map[string]string `json:"aws_tags,omitempty"`

	// configuration for managing the runner binary version (for mng mode, not the install runner)
	BinaryVersion string `json:"binary_version,omitempty"`

	// container image tag
	ContainerImageTag string `json:"container_image_tag,omitempty"`

	// configuration for deploying the runner
	ContainerImageURL string `json:"container_image_url,omitempty"`

	// container max uptime
	ContainerMaxUptime int64 `json:"container_max_uptime,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// enable logging
	EnableLogging bool `json:"enable_logging,omitempty"`

	// enable metrics
	EnableMetrics bool `json:"enable_metrics,omitempty"`

	// enable sentry
	EnableSentry bool `json:"enable_sentry,omitempty"`

	// the job loop groups the runner should poll for
	Groups []string `json:"groups"`

	// Various settings for the runner to handle internally
	HeartBeatTimeout int64 `json:"heart_beat_timeout,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// JobGroupParallelism maps RunnerJobGroup names to max-in-flight counts for queue-based job routing.
	// e.g., {"build": "2", "deploy": "1"}. Only used when parallel-runner-jobs feature flag is on.
	JobGroupParallelism map[string]string `json:"job_group_parallelism,omitempty"`

	// local aws iam role arn
	LocalAwsIamRoleArn string `json:"local_aws_iam_role_arn,omitempty"`

	// logging level
	LoggingLevel string `json:"logging_level,omitempty"`

	// LongPollJobs mirrors the org's `runner-job-long-poll` feature flag
	// so the runner can choose between the legacy idle-poll loop and the
	// new long-poll endpoint at boot. Not persisted; populated by the
	// runner-settings handler.
	LongPollJobs bool `json:"long_poll_jobs,omitempty"`

	// Metadata is used as both log and metric tags/attributes in the runner when emitting data
	Metadata map[string]string `json:"metadata,omitempty"`

	// org runner specifics
	OrgAwsIamRoleArn string `json:"org_aws_iam_role_arn,omitempty"`

	// org azure client id
	OrgAzureClientID string `json:"org_azure_client_id,omitempty"`

	// org gcp service account
	OrgGcpServiceAccount string `json:"org_gcp_service_account,omitempty"`

	// org id
	OrgID string `json:"org_id,omitempty"`

	// org k8s service account name
	OrgK8sServiceAccountName string `json:"org_k8s_service_account_name,omitempty"`

	// otel collector config
	OtelCollectorConfig string `json:"otel_collector_config,omitempty"`

	// platform variable for use in the runner
	Platform string `json:"platform,omitempty"`

	// runner api url
	RunnerAPIURL string `json:"runner_api_url,omitempty"`

	// RunnerBinaryURL overrides the URL used to download the runner binary onto the
	// host for mng mode. When empty, defaults to the S3 artifacts URL.
	RunnerBinaryURL string `json:"runner_binary_url,omitempty"`

	// runner group id
	RunnerGroupID string `json:"runner_group_id,omitempty"`

	// configuration for managing the runner server side
	SandboxMode bool `json:"sandbox_mode,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// vm max uptime
	VMMaxUptime int64 `json:"vm_max_uptime,omitempty"`
}

// Validate validates this app runner group settings
func (m *AppRunnerGroupSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAwsAuthMethod(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var appRunnerGroupSettingsTypeAwsAuthMethodPropEnum []any

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["iid","sts"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		appRunnerGroupSettingsTypeAwsAuthMethodPropEnum = append(appRunnerGroupSettingsTypeAwsAuthMethodPropEnum, v)
	}
}

const (

	// AppRunnerGroupSettingsAwsAuthMethodIid captures enum value "iid"
	AppRunnerGroupSettingsAwsAuthMethodIid string = "iid"

	// AppRunnerGroupSettingsAwsAuthMethodSts captures enum value "sts"
	AppRunnerGroupSettingsAwsAuthMethodSts string = "sts"
)

// prop value enum
func (m *AppRunnerGroupSettings) validateAwsAuthMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, appRunnerGroupSettingsTypeAwsAuthMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AppRunnerGroupSettings) validateAwsAuthMethod(formats strfmt.Registry) error {
	if swag.IsZero(m.AwsAuthMethod) { // not required
		return nil
	}

	// value enum
	if err := m.validateAwsAuthMethodEnum("aws_auth_method", "body", m.AwsAuthMethod); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this app runner group settings based on context it is used
func (m *AppRunnerGroupSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppRunnerGroupSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppRunnerGroupSettings) UnmarshalBinary(b []byte) error {
	var res AppRunnerGroupSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
