// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppInstallRoleSelectionRecord app install role selection record
//
// swagger:model app.InstallRoleSelectionRecord
type AppInstallRoleSelectionRecord struct {

	// available
	Available bool `json:"available,omitempty"`

	// role id
	RoleID string `json:"role_id,omitempty"`

	// role name
	RoleName string `json:"role_name,omitempty"`

	// role source
	RoleSource string `json:"role_source,omitempty"`

	// selected
	Selected bool `json:"selected,omitempty"`
}

// Validate validates this app install role selection record
func (m *AppInstallRoleSelectionRecord) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this app install role selection record based on context it is used
func (m *AppInstallRoleSelectionRecord) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AppInstallRoleSelectionRecord) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppInstallRoleSelectionRecord) UnmarshalBinary(b []byte) error {
	var res AppInstallRoleSelectionRecord
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
