// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppQueueSignal app queue signal
//
// swagger:model app.QueueSignal
type AppQueueSignal struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// Optional: if this signal was emitted by an emitter
	EmitterID string `json:"emitter_id,omitempty"`

	// enqueued
	Enqueued bool `json:"enqueued,omitempty"`

	// execution count
	ExecutionCount int64 `json:"execution_count,omitempty"`

	// expires at
	ExpiresAt string `json:"expires_at,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// org id
	OrgID string `json:"org_id,omitempty"`

	// owner id
	OwnerID string `json:"owner_id,omitempty"`

	// owner type
	OwnerType string `json:"owner_type,omitempty"`

	// queue
	Queue *AppQueue `json:"queue,omitempty"`

	// queue id
	QueueID string `json:"queue_id,omitempty"`

	// signal
	Signal *SignaldbSignalData `json:"signal,omitempty"`

	// signal context
	SignalContext *CctxSignalContext `json:"signal_context,omitempty"`

	// status
	Status *AppCompositeStatus `json:"status,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// workflow
	Workflow *SignaldbWorkflowRef `json:"workflow,omitempty"`
}

// Validate validates this app queue signal
func (m *AppQueueSignal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateQueue(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignal(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSignalContext(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWorkflow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppQueueSignal) validateQueue(formats strfmt.Registry) error {
	if swag.IsZero(m.Queue) { // not required
		return nil
	}

	if m.Queue != nil {
		if err := m.Queue.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("queue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("queue")
			}

			return err
		}
	}

	return nil
}

func (m *AppQueueSignal) validateSignal(formats strfmt.Registry) error {
	if swag.IsZero(m.Signal) { // not required
		return nil
	}

	if m.Signal != nil {
		if err := m.Signal.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("signal")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("signal")
			}

			return err
		}
	}

	return nil
}

func (m *AppQueueSignal) validateSignalContext(formats strfmt.Registry) error {
	if swag.IsZero(m.SignalContext) { // not required
		return nil
	}

	if m.SignalContext != nil {
		if err := m.SignalContext.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("signal_context")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("signal_context")
			}

			return err
		}
	}

	return nil
}

func (m *AppQueueSignal) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("status")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("status")
			}

			return err
		}
	}

	return nil
}

func (m *AppQueueSignal) validateWorkflow(formats strfmt.Registry) error {
	if swag.IsZero(m.Workflow) { // not required
		return nil
	}

	if m.Workflow != nil {
		if err := m.Workflow.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("workflow")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("workflow")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this app queue signal based on the context it is used
func (m *AppQueueSignal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateQueue(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSignal(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSignalContext(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWorkflow(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppQueueSignal) contextValidateQueue(ctx context.Context, formats strfmt.Registry) error {

	if m.Queue != nil {

		if swag.IsZero(m.Queue) { // not required
			return nil
		}

		if err := m.Queue.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("queue")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("queue")
			}

			return err
		}
	}

	return nil
}

func (m *AppQueueSignal) contextValidateSignal(ctx context.Context, formats strfmt.Registry) error {

	if m.Signal != nil {

		if swag.IsZero(m.Signal) { // not required
			return nil
		}

		if err := m.Signal.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("signal")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("signal")
			}

			return err
		}
	}

	return nil
}

func (m *AppQueueSignal) contextValidateSignalContext(ctx context.Context, formats strfmt.Registry) error {

	if m.SignalContext != nil {

		if swag.IsZero(m.SignalContext) { // not required
			return nil
		}

		if err := m.SignalContext.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("signal_context")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("signal_context")
			}

			return err
		}
	}

	return nil
}

func (m *AppQueueSignal) contextValidateStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.Status != nil {

		if swag.IsZero(m.Status) { // not required
			return nil
		}

		if err := m.Status.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("status")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("status")
			}

			return err
		}
	}

	return nil
}

func (m *AppQueueSignal) contextValidateWorkflow(ctx context.Context, formats strfmt.Registry) error {

	if m.Workflow != nil {

		if swag.IsZero(m.Workflow) { // not required
			return nil
		}

		if err := m.Workflow.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("workflow")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("workflow")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppQueueSignal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppQueueSignal) UnmarshalBinary(b []byte) error {
	var res AppQueueSignal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
