// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AppRunnerJobPlan app runner job plan
//
// swagger:model app.RunnerJobPlan
type AppRunnerJobPlan struct {

	// composite plan
	CompositePlan *PlantypesCompositePlan `json:"composite_plan,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by id
	CreatedByID string `json:"created_by_id,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// org id
	OrgID string `json:"org_id,omitempty"`

	// plan json
	PlanJSON string `json:"plan_json,omitempty"`

	// runner job id
	RunnerJobID string `json:"runner_job_id,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`
}

// Validate validates this app runner job plan
func (m *AppRunnerJobPlan) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCompositePlan(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppRunnerJobPlan) validateCompositePlan(formats strfmt.Registry) error {
	if swag.IsZero(m.CompositePlan) { // not required
		return nil
	}

	if m.CompositePlan != nil {
		if err := m.CompositePlan.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("composite_plan")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("composite_plan")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this app runner job plan based on the context it is used
func (m *AppRunnerJobPlan) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCompositePlan(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AppRunnerJobPlan) contextValidateCompositePlan(ctx context.Context, formats strfmt.Registry) error {

	if m.CompositePlan != nil {

		if swag.IsZero(m.CompositePlan) { // not required
			return nil
		}

		if err := m.CompositePlan.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("composite_plan")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("composite_plan")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AppRunnerJobPlan) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AppRunnerJobPlan) UnmarshalBinary(b []byte) error {
	var res AppRunnerJobPlan
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
