// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PlantypesTerraformBuildPlan plantypes terraform build plan
//
// swagger:model plantypes.TerraformBuildPlan
type PlantypesTerraformBuildPlan struct {

	// labels
	Labels map[string]string `json:"labels,omitempty"`

	// TerraformVersion is the version of the terraform CLI the build runner
	// should install in order to vendor providers via
	// `terraform providers mirror`. When empty the build runner falls back
	// to a sane default. Should mirror the version configured for the
	// component's deploy plan so init resolves the same provider bytes the
	// build vendored. Only consulted when VendorProviders is true.
	TerraformVersion string `json:"terraform_version,omitempty"`

	// VendorProviders enables build-time vendoring of terraform providers
	// via `terraform providers mirror`. Gated by the
	// `terraform-provider-mirror` org feature flag in ctl-api so we can
	// roll the change out gradually without coupling install-runner
	// behaviour to the flag (the install runner auto-detects whether a
	// mirror is present in the OCI artifact).
	VendorProviders bool `json:"vendor_providers,omitempty"`
}

// Validate validates this plantypes terraform build plan
func (m *PlantypesTerraformBuildPlan) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this plantypes terraform build plan based on context it is used
func (m *PlantypesTerraformBuildPlan) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PlantypesTerraformBuildPlan) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PlantypesTerraformBuildPlan) UnmarshalBinary(b []byte) error {
	var res PlantypesTerraformBuildPlan
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
