// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceCreateRunnerProcessRequest service create runner process request
//
// swagger:model service.CreateRunnerProcessRequest
type ServiceCreateRunnerProcessRequest struct {

	// type
	// Required: true
	Type *string `json:"type"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this service create runner process request
func (m *ServiceCreateRunnerProcessRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceCreateRunnerProcessRequest) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this service create runner process request based on context it is used
func (m *ServiceCreateRunnerProcessRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceCreateRunnerProcessRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceCreateRunnerProcessRequest) UnmarshalBinary(b []byte) error {
	var res ServiceCreateRunnerProcessRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
