// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1HookExecution v1 hook execution
//
// swagger:model v1.HookExecution
type V1HookExecution struct {

	// CompletedAt indicates the date/time this hook was completed.
	CompletedAt string `json:"completed_at,omitempty"`

	// Phase indicates whether the hook completed successfully
	Phase struct {
		V1HookPhase
	} `json:"phase,omitempty"`

	// StartedAt indicates the date/time this hook was started
	StartedAt string `json:"started_at,omitempty"`
}

// Validate validates this v1 hook execution
func (m *V1HookExecution) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePhase(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1HookExecution) validatePhase(formats strfmt.Registry) error {
	if swag.IsZero(m.Phase) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this v1 hook execution based on the context it is used
func (m *V1HookExecution) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePhase(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1HookExecution) contextValidatePhase(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *V1HookExecution) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1HookExecution) UnmarshalBinary(b []byte) error {
	var res V1HookExecution
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
