// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-runner-go/models"
)

// CreateRunnerJobExecutionOutputsReader is a Reader for the CreateRunnerJobExecutionOutputs structure.
type CreateRunnerJobExecutionOutputsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRunnerJobExecutionOutputsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 201:
		result := NewCreateRunnerJobExecutionOutputsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateRunnerJobExecutionOutputsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateRunnerJobExecutionOutputsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateRunnerJobExecutionOutputsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewCreateRunnerJobExecutionOutputsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateRunnerJobExecutionOutputsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateRunnerJobExecutionOutputsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs] CreateRunnerJobExecutionOutputs", response, response.Code())
	}
}

// NewCreateRunnerJobExecutionOutputsCreated creates a CreateRunnerJobExecutionOutputsCreated with default headers values
func NewCreateRunnerJobExecutionOutputsCreated() *CreateRunnerJobExecutionOutputsCreated {
	return &CreateRunnerJobExecutionOutputsCreated{}
}

/*
CreateRunnerJobExecutionOutputsCreated describes a response with status code 201, with default header values.

Created
*/
type CreateRunnerJobExecutionOutputsCreated struct {
	Payload *models.AppRunnerJobExecutionOutputs
}

// IsSuccess returns true when this create runner job execution outputs created response has a 2xx status code
func (o *CreateRunnerJobExecutionOutputsCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create runner job execution outputs created response has a 3xx status code
func (o *CreateRunnerJobExecutionOutputsCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create runner job execution outputs created response has a 4xx status code
func (o *CreateRunnerJobExecutionOutputsCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create runner job execution outputs created response has a 5xx status code
func (o *CreateRunnerJobExecutionOutputsCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create runner job execution outputs created response a status code equal to that given
func (o *CreateRunnerJobExecutionOutputsCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create runner job execution outputs created response
func (o *CreateRunnerJobExecutionOutputsCreated) Code() int {
	return 201
}

func (o *CreateRunnerJobExecutionOutputsCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsCreated %s", 201, payload)
}

func (o *CreateRunnerJobExecutionOutputsCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsCreated %s", 201, payload)
}

func (o *CreateRunnerJobExecutionOutputsCreated) GetPayload() *models.AppRunnerJobExecutionOutputs {
	return o.Payload
}

func (o *CreateRunnerJobExecutionOutputsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AppRunnerJobExecutionOutputs)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateRunnerJobExecutionOutputsBadRequest creates a CreateRunnerJobExecutionOutputsBadRequest with default headers values
func NewCreateRunnerJobExecutionOutputsBadRequest() *CreateRunnerJobExecutionOutputsBadRequest {
	return &CreateRunnerJobExecutionOutputsBadRequest{}
}

/*
CreateRunnerJobExecutionOutputsBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateRunnerJobExecutionOutputsBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create runner job execution outputs bad request response has a 2xx status code
func (o *CreateRunnerJobExecutionOutputsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create runner job execution outputs bad request response has a 3xx status code
func (o *CreateRunnerJobExecutionOutputsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create runner job execution outputs bad request response has a 4xx status code
func (o *CreateRunnerJobExecutionOutputsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create runner job execution outputs bad request response has a 5xx status code
func (o *CreateRunnerJobExecutionOutputsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create runner job execution outputs bad request response a status code equal to that given
func (o *CreateRunnerJobExecutionOutputsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create runner job execution outputs bad request response
func (o *CreateRunnerJobExecutionOutputsBadRequest) Code() int {
	return 400
}

func (o *CreateRunnerJobExecutionOutputsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsBadRequest %s", 400, payload)
}

func (o *CreateRunnerJobExecutionOutputsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsBadRequest %s", 400, payload)
}

func (o *CreateRunnerJobExecutionOutputsBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateRunnerJobExecutionOutputsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateRunnerJobExecutionOutputsUnauthorized creates a CreateRunnerJobExecutionOutputsUnauthorized with default headers values
func NewCreateRunnerJobExecutionOutputsUnauthorized() *CreateRunnerJobExecutionOutputsUnauthorized {
	return &CreateRunnerJobExecutionOutputsUnauthorized{}
}

/*
CreateRunnerJobExecutionOutputsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateRunnerJobExecutionOutputsUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create runner job execution outputs unauthorized response has a 2xx status code
func (o *CreateRunnerJobExecutionOutputsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create runner job execution outputs unauthorized response has a 3xx status code
func (o *CreateRunnerJobExecutionOutputsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create runner job execution outputs unauthorized response has a 4xx status code
func (o *CreateRunnerJobExecutionOutputsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create runner job execution outputs unauthorized response has a 5xx status code
func (o *CreateRunnerJobExecutionOutputsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create runner job execution outputs unauthorized response a status code equal to that given
func (o *CreateRunnerJobExecutionOutputsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create runner job execution outputs unauthorized response
func (o *CreateRunnerJobExecutionOutputsUnauthorized) Code() int {
	return 401
}

func (o *CreateRunnerJobExecutionOutputsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsUnauthorized %s", 401, payload)
}

func (o *CreateRunnerJobExecutionOutputsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsUnauthorized %s", 401, payload)
}

func (o *CreateRunnerJobExecutionOutputsUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateRunnerJobExecutionOutputsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateRunnerJobExecutionOutputsForbidden creates a CreateRunnerJobExecutionOutputsForbidden with default headers values
func NewCreateRunnerJobExecutionOutputsForbidden() *CreateRunnerJobExecutionOutputsForbidden {
	return &CreateRunnerJobExecutionOutputsForbidden{}
}

/*
CreateRunnerJobExecutionOutputsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateRunnerJobExecutionOutputsForbidden struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create runner job execution outputs forbidden response has a 2xx status code
func (o *CreateRunnerJobExecutionOutputsForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create runner job execution outputs forbidden response has a 3xx status code
func (o *CreateRunnerJobExecutionOutputsForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create runner job execution outputs forbidden response has a 4xx status code
func (o *CreateRunnerJobExecutionOutputsForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create runner job execution outputs forbidden response has a 5xx status code
func (o *CreateRunnerJobExecutionOutputsForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create runner job execution outputs forbidden response a status code equal to that given
func (o *CreateRunnerJobExecutionOutputsForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create runner job execution outputs forbidden response
func (o *CreateRunnerJobExecutionOutputsForbidden) Code() int {
	return 403
}

func (o *CreateRunnerJobExecutionOutputsForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsForbidden %s", 403, payload)
}

func (o *CreateRunnerJobExecutionOutputsForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsForbidden %s", 403, payload)
}

func (o *CreateRunnerJobExecutionOutputsForbidden) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateRunnerJobExecutionOutputsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateRunnerJobExecutionOutputsNotFound creates a CreateRunnerJobExecutionOutputsNotFound with default headers values
func NewCreateRunnerJobExecutionOutputsNotFound() *CreateRunnerJobExecutionOutputsNotFound {
	return &CreateRunnerJobExecutionOutputsNotFound{}
}

/*
CreateRunnerJobExecutionOutputsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type CreateRunnerJobExecutionOutputsNotFound struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create runner job execution outputs not found response has a 2xx status code
func (o *CreateRunnerJobExecutionOutputsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create runner job execution outputs not found response has a 3xx status code
func (o *CreateRunnerJobExecutionOutputsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create runner job execution outputs not found response has a 4xx status code
func (o *CreateRunnerJobExecutionOutputsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this create runner job execution outputs not found response has a 5xx status code
func (o *CreateRunnerJobExecutionOutputsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this create runner job execution outputs not found response a status code equal to that given
func (o *CreateRunnerJobExecutionOutputsNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the create runner job execution outputs not found response
func (o *CreateRunnerJobExecutionOutputsNotFound) Code() int {
	return 404
}

func (o *CreateRunnerJobExecutionOutputsNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsNotFound %s", 404, payload)
}

func (o *CreateRunnerJobExecutionOutputsNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsNotFound %s", 404, payload)
}

func (o *CreateRunnerJobExecutionOutputsNotFound) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateRunnerJobExecutionOutputsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateRunnerJobExecutionOutputsConflict creates a CreateRunnerJobExecutionOutputsConflict with default headers values
func NewCreateRunnerJobExecutionOutputsConflict() *CreateRunnerJobExecutionOutputsConflict {
	return &CreateRunnerJobExecutionOutputsConflict{}
}

/*
CreateRunnerJobExecutionOutputsConflict describes a response with status code 409, with default header values.

Conflict
*/
type CreateRunnerJobExecutionOutputsConflict struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create runner job execution outputs conflict response has a 2xx status code
func (o *CreateRunnerJobExecutionOutputsConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create runner job execution outputs conflict response has a 3xx status code
func (o *CreateRunnerJobExecutionOutputsConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create runner job execution outputs conflict response has a 4xx status code
func (o *CreateRunnerJobExecutionOutputsConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create runner job execution outputs conflict response has a 5xx status code
func (o *CreateRunnerJobExecutionOutputsConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create runner job execution outputs conflict response a status code equal to that given
func (o *CreateRunnerJobExecutionOutputsConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the create runner job execution outputs conflict response
func (o *CreateRunnerJobExecutionOutputsConflict) Code() int {
	return 409
}

func (o *CreateRunnerJobExecutionOutputsConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsConflict %s", 409, payload)
}

func (o *CreateRunnerJobExecutionOutputsConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsConflict %s", 409, payload)
}

func (o *CreateRunnerJobExecutionOutputsConflict) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateRunnerJobExecutionOutputsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewCreateRunnerJobExecutionOutputsInternalServerError creates a CreateRunnerJobExecutionOutputsInternalServerError with default headers values
func NewCreateRunnerJobExecutionOutputsInternalServerError() *CreateRunnerJobExecutionOutputsInternalServerError {
	return &CreateRunnerJobExecutionOutputsInternalServerError{}
}

/*
CreateRunnerJobExecutionOutputsInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateRunnerJobExecutionOutputsInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this create runner job execution outputs internal server error response has a 2xx status code
func (o *CreateRunnerJobExecutionOutputsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create runner job execution outputs internal server error response has a 3xx status code
func (o *CreateRunnerJobExecutionOutputsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create runner job execution outputs internal server error response has a 4xx status code
func (o *CreateRunnerJobExecutionOutputsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create runner job execution outputs internal server error response has a 5xx status code
func (o *CreateRunnerJobExecutionOutputsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create runner job execution outputs internal server error response a status code equal to that given
func (o *CreateRunnerJobExecutionOutputsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create runner job execution outputs internal server error response
func (o *CreateRunnerJobExecutionOutputsInternalServerError) Code() int {
	return 500
}

func (o *CreateRunnerJobExecutionOutputsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsInternalServerError %s", 500, payload)
}

func (o *CreateRunnerJobExecutionOutputsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-jobs/{runner_job_id}/executions/{runner_job_execution_id}/outputs][%d] createRunnerJobExecutionOutputsInternalServerError %s", 500, payload)
}

func (o *CreateRunnerJobExecutionOutputsInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *CreateRunnerJobExecutionOutputsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
