// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteTerraformStateJSONParams creates a new DeleteTerraformStateJSONParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTerraformStateJSONParams() *DeleteTerraformStateJSONParams {
	return &DeleteTerraformStateJSONParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTerraformStateJSONParamsWithTimeout creates a new DeleteTerraformStateJSONParams object
// with the ability to set a timeout on a request.
func NewDeleteTerraformStateJSONParamsWithTimeout(timeout time.Duration) *DeleteTerraformStateJSONParams {
	return &DeleteTerraformStateJSONParams{
		timeout: timeout,
	}
}

// NewDeleteTerraformStateJSONParamsWithContext creates a new DeleteTerraformStateJSONParams object
// with the ability to set a context for a request.
func NewDeleteTerraformStateJSONParamsWithContext(ctx context.Context) *DeleteTerraformStateJSONParams {
	return &DeleteTerraformStateJSONParams{
		Context: ctx,
	}
}

// NewDeleteTerraformStateJSONParamsWithHTTPClient creates a new DeleteTerraformStateJSONParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTerraformStateJSONParamsWithHTTPClient(client *http.Client) *DeleteTerraformStateJSONParams {
	return &DeleteTerraformStateJSONParams{
		HTTPClient: client,
	}
}

/*
DeleteTerraformStateJSONParams contains all the parameters to send to the API endpoint

	for the delete terraform state JSON operation.

	Typically these are written to a http.Request.
*/
type DeleteTerraformStateJSONParams struct {

	/* WorkspaceID.

	   workspace ID
	*/
	WorkspaceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete terraform state JSON params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTerraformStateJSONParams) WithDefaults() *DeleteTerraformStateJSONParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete terraform state JSON params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTerraformStateJSONParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete terraform state JSON params
func (o *DeleteTerraformStateJSONParams) WithTimeout(timeout time.Duration) *DeleteTerraformStateJSONParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete terraform state JSON params
func (o *DeleteTerraformStateJSONParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete terraform state JSON params
func (o *DeleteTerraformStateJSONParams) WithContext(ctx context.Context) *DeleteTerraformStateJSONParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete terraform state JSON params
func (o *DeleteTerraformStateJSONParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete terraform state JSON params
func (o *DeleteTerraformStateJSONParams) WithHTTPClient(client *http.Client) *DeleteTerraformStateJSONParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete terraform state JSON params
func (o *DeleteTerraformStateJSONParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkspaceID adds the workspaceID to the delete terraform state JSON params
func (o *DeleteTerraformStateJSONParams) WithWorkspaceID(workspaceID string) *DeleteTerraformStateJSONParams {
	o.SetWorkspaceID(workspaceID)
	return o
}

// SetWorkspaceID adds the workspaceId to the delete terraform state JSON params
func (o *DeleteTerraformStateJSONParams) SetWorkspaceID(workspaceID string) {
	o.WorkspaceID = workspaceID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTerraformStateJSONParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param workspace_id
	if err := r.SetPathParam("workspace_id", o.WorkspaceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
