// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInstallComponenetLastActivePlanParams creates a new GetInstallComponenetLastActivePlanParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetInstallComponenetLastActivePlanParams() *GetInstallComponenetLastActivePlanParams {
	return &GetInstallComponenetLastActivePlanParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetInstallComponenetLastActivePlanParamsWithTimeout creates a new GetInstallComponenetLastActivePlanParams object
// with the ability to set a timeout on a request.
func NewGetInstallComponenetLastActivePlanParamsWithTimeout(timeout time.Duration) *GetInstallComponenetLastActivePlanParams {
	return &GetInstallComponenetLastActivePlanParams{
		timeout: timeout,
	}
}

// NewGetInstallComponenetLastActivePlanParamsWithContext creates a new GetInstallComponenetLastActivePlanParams object
// with the ability to set a context for a request.
func NewGetInstallComponenetLastActivePlanParamsWithContext(ctx context.Context) *GetInstallComponenetLastActivePlanParams {
	return &GetInstallComponenetLastActivePlanParams{
		Context: ctx,
	}
}

// NewGetInstallComponenetLastActivePlanParamsWithHTTPClient creates a new GetInstallComponenetLastActivePlanParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetInstallComponenetLastActivePlanParamsWithHTTPClient(client *http.Client) *GetInstallComponenetLastActivePlanParams {
	return &GetInstallComponenetLastActivePlanParams{
		HTTPClient: client,
	}
}

/*
GetInstallComponenetLastActivePlanParams contains all the parameters to send to the API endpoint

	for the get install componenet last active plan operation.

	Typically these are written to a http.Request.
*/
type GetInstallComponenetLastActivePlanParams struct {

	/* ComponentID.

	   component ID
	*/
	ComponentID string

	/* InstallID.

	   install ID
	*/
	InstallID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get install componenet last active plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallComponenetLastActivePlanParams) WithDefaults() *GetInstallComponenetLastActivePlanParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get install componenet last active plan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetInstallComponenetLastActivePlanParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) WithTimeout(timeout time.Duration) *GetInstallComponenetLastActivePlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) WithContext(ctx context.Context) *GetInstallComponenetLastActivePlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) WithHTTPClient(client *http.Client) *GetInstallComponenetLastActivePlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComponentID adds the componentID to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) WithComponentID(componentID string) *GetInstallComponenetLastActivePlanParams {
	o.SetComponentID(componentID)
	return o
}

// SetComponentID adds the componentId to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) SetComponentID(componentID string) {
	o.ComponentID = componentID
}

// WithInstallID adds the installID to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) WithInstallID(installID string) *GetInstallComponenetLastActivePlanParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get install componenet last active plan params
func (o *GetInstallComponenetLastActivePlanParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WriteToRequest writes these params to a swagger request
func (o *GetInstallComponenetLastActivePlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param component_id
	if err := r.SetPathParam("component_id", o.ComponentID); err != nil {
		return err
	}

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
