// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetV1InstallInstallIDOwnerPlansOwnerIDParams creates a new GetV1InstallInstallIDOwnerPlansOwnerIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetV1InstallInstallIDOwnerPlansOwnerIDParams() *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	return &GetV1InstallInstallIDOwnerPlansOwnerIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetV1InstallInstallIDOwnerPlansOwnerIDParamsWithTimeout creates a new GetV1InstallInstallIDOwnerPlansOwnerIDParams object
// with the ability to set a timeout on a request.
func NewGetV1InstallInstallIDOwnerPlansOwnerIDParamsWithTimeout(timeout time.Duration) *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	return &GetV1InstallInstallIDOwnerPlansOwnerIDParams{
		timeout: timeout,
	}
}

// NewGetV1InstallInstallIDOwnerPlansOwnerIDParamsWithContext creates a new GetV1InstallInstallIDOwnerPlansOwnerIDParams object
// with the ability to set a context for a request.
func NewGetV1InstallInstallIDOwnerPlansOwnerIDParamsWithContext(ctx context.Context) *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	return &GetV1InstallInstallIDOwnerPlansOwnerIDParams{
		Context: ctx,
	}
}

// NewGetV1InstallInstallIDOwnerPlansOwnerIDParamsWithHTTPClient creates a new GetV1InstallInstallIDOwnerPlansOwnerIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetV1InstallInstallIDOwnerPlansOwnerIDParamsWithHTTPClient(client *http.Client) *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	return &GetV1InstallInstallIDOwnerPlansOwnerIDParams{
		HTTPClient: client,
	}
}

/*
GetV1InstallInstallIDOwnerPlansOwnerIDParams contains all the parameters to send to the API endpoint

	for the get v1 install install ID owner plans owner ID operation.

	Typically these are written to a http.Request.
*/
type GetV1InstallInstallIDOwnerPlansOwnerIDParams struct {

	/* InstallID.

	   Install ID
	*/
	InstallID string

	/* OwnerID.

	   Owner ID
	*/
	OwnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get v1 install install ID owner plans owner ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) WithDefaults() *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get v1 install install ID owner plans owner ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) WithTimeout(timeout time.Duration) *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) WithContext(ctx context.Context) *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) WithHTTPClient(client *http.Client) *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInstallID adds the installID to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) WithInstallID(installID string) *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	o.SetInstallID(installID)
	return o
}

// SetInstallID adds the installId to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) SetInstallID(installID string) {
	o.InstallID = installID
}

// WithOwnerID adds the ownerID to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) WithOwnerID(ownerID string) *GetV1InstallInstallIDOwnerPlansOwnerIDParams {
	o.SetOwnerID(ownerID)
	return o
}

// SetOwnerID adds the ownerId to the get v1 install install ID owner plans owner ID params
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) SetOwnerID(ownerID string) {
	o.OwnerID = ownerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetV1InstallInstallIDOwnerPlansOwnerIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param install_id
	if err := r.SetPathParam("install_id", o.InstallID); err != nil {
		return err
	}

	// path param owner_id
	if err := r.SetPathParam("owner_id", o.OwnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
