// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-runner-go/models"
)

// NewRunnerOtelWriteLogsParams creates a new RunnerOtelWriteLogsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRunnerOtelWriteLogsParams() *RunnerOtelWriteLogsParams {
	return &RunnerOtelWriteLogsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRunnerOtelWriteLogsParamsWithTimeout creates a new RunnerOtelWriteLogsParams object
// with the ability to set a timeout on a request.
func NewRunnerOtelWriteLogsParamsWithTimeout(timeout time.Duration) *RunnerOtelWriteLogsParams {
	return &RunnerOtelWriteLogsParams{
		timeout: timeout,
	}
}

// NewRunnerOtelWriteLogsParamsWithContext creates a new RunnerOtelWriteLogsParams object
// with the ability to set a context for a request.
func NewRunnerOtelWriteLogsParamsWithContext(ctx context.Context) *RunnerOtelWriteLogsParams {
	return &RunnerOtelWriteLogsParams{
		Context: ctx,
	}
}

// NewRunnerOtelWriteLogsParamsWithHTTPClient creates a new RunnerOtelWriteLogsParams object
// with the ability to set a custom HTTPClient for a request.
func NewRunnerOtelWriteLogsParamsWithHTTPClient(client *http.Client) *RunnerOtelWriteLogsParams {
	return &RunnerOtelWriteLogsParams{
		HTTPClient: client,
	}
}

/*
RunnerOtelWriteLogsParams contains all the parameters to send to the API endpoint

	for the runner otel write logs operation.

	Typically these are written to a http.Request.
*/
type RunnerOtelWriteLogsParams struct {

	/* Req.

	   Input
	*/
	Req *models.OtelOTLPLogExportRequest

	/* RunnerID.

	   runner ID
	*/
	RunnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the runner otel write logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunnerOtelWriteLogsParams) WithDefaults() *RunnerOtelWriteLogsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the runner otel write logs params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RunnerOtelWriteLogsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) WithTimeout(timeout time.Duration) *RunnerOtelWriteLogsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) WithContext(ctx context.Context) *RunnerOtelWriteLogsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) WithHTTPClient(client *http.Client) *RunnerOtelWriteLogsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithReq adds the req to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) WithReq(req *models.OtelOTLPLogExportRequest) *RunnerOtelWriteLogsParams {
	o.SetReq(req)
	return o
}

// SetReq adds the req to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) SetReq(req *models.OtelOTLPLogExportRequest) {
	o.Req = req
}

// WithRunnerID adds the runnerID to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) WithRunnerID(runnerID string) *RunnerOtelWriteLogsParams {
	o.SetRunnerID(runnerID)
	return o
}

// SetRunnerID adds the runnerId to the runner otel write logs params
func (o *RunnerOtelWriteLogsParams) SetRunnerID(runnerID string) {
	o.RunnerID = runnerID
}

// WriteToRequest writes these params to a swagger request
func (o *RunnerOtelWriteLogsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Req != nil {
		if err := r.SetBodyParam(o.Req); err != nil {
			return err
		}
	}

	// path param runner_id
	if err := r.SetPathParam("runner_id", o.RunnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
