// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/nuonco/nuon/sdks/nuon-runner-go/models"
)

// RunnerAuthAWSReader is a Reader for the RunnerAuthAWS structure.
type RunnerAuthAWSReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RunnerAuthAWSReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewRunnerAuthAWSOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRunnerAuthAWSBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewRunnerAuthAWSUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRunnerAuthAWSInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /v1/runner-auth/aws] RunnerAuthAWS", response, response.Code())
	}
}

// NewRunnerAuthAWSOK creates a RunnerAuthAWSOK with default headers values
func NewRunnerAuthAWSOK() *RunnerAuthAWSOK {
	return &RunnerAuthAWSOK{}
}

/*
RunnerAuthAWSOK describes a response with status code 200, with default header values.

OK
*/
type RunnerAuthAWSOK struct {
	Payload *models.GithubComNuoncoNuonServicesCtlAPIInternalAppRunnerAuthServiceRunnerAuthAWSResponse
}

// IsSuccess returns true when this runner auth a w s o k response has a 2xx status code
func (o *RunnerAuthAWSOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this runner auth a w s o k response has a 3xx status code
func (o *RunnerAuthAWSOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this runner auth a w s o k response has a 4xx status code
func (o *RunnerAuthAWSOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this runner auth a w s o k response has a 5xx status code
func (o *RunnerAuthAWSOK) IsServerError() bool {
	return false
}

// IsCode returns true when this runner auth a w s o k response a status code equal to that given
func (o *RunnerAuthAWSOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the runner auth a w s o k response
func (o *RunnerAuthAWSOK) Code() int {
	return 200
}

func (o *RunnerAuthAWSOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-auth/aws][%d] runnerAuthAWSOK %s", 200, payload)
}

func (o *RunnerAuthAWSOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-auth/aws][%d] runnerAuthAWSOK %s", 200, payload)
}

func (o *RunnerAuthAWSOK) GetPayload() *models.GithubComNuoncoNuonServicesCtlAPIInternalAppRunnerAuthServiceRunnerAuthAWSResponse {
	return o.Payload
}

func (o *RunnerAuthAWSOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GithubComNuoncoNuonServicesCtlAPIInternalAppRunnerAuthServiceRunnerAuthAWSResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRunnerAuthAWSBadRequest creates a RunnerAuthAWSBadRequest with default headers values
func NewRunnerAuthAWSBadRequest() *RunnerAuthAWSBadRequest {
	return &RunnerAuthAWSBadRequest{}
}

/*
RunnerAuthAWSBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type RunnerAuthAWSBadRequest struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this runner auth a w s bad request response has a 2xx status code
func (o *RunnerAuthAWSBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this runner auth a w s bad request response has a 3xx status code
func (o *RunnerAuthAWSBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this runner auth a w s bad request response has a 4xx status code
func (o *RunnerAuthAWSBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this runner auth a w s bad request response has a 5xx status code
func (o *RunnerAuthAWSBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this runner auth a w s bad request response a status code equal to that given
func (o *RunnerAuthAWSBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the runner auth a w s bad request response
func (o *RunnerAuthAWSBadRequest) Code() int {
	return 400
}

func (o *RunnerAuthAWSBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-auth/aws][%d] runnerAuthAWSBadRequest %s", 400, payload)
}

func (o *RunnerAuthAWSBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-auth/aws][%d] runnerAuthAWSBadRequest %s", 400, payload)
}

func (o *RunnerAuthAWSBadRequest) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *RunnerAuthAWSBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRunnerAuthAWSUnauthorized creates a RunnerAuthAWSUnauthorized with default headers values
func NewRunnerAuthAWSUnauthorized() *RunnerAuthAWSUnauthorized {
	return &RunnerAuthAWSUnauthorized{}
}

/*
RunnerAuthAWSUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type RunnerAuthAWSUnauthorized struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this runner auth a w s unauthorized response has a 2xx status code
func (o *RunnerAuthAWSUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this runner auth a w s unauthorized response has a 3xx status code
func (o *RunnerAuthAWSUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this runner auth a w s unauthorized response has a 4xx status code
func (o *RunnerAuthAWSUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this runner auth a w s unauthorized response has a 5xx status code
func (o *RunnerAuthAWSUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this runner auth a w s unauthorized response a status code equal to that given
func (o *RunnerAuthAWSUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the runner auth a w s unauthorized response
func (o *RunnerAuthAWSUnauthorized) Code() int {
	return 401
}

func (o *RunnerAuthAWSUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-auth/aws][%d] runnerAuthAWSUnauthorized %s", 401, payload)
}

func (o *RunnerAuthAWSUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-auth/aws][%d] runnerAuthAWSUnauthorized %s", 401, payload)
}

func (o *RunnerAuthAWSUnauthorized) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *RunnerAuthAWSUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewRunnerAuthAWSInternalServerError creates a RunnerAuthAWSInternalServerError with default headers values
func NewRunnerAuthAWSInternalServerError() *RunnerAuthAWSInternalServerError {
	return &RunnerAuthAWSInternalServerError{}
}

/*
RunnerAuthAWSInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type RunnerAuthAWSInternalServerError struct {
	Payload *models.StderrErrResponse
}

// IsSuccess returns true when this runner auth a w s internal server error response has a 2xx status code
func (o *RunnerAuthAWSInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this runner auth a w s internal server error response has a 3xx status code
func (o *RunnerAuthAWSInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this runner auth a w s internal server error response has a 4xx status code
func (o *RunnerAuthAWSInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this runner auth a w s internal server error response has a 5xx status code
func (o *RunnerAuthAWSInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this runner auth a w s internal server error response a status code equal to that given
func (o *RunnerAuthAWSInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the runner auth a w s internal server error response
func (o *RunnerAuthAWSInternalServerError) Code() int {
	return 500
}

func (o *RunnerAuthAWSInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-auth/aws][%d] runnerAuthAWSInternalServerError %s", 500, payload)
}

func (o *RunnerAuthAWSInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1/runner-auth/aws][%d] runnerAuthAWSInternalServerError %s", 500, payload)
}

func (o *RunnerAuthAWSInternalServerError) GetPayload() *models.StderrErrResponse {
	return o.Payload
}

func (o *RunnerAuthAWSInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StderrErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
