export const AWS_REGIONS = [
  // usa
  {
    helpText: "us-east-1",
    iconVariant: "flag-US",
    text: "US East (N. Virginia)",
    value: "us-east-1",
  },
  {
    helpText: "us-east-2",
    iconVariant: "flag-US",
    text: "US East (Ohio)",
    value: "us-east-2",
  },
  {
    helpText: "us-west-1",
    iconVariant: "flag-US",
    text: "US West (N. California)",
    value: "us-west-1",
  },
  {
    helpText: "us-west-2",
    iconVariant: "flag-US",
    text: "US West (Oregon)",
    value: "us-west-2",
  },

  // africa
  {
    helpText: "af-south-1",
    iconVariant: "flag-ZA",
    text: "Africa (Cape Town)",
    value: "af-south-1",
  },

  // asia
  {
    helpText: "ap-east-1",
    iconVariant: "flag-HK",
    text: "Asia Pacific (Hong Kong)",
    value: "ap-east-1",
  },
  {
    helpText: "ap-south-2",
    iconVariant: "flag-IN",
    text: "Asia Pacific (Hyderabad)",
    value: "ap-south-2",
  },
  {
    helpText: "ap-southeast-3",
    iconVariant: "flag-ID",
    text: "Asia Pacific (Jakarta)",
    value: "ap-southeast-3",
  },
  {
    helpText: "ap-southeast-4",
    iconVariant: "flag-AU",
    text: "Asia Pacific (Melbourne)",
    value: "ap-southeast-4",
  },
  {
    helpText: "ap-south-1",
    iconVariant: "flag-IN",
    text: "Asia Pacific (Mumbai)",
    value: "ap-south-1",
  },
  {
    helpText: "ap-northeast-3",
    iconVariant: "flag-JP",
    text: "Asia Pacific (Osaka)",
    value: "ap-northeast-3",
  },
  {
    helpText: "ap-northeast-2",
    iconVariant: "flag-KR",
    text: "Asia Pacific (Seoul)",
    value: "ap-northeast-2",
  },
  {
    helpText: "ap-southeast-1",
    iconVariant: "flag-SG",
    text: "Asia Pacific (Singapore)",
    value: "ap-southeast-1",
  },
  {
    helpText: "ap-southeast-2",
    iconVariant: "flag-AU",
    text: "Asia Pacific (Sydney)",
    value: "ap-southeast-2",
  },
  {
    helpText: "ap-northeast-1",
    iconVariant: "flag-JP",
    text: "Asia Pacific (Tokyo)",
    value: "ap-northeast-1",
  },

  // canada
  {
    helpText: "ca-central-1",
    iconVariant: "flag-CA",
    text: "Canada (Central)",
    value: "ca-central-1",
  },
  {
    helpText: "ca-west-1",
    iconVariant: "flag-CA",
    text: "Canada West (Calgery)",
    value: "ca-west-1",
  },

  // europe
  {
    helpText: "eu-central-1",
    iconVariant: "flag-DE",
    text: "Europe (Frankfurt)",
    value: "eu-central-1",
  },
  {
    helpText: "eu-west-1",
    iconVariant: "flag-IE",
    text: "Europe (Ireland)",
    value: "eu-west-1",
  },
  {
    helpText: "eu-west-2",
    iconVariant: "flag-GB",
    text: "Europe (London)",
    value: "eu-west-2",
  },
  {
    helpText: "eu-south-1",
    iconVariant: "flag-IT",
    text: "Europe (Milan)",
    value: "eu-south-1",
  },
  {
    helpText: "eu-west-3",
    iconVariant: "flag-FR",
    text: "Europe (Paris)",
    value: "eu-west-3",
  },
  {
    helpText: "eu-south-2",
    iconVariant: "flag-ES",
    text: "Europe (Spain)",
    value: "eu-south-2",
  },
  {
    helpText: "eu-north-1",
    iconVariant: "flag-SE",
    text: "Europe (Stockholm)",
    value: "eu-north-1",
  },
  {
    helpText: "eu-central-2",
    iconVariant: "flag-CH",
    text: "Europe (Zürich)",
    value: "eu-central-2",
  },

  // israel
  {
    helpText: "il-central-1",
    iconVariant: "flag-IL",
    text: "Israel (Tel Aviv)",
    value: "il-central-1",
  },

  // middle east
  {
    helpText: "me-south-1",
    iconVariant: "flag-BH",
    text: "Middle East (Bahrain)",
    value: "me-south-1",
  },
  {
    helpText: "me-central-1",
    iconVariant: "flag-AE",
    text: "Middle East (UAE)",
    value: "me-central-1",
  },

  // south america
  {
    helpText: "sa-east-1",
    iconVariant: "flag-BR",
    text: "South America (São Paulo)",
    value: "sa-east-1",
  },

  // gov cloud
  {
    helpText: "us-gov-east-1",
    iconVariant: "flag-US",
    text: "AWS GovCloud (US-East)",
    value: "us-gov-east-1",
  },
  {
    helpText: "us-gov-west-1",
    iconVariant: "flag-US",
    text: "AWS GovCloud (US-West)",
    value: "us-gov-west-1",
  },
];

export const AZURE_REGIONS = [
  {
    text: "East US",
    value: "eastus",
    helpText: "(US) East US",
    iconVariant: "flag-US",
  },
  {
    text: "East US 2",
    value: "eastus2",
    helpText: "(US) East US 2",
    iconVariant: "flag-US",
  },
  {
    text: "South Central US",
    value: "southcentralus",
    helpText: "(US) South Central US",
    iconVariant: "flag-US",
  },
  {
    text: "West US 2",
    value: "westus2",
    helpText: "(US) West US 2",
    iconVariant: "flag-US",
  },
  {
    text: "West US 3",
    value: "westus3",
    helpText: "(US) West US 3",
    iconVariant: "flag-US",
  },
  {
    text: "Australia East",
    value: "australiaeast",
    helpText: "(Asia Pacific) Australia East",
    iconVariant: "flag-AU",
  },
  {
    text: "Southeast Asia",
    value: "southeastasia",
    helpText: "(Asia Pacific) Southeast Asia",
    iconVariant: "flag-SG",
  },
  {
    text: "North Europe",
    value: "northeurope",
    helpText: "(Europe) North Europe",
    iconVariant: "flag-IE",
  },
  {
    text: "Sweden Central",
    value: "swedencentral",
    helpText: "(Europe) Sweden Central",
    iconVariant: "flag-SE",
  },
  {
    text: "UK South",
    value: "uksouth",
    helpText: "(Europe) UK South",
    iconVariant: "flag-GB",
  },
  {
    text: "West Europe",
    value: "westeurope",
    helpText: "(Europe) West Europe",
    iconVariant: "flag-NL",
  },
  {
    text: "Central US",
    value: "centralus",
    helpText: "(US) Central US",
    iconVariant: "flag-US",
  },
  {
    text: "South Africa North",
    value: "southafricanorth",
    helpText: "(Africa) South Africa North",
    iconVariant: "flag-ZA",
  },
  {
    text: "Central India",
    value: "centralindia",
    helpText: "(Asia Pacific) Central India",
    iconVariant: "flag-IN",
  },
  {
    text: "East Asia",
    value: "eastasia",
    helpText: "(Asia Pacific) East Asia",
    iconVariant: "flag-HK",
  },
  {
    text: "Japan East",
    value: "japaneast",
    helpText: "(Asia Pacific) Japan East",
    iconVariant: "flag-JP",
  },
  {
    text: "Korea Central",
    value: "koreacentral",
    helpText: "(Asia Pacific) Korea Central",
    iconVariant: "flag-KR",
  },
  {
    text: "Canada Central",
    value: "canadacentral",
    helpText: "(Canada) Canada Central",
    iconVariant: "flag-CA",
  },
  {
    text: "France Central",
    value: "francecentral",
    helpText: "(Europe) France Central",
    iconVariant: "flag-FR",
  },
  {
    text: "Germany West Central",
    value: "germanywestcentral",
    helpText: "(Europe) Germany West Central",
    iconVariant: "flag-DE",
  },
  {
    text: "Norway East",
    value: "norwayeast",
    helpText: "(Europe) Norway East",
    iconVariant: "flag-NO",
  },
  {
    text: "Poland Central",
    value: "polandcentral",
    helpText: "(Europe) Poland Central",
    iconVariant: "flag-PL",
  },
  {
    text: "Switzerland North",
    value: "switzerlandnorth",
    helpText: "(Europe) Switzerland North",
    iconVariant: "flag-CH",
  },
  {
    text: "UAE North",
    value: "uaenorth",
    helpText: "(Middle East) UAE North",
    iconVariant: "flag-AE",
  },
  {
    text: "Brazil South",
    value: "brazilsouth",
    helpText: "(South America) Brazil South",
    iconVariant: "flag-BR",
  },
  {
    text: "Central US EUAP",
    value: "centraluseuap",
    helpText: "(US) Central US EUAP",
    iconVariant: "flag-US",
  },
  {
    text: "Qatar Central",
    value: "qatarcentral",
    helpText: "(Middle East) Qatar Central",
    iconVariant: "flag-QA",
  },
  {
    text: "Central US (Stage)",
    value: "centralusstage",
    helpText: "(US) Central US (Stage)",
    iconVariant: "flag-US",
  },
  {
    text: "East US (Stage)",
    value: "eastusstage",
    helpText: "(US) East US (Stage)",
    iconVariant: "flag-US",
  },
  {
    text: "East US 2 (Stage)",
    value: "eastus2stage",
    helpText: "(US) East US 2 (Stage)",
    iconVariant: "flag-US",
  },
  {
    text: "North Central US (Stage)",
    value: "northcentralusstage",
    helpText: "(US) North Central US (Stage)",
    iconVariant: "flag-US",
  },
  {
    text: "South Central US (Stage)",
    value: "southcentralusstage",
    helpText: "(US) South Central US (Stage)",
    iconVariant: "flag-US",
  },
  {
    text: "West US (Stage)",
    value: "westusstage",
    helpText: "(US) West US (Stage)",
    iconVariant: "flag-US",
  },
  {
    text: "West US 2 (Stage)",
    value: "westus2stage",
    helpText: "(US) West US 2 (Stage)",
    iconVariant: "flag-US",
  },
  {
    text: "Asia",
    value: "asia",
    helpText: "Asia",
  },
  {
    text: "Asia Pacific",
    value: "asiapacific",
    helpText: "Asia Pacific",
    iconVariant: "flag-SG",
  },
  {
    text: "Australia",
    value: "australia",
    helpText: "Australia",
    iconVariant: "flag-AU",
  },
  {
    text: "Brazil",
    value: "brazil",
    helpText: "Brazil",
    iconVariant: "flag-BR",
  },
  {
    text: "Canada",
    value: "canada",
    helpText: "Canada",
    iconVariant: "flag-CA",
  },
  {
    text: "Europe",
    value: "europe",
    helpText: "Europe",
    iconVariant: "flag-EU",
  },
  {
    text: "France",
    value: "france",
    helpText: "France",
    iconVariant: "flag-FR",
  },
  {
    text: "Germany",
    value: "germany",
    helpText: "Germany",
    iconVariant: "flag-DE",
  },
  {
    text: "Global",
    value: "global",
    helpText: "Global",
  },
  {
    text: "India",
    value: "india",
    helpText: "India",
    iconVariant: "flag-IN",
  },
  {
    text: "Japan",
    value: "japan",
    helpText: "Japan",
    iconVariant: "flag-JP",
  },
  {
    text: "Korea",
    value: "korea",
    helpText: "Korea",
    iconVariant: "flag-KR",
  },
  {
    text: "Norway",
    value: "norway",
    helpText: "Norway",
    iconVariant: "flag-NO",
  },
  {
    text: "Singapore",
    value: "singapore",
    helpText: "Singapore",
    iconVariant: "flag-SG",
  },
  {
    text: "South Africa",
    value: "southafrica",
    helpText: "South Africa",
    iconVariant: "flag-ZA",
  },
  {
    text: "Switzerland",
    value: "switzerland",
    helpText: "Switzerland",
    iconVariant: "flag-CH",
  },
  {
    text: "United Arab Emirates",
    value: "uae",
    helpText: "United Arab Emirates",
    iconVariant: "flag-AE",
  },
  {
    text: "United Kingdom",
    value: "uk",
    helpText: "United Kingdom",
    iconVariant: "flag-GB",
  },
  {
    text: "United States",
    value: "unitedstates",
    helpText: "United States",
    iconVariant: "flag-US",
  },
  {
    text: "United States EUAP",
    value: "unitedstateseuap",
    helpText: "United States EUAP",
    iconVariant: "flag-US",
  },
  {
    text: "East Asia (Stage)",
    value: "eastasiastage",
    helpText: "(Asia Pacific) East Asia (Stage)",
    iconVariant: "flag-HK",
  },
  {
    text: "Southeast Asia (Stage)",
    value: "southeastasiastage",
    helpText: "(Asia Pacific) Southeast Asia (Stage)",
    iconVariant: "flag-SG",
  },
  {
    text: "Brazil US",
    value: "brazilus",
    helpText: "(South America) Brazil US",
    iconVariant: "flag-BR",
  },
  {
    text: "East US STG",
    value: "eastusstg",
    helpText: "(US) East US STG",
    iconVariant: "flag-US",
  },
  {
    text: "North Central US",
    value: "northcentralus",
    helpText: "(US) North Central US",
    iconVariant: "flag-US",
  },
  {
    text: "West US",
    value: "westus",
    helpText: "(US) West US",
    iconVariant: "flag-US",
  },
  {
    text: "Jio India West",
    value: "jioindiawest",
    helpText: "(Asia Pacific) Jio India West",
    iconVariant: "flag-IN",
  },
  {
    text: "East US 2 EUAP",
    value: "eastus2euap",
    helpText: "(US) East US 2 EUAP",
    iconVariant: "flag-US",
  },
  {
    text: "South Central US STG",
    value: "southcentralusstg",
    helpText: "(US) South Central US STG",
    iconVariant: "flag-US",
  },
  {
    text: "West Central US",
    value: "westcentralus",
    helpText: "(US) West Central US",
    iconVariant: "flag-US",
  },
  {
    text: "South Africa West",
    value: "southafricawest",
    helpText: "(Africa) South Africa West",
    iconVariant: "flag-ZA",
  },
  {
    text: "Australia Central",
    value: "australiacentral",
    helpText: "(Asia Pacific) Australia Central",
    iconVariant: "flag-AU",
  },
  {
    text: "Australia Central 2",
    value: "australiacentral2",
    helpText: "(Asia Pacific) Australia Central 2",
    iconVariant: "flag-AU",
  },
  {
    text: "Australia Southeast",
    value: "australiasoutheast",
    helpText: "(Asia Pacific) Australia Southeast",
    iconVariant: "flag-AU",
  },
  {
    text: "Japan West",
    value: "japanwest",
    helpText: "(Asia Pacific) Japan West",
    iconVariant: "flag-JP",
  },
  {
    text: "Jio India Central",
    value: "jioindiacentral",
    helpText: "(Asia Pacific) Jio India Central",
    iconVariant: "flag-IN",
  },
  {
    text: "Korea South",
    value: "koreasouth",
    helpText: "(Asia Pacific) Korea South",
    iconVariant: "flag-KR",
  },
  {
    text: "South India",
    value: "southindia",
    helpText: "(Asia Pacific) South India",
    iconVariant: "flag-IN",
  },
  {
    text: "West India",
    value: "westindia",
    helpText: "(Asia Pacific) West India",
    iconVariant: "flag-IN",
  },
  {
    text: "Canada East",
    value: "canadaeast",
    helpText: "(Canada) Canada East",
    iconVariant: "flag-CA",
  },
  {
    text: "France South",
    value: "francesouth",
    helpText: "(Europe) France South",
    iconVariant: "flag-FR",
  },
  {
    text: "Germany North",
    value: "germanynorth",
    helpText: "(Europe) Germany North",
    iconVariant: "flag-DE",
  },
  {
    text: "Norway West",
    value: "norwaywest",
    helpText: "(Europe) Norway West",
    iconVariant: "flag-NO",
  },
  {
    text: "Switzerland West",
    value: "switzerlandwest",
    helpText: "(Europe) Switzerland West",
    iconVariant: "flag-CH",
  },
  {
    text: "UK West",
    value: "ukwest",
    helpText: "(Europe) UK West",
    iconVariant: "flag-GB",
  },
  {
    text: "UAE Central",
    value: "uaecentral",
    helpText: "(Middle East) UAE Central",
    iconVariant: "flag-AE",
  },
  {
    text: "Brazil Southeast",
    value: "brazilsoutheast",
    helpText: "(South America) Brazil Southeast",
    iconVariant: "flag-BR",
  },
  {
    helpText: "(Middle East) Israel Central",
    iconVariant: "flag-IL",
    text: "Israel Central",
    value: "israelcentral",
  },
];
