package flow

import (
	"github.com/pkg/errors"
	"go.temporal.io/sdk/workflow"

	"github.com/nuonco/nuon/services/ctl-api/internal/app"
	signaldb "github.com/nuonco/nuon/services/ctl-api/internal/pkg/queue/signal/db"
)

// ExecuteStepRequest is the input for the ExecuteStep child workflow.
type ExecuteStepRequest struct {
	StepID      string               `json:"step_id"`
	QueueSignal *signaldb.SignalData `json:"queue_signal"`
	Step        app.WorkflowStep     `json:"step"`
}

// ExecuteStepWorkflows provides a registrable workflow struct for the ExecuteStep child workflow.
// Callers must set ExecFn before registering the workflow on the worker.
type ExecuteStepWorkflows struct {
	ExecFn func(workflow.Context, *signaldb.SignalData, app.WorkflowStep) error
}

func (w *ExecuteStepWorkflows) ExecuteStep(ctx workflow.Context, req ExecuteStepRequest) error {
	if w.ExecFn == nil {
		return errors.New("ExecFn not configured on ExecuteStepWorkflows")
	}
	return w.ExecFn(ctx, req.QueueSignal, req.Step)
}

// executeStepAsChildWorkflow launches the step execution as a Temporal child workflow
// and waits for it to complete. AwaitExecuteStep is generated by temporal-gen-v2.
func (c *WorkflowConductor[DomainSignal]) executeStepAsChildWorkflow(ctx workflow.Context, step *app.WorkflowStep) error {
	return nil
	//return AwaitExecuteStep(ctx, ExecuteStepRequest{
	//StepID:      step.ID,
	//QueueSignal: step.QueueSignal,
	//Step:        *step,
	//})
}
