export default {
  title: 'Approvals/PlanDiffs/KubernetesDiff',
}

import { KubernetesDiff } from './KubernetesDiff'

const mockPlan = {
  plan: 'k8s-plan-1',
  op: 'apply',
  k8s_content_diff: [
    {
      _version: 'v1',
      name: 'my-configmap',
      namespace: 'default',
      kind: 'ConfigMap',
      api: 'v1',
      resource: 'configmaps',
      op: 'changed',
      type: 3,
      dry_run: false,
      entries: [
        {
          path: 'data.DATABASE_URL',
          original: 'postgres://old-host:5432/db',
          applied: 'postgres://new-host:5432/db',
          type: 2,
          payload: '',
        },
      ],
    },
    {
      _version: 'v1',
      name: 'new-secret',
      namespace: 'staging',
      kind: 'Secret',
      api: 'v1',
      resource: 'secrets',
      op: 'added',
      type: 1,
      dry_run: false,
    },
  ],
} as any

export const Default = () => <KubernetesDiff plan={mockPlan} />

const deploymentUpgradePlan = {
  plan: 'k8s-deployment-upgrade',
  op: 'apply',
  k8s_content_diff: [
    {
      _version: 'v1',
      name: 'api-server',
      namespace: 'production',
      kind: 'Deployment',
      api: 'apps/v1',
      resource: 'deployments',
      op: 'apply',
      type: 3,
      dry_run: false,
      entries: [
        { type: 0, payload: 'apiVersion: apps/v1', path: '' },
        { type: 0, payload: 'kind: Deployment', path: '' },
        { type: 0, payload: 'metadata:', path: '' },
        { type: 0, payload: '  name: api-server', path: '' },
        { type: 0, payload: '  namespace: production', path: '' },
        { type: 0, payload: 'spec:', path: '' },
        { type: 1, payload: '  replicas: 2', path: '' },
        { type: 2, payload: '  replicas: 3', path: '' },
        { type: 0, payload: '  template:', path: '' },
        { type: 0, payload: '    spec:', path: '' },
        { type: 0, payload: '      containers:', path: '' },
        { type: 0, payload: '      - name: api-server', path: '' },
        { type: 1, payload: '        image: registry.example.com/api-server:v2.14.0', path: '' },
        { type: 2, payload: '        image: registry.example.com/api-server:v2.15.1', path: '' },
        { type: 0, payload: '        ports:', path: '' },
        { type: 0, payload: '        - containerPort: 8080', path: '' },
        { type: 0, payload: '        resources:', path: '' },
        { type: 0, payload: '          requests:', path: '' },
        { type: 0, payload: '            cpu: 200m', path: '' },
        { type: 1, payload: '            memory: 256Mi', path: '' },
        { type: 2, payload: '            memory: 384Mi', path: '' },
        { type: 0, payload: '          limits:', path: '' },
        { type: 0, payload: '            cpu: 500m', path: '' },
        { type: 1, payload: '            memory: 512Mi', path: '' },
        { type: 2, payload: '            memory: 768Mi', path: '' },
      ],
    },
    {
      _version: 'v1',
      name: 'api-server',
      namespace: 'production',
      kind: 'ConfigMap',
      api: 'v1',
      resource: 'configmaps',
      op: 'apply',
      type: 3,
      dry_run: false,
      entries: [
        { type: 0, payload: 'apiVersion: v1', path: '' },
        { type: 0, payload: 'kind: ConfigMap', path: '' },
        { type: 0, payload: 'metadata:', path: '' },
        { type: 0, payload: '  name: api-server', path: '' },
        { type: 0, payload: '  namespace: production', path: '' },
        { type: 0, payload: 'data:', path: '' },
        { type: 1, payload: '  LOG_LEVEL: info', path: '' },
        { type: 2, payload: '  LOG_LEVEL: debug', path: '' },
        { type: 1, payload: '  MAX_CONNECTIONS: "100"', path: '' },
        { type: 2, payload: '  MAX_CONNECTIONS: "200"', path: '' },
        { type: 2, payload: '  FEATURE_FLAG_NEW_AUTH: "true"', path: '' },
      ],
    },
    {
      _version: 'v1',
      name: 'api-server',
      namespace: 'production',
      kind: 'Service',
      api: 'v1',
      resource: 'services',
      op: 'apply',
      type: 0,
      dry_run: false,
      entries: [],
    },
  ],
} as any

export const DeploymentUpgrade = () => (
  <KubernetesDiff plan={deploymentUpgradePlan} />
)

const freshInstallPlan = {
  plan: 'k8s-fresh-install',
  op: 'apply',
  k8s_content_diff: [
    {
      _version: 'v1',
      name: 'worker',
      namespace: 'jobs',
      kind: 'Deployment',
      api: 'apps/v1',
      resource: 'deployments',
      op: 'apply',
      type: 2,
      dry_run: false,
      entries: [
        { type: 2, payload: 'apiVersion: apps/v1', path: '' },
        { type: 2, payload: 'kind: Deployment', path: '' },
        { type: 2, payload: 'metadata:', path: '' },
        { type: 2, payload: '  name: worker', path: '' },
        { type: 2, payload: '  namespace: jobs', path: '' },
        { type: 2, payload: 'spec:', path: '' },
        { type: 2, payload: '  replicas: 2', path: '' },
        { type: 2, payload: '  selector:', path: '' },
        { type: 2, payload: '    matchLabels:', path: '' },
        { type: 2, payload: '      app: worker', path: '' },
        { type: 2, payload: '  template:', path: '' },
        { type: 2, payload: '    spec:', path: '' },
        { type: 2, payload: '      containers:', path: '' },
        { type: 2, payload: '      - name: worker', path: '' },
        { type: 2, payload: '        image: registry.example.com/worker:v1.0.0', path: '' },
        { type: 2, payload: '        resources:', path: '' },
        { type: 2, payload: '          requests:', path: '' },
        { type: 2, payload: '            cpu: 100m', path: '' },
        { type: 2, payload: '            memory: 128Mi', path: '' },
        { type: 2, payload: '          limits:', path: '' },
        { type: 2, payload: '            cpu: 500m', path: '' },
        { type: 2, payload: '            memory: 512Mi', path: '' },
      ],
    },
    {
      _version: 'v1',
      name: 'worker',
      namespace: 'jobs',
      kind: 'ServiceAccount',
      api: 'v1',
      resource: 'serviceaccounts',
      op: 'apply',
      type: 2,
      dry_run: false,
      entries: [
        { type: 2, payload: 'apiVersion: v1', path: '' },
        { type: 2, payload: 'kind: ServiceAccount', path: '' },
        { type: 2, payload: 'metadata:', path: '' },
        { type: 2, payload: '  name: worker', path: '' },
        { type: 2, payload: '  namespace: jobs', path: '' },
        { type: 2, payload: '  annotations:', path: '' },
        { type: 2, payload: '    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/worker', path: '' },
      ],
    },
    {
      _version: 'v1',
      name: 'worker',
      namespace: 'jobs',
      kind: 'Service',
      api: 'v1',
      resource: 'services',
      op: 'apply',
      type: 2,
      dry_run: false,
      entries: [
        { type: 2, payload: 'apiVersion: v1', path: '' },
        { type: 2, payload: 'kind: Service', path: '' },
        { type: 2, payload: 'metadata:', path: '' },
        { type: 2, payload: '  name: worker', path: '' },
        { type: 2, payload: '  namespace: jobs', path: '' },
        { type: 2, payload: 'spec:', path: '' },
        { type: 2, payload: '  type: ClusterIP', path: '' },
        { type: 2, payload: '  ports:', path: '' },
        { type: 2, payload: '  - name: http', path: '' },
        { type: 2, payload: '    port: 8080', path: '' },
        { type: 2, payload: '    targetPort: 8080', path: '' },
        { type: 2, payload: '  selector:', path: '' },
        { type: 2, payload: '    app: worker', path: '' },
      ],
    },
  ],
} as any

export const FreshInstall = () => <KubernetesDiff plan={freshInstallPlan} />

const deleteResourcesPlan = {
  plan: 'k8s-delete-resources',
  op: 'apply',
  k8s_content_diff: [
    {
      _version: 'v1',
      name: 'legacy-cron',
      namespace: 'default',
      kind: 'CronJob',
      api: 'batch/v1',
      resource: 'cronjobs',
      op: 'delete',
      type: 1,
      dry_run: false,
      entries: [
        { type: 1, payload: 'apiVersion: batch/v1', path: '' },
        { type: 1, payload: 'kind: CronJob', path: '' },
        { type: 1, payload: 'metadata:', path: '' },
        { type: 1, payload: '  name: legacy-cron', path: '' },
        { type: 1, payload: '  namespace: default', path: '' },
        { type: 1, payload: 'spec:', path: '' },
        { type: 1, payload: '  schedule: "0 */6 * * *"', path: '' },
        { type: 1, payload: '  jobTemplate:', path: '' },
        { type: 1, payload: '    spec:', path: '' },
        { type: 1, payload: '      template:', path: '' },
        { type: 1, payload: '        spec:', path: '' },
        { type: 1, payload: '          containers:', path: '' },
        { type: 1, payload: '          - name: cleanup', path: '' },
        { type: 1, payload: '            image: registry.example.com/cleanup:v0.3.2', path: '' },
        { type: 1, payload: '          restartPolicy: OnFailure', path: '' },
      ],
    },
    {
      _version: 'v1',
      name: 'legacy-worker',
      namespace: 'default',
      kind: 'Deployment',
      api: 'apps/v1',
      resource: 'deployments',
      op: 'delete',
      type: 1,
      dry_run: false,
      entries: [
        { type: 1, payload: 'apiVersion: apps/v1', path: '' },
        { type: 1, payload: 'kind: Deployment', path: '' },
        { type: 1, payload: 'metadata:', path: '' },
        { type: 1, payload: '  name: legacy-worker', path: '' },
        { type: 1, payload: '  namespace: default', path: '' },
        { type: 1, payload: 'spec:', path: '' },
        { type: 1, payload: '  replicas: 1', path: '' },
        { type: 1, payload: '  template:', path: '' },
        { type: 1, payload: '    spec:', path: '' },
        { type: 1, payload: '      containers:', path: '' },
        { type: 1, payload: '      - name: worker', path: '' },
        { type: 1, payload: '        image: registry.example.com/legacy-worker:v1.8.0', path: '' },
      ],
    },
  ],
} as any

export const DeleteResources = () => (
  <KubernetesDiff plan={deleteResourcesPlan} />
)

const mixedOperationsPlan = {
  plan: 'k8s-mixed-ops',
  op: 'apply',
  k8s_content_diff: [
    {
      _version: 'v1',
      name: 'web-app',
      namespace: 'production',
      kind: 'Deployment',
      api: 'apps/v1',
      resource: 'deployments',
      op: 'apply',
      type: 3,
      dry_run: false,
      entries: [
        { type: 0, payload: 'apiVersion: apps/v1', path: '' },
        { type: 0, payload: 'kind: Deployment', path: '' },
        { type: 0, payload: 'metadata:', path: '' },
        { type: 0, payload: '  name: web-app', path: '' },
        { type: 0, payload: '  namespace: production', path: '' },
        { type: 0, payload: 'spec:', path: '' },
        { type: 0, payload: '  replicas: 3', path: '' },
        { type: 0, payload: '  template:', path: '' },
        { type: 0, payload: '    spec:', path: '' },
        { type: 0, payload: '      containers:', path: '' },
        { type: 0, payload: '      - name: web', path: '' },
        { type: 1, payload: '        image: registry.example.com/web-app:v3.1.0', path: '' },
        { type: 2, payload: '        image: registry.example.com/web-app:v3.2.0', path: '' },
        { type: 0, payload: '        ports:', path: '' },
        { type: 0, payload: '        - containerPort: 3000', path: '' },
        { type: 0, payload: '        env:', path: '' },
        { type: 0, payload: '        - name: NODE_ENV', path: '' },
        { type: 0, payload: '          value: production', path: '' },
        { type: 2, payload: '        - name: OTEL_ENABLED', path: '' },
        { type: 2, payload: '          value: "true"', path: '' },
        { type: 0, payload: '        resources:', path: '' },
        { type: 0, payload: '          requests:', path: '' },
        { type: 0, payload: '            cpu: 200m', path: '' },
        { type: 1, payload: '            memory: 256Mi', path: '' },
        { type: 2, payload: '            memory: 384Mi', path: '' },
        { type: 0, payload: '          limits:', path: '' },
        { type: 0, payload: '            cpu: 500m', path: '' },
        { type: 1, payload: '            memory: 512Mi', path: '' },
        { type: 2, payload: '            memory: 768Mi', path: '' },
      ],
    },
    {
      _version: 'v1',
      name: 'web-app-hpa',
      namespace: 'production',
      kind: 'HorizontalPodAutoscaler',
      api: 'autoscaling/v2',
      resource: 'horizontalpodautoscalers',
      op: 'apply',
      type: 2,
      dry_run: false,
      entries: [
        { type: 2, payload: 'apiVersion: autoscaling/v2', path: '' },
        { type: 2, payload: 'kind: HorizontalPodAutoscaler', path: '' },
        { type: 2, payload: 'metadata:', path: '' },
        { type: 2, payload: '  name: web-app-hpa', path: '' },
        { type: 2, payload: '  namespace: production', path: '' },
        { type: 2, payload: 'spec:', path: '' },
        { type: 2, payload: '  scaleTargetRef:', path: '' },
        { type: 2, payload: '    apiVersion: apps/v1', path: '' },
        { type: 2, payload: '    kind: Deployment', path: '' },
        { type: 2, payload: '    name: web-app', path: '' },
        { type: 2, payload: '  minReplicas: 3', path: '' },
        { type: 2, payload: '  maxReplicas: 10', path: '' },
        { type: 2, payload: '  metrics:', path: '' },
        { type: 2, payload: '  - type: Resource', path: '' },
        { type: 2, payload: '    resource:', path: '' },
        { type: 2, payload: '      name: cpu', path: '' },
        { type: 2, payload: '      target:', path: '' },
        { type: 2, payload: '        type: Utilization', path: '' },
        { type: 2, payload: '        averageUtilization: 70', path: '' },
      ],
    },
    {
      _version: 'v1',
      name: 'old-ingress',
      namespace: 'production',
      kind: 'Ingress',
      api: 'networking.k8s.io/v1',
      resource: 'ingresses',
      op: 'delete',
      type: 1,
      dry_run: false,
      entries: [
        { type: 1, payload: 'apiVersion: networking.k8s.io/v1', path: '' },
        { type: 1, payload: 'kind: Ingress', path: '' },
        { type: 1, payload: 'metadata:', path: '' },
        { type: 1, payload: '  name: old-ingress', path: '' },
        { type: 1, payload: '  namespace: production', path: '' },
        { type: 1, payload: 'spec:', path: '' },
        { type: 1, payload: '  rules:', path: '' },
        { type: 1, payload: '  - host: old.example.com', path: '' },
        { type: 1, payload: '    http:', path: '' },
        { type: 1, payload: '      paths:', path: '' },
        { type: 1, payload: '      - path: /', path: '' },
        { type: 1, payload: '        pathType: Prefix', path: '' },
        { type: 1, payload: '        backend:', path: '' },
        { type: 1, payload: '          service:', path: '' },
        { type: 1, payload: '            name: web-app', path: '' },
        { type: 1, payload: '            port:', path: '' },
        { type: 1, payload: '              number: 3000', path: '' },
      ],
    },
  ],
} as any

export const MixedOperations = () => (
  <KubernetesDiff plan={mixedOperationsPlan} />
)

const withErrorsPlan = {
  plan: 'k8s-with-errors',
  op: 'apply',
  k8s_content_diff: [
    {
      _version: 'v1',
      name: 'api-gateway',
      namespace: 'ingress',
      kind: 'Deployment',
      api: 'apps/v1',
      resource: 'deployments',
      op: 'apply',
      type: 3,
      dry_run: false,
      entries: [
        { type: 0, payload: 'apiVersion: apps/v1', path: '' },
        { type: 0, payload: 'kind: Deployment', path: '' },
        { type: 0, payload: 'metadata:', path: '' },
        { type: 0, payload: '  name: api-gateway', path: '' },
        { type: 0, payload: '  namespace: ingress', path: '' },
        { type: 0, payload: 'spec:', path: '' },
        { type: 0, payload: '  template:', path: '' },
        { type: 0, payload: '    spec:', path: '' },
        { type: 0, payload: '      containers:', path: '' },
        { type: 0, payload: '      - name: gateway', path: '' },
        { type: 1, payload: '        image: registry.example.com/gateway:v2.0.0', path: '' },
        { type: 2, payload: '        image: registry.example.com/gateway:v2.1.0', path: '' },
        { type: 0, payload: '        ports:', path: '' },
        { type: 0, payload: '        - containerPort: 8080', path: '' },
      ],
    },
    {
      _version: 'v1',
      name: 'broken-crd',
      namespace: 'ingress',
      kind: 'GatewayRoute',
      api: 'gateway.networking.k8s.io/v1',
      resource: 'gatewayroutes',
      op: 'apply',
      type: 3,
      dry_run: false,
      error: 'resource "gateway.networking.k8s.io/v1/GatewayRoute" not found: ensure the CRD is installed',
    },
    {
      _version: 'v1',
      name: 'bad-config',
      namespace: 'ingress',
      kind: 'ConfigMap',
      api: 'v1',
      resource: 'configmaps',
      op: 'apply',
      type: 3,
      dry_run: false,
      error: 'field validation failed: data.RATE_LIMIT must be a positive integer',
    },
  ],
} as any

export const WithErrors = () => <KubernetesDiff plan={withErrorsPlan} />
