// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: variables/v1/install_inputs.proto

package variablesv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/srikrsna/protoc-gen-gotag/tagger"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstallInputs represent a customer provided input
type InstallInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallInput) Reset() {
	*x = InstallInput{}
	mi := &file_variables_v1_install_inputs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallInput) ProtoMessage() {}

func (x *InstallInput) ProtoReflect() protoreflect.Message {
	mi := &file_variables_v1_install_inputs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallInput.ProtoReflect.Descriptor instead.
func (*InstallInput) Descriptor() ([]byte, []int) {
	return file_variables_v1_install_inputs_proto_rawDescGZIP(), []int{0}
}

func (x *InstallInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstallInput) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// InstallInputss is a list of env vars, and exposes methods to convert to maps etc.
type InstallInputs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstallInputs []*InstallInput        `protobuf:"bytes,1,rep,name=install_inputs,json=installInputs,proto3" json:"install_inputs,omitempty" faker:"installInputs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallInputs) Reset() {
	*x = InstallInputs{}
	mi := &file_variables_v1_install_inputs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallInputs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallInputs) ProtoMessage() {}

func (x *InstallInputs) ProtoReflect() protoreflect.Message {
	mi := &file_variables_v1_install_inputs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallInputs.ProtoReflect.Descriptor instead.
func (*InstallInputs) Descriptor() ([]byte, []int) {
	return file_variables_v1_install_inputs_proto_rawDescGZIP(), []int{1}
}

func (x *InstallInputs) GetInstallInputs() []*InstallInput {
	if x != nil {
		return x.InstallInputs
	}
	return nil
}

var File_variables_v1_install_inputs_proto protoreflect.FileDescriptor

const file_variables_v1_install_inputs_proto_rawDesc = "" +
	"\n" +
	"!variables/v1/install_inputs.proto\x12\fvariables.v1\x1a\x13tagger/tagger.proto\"8\n" +
	"\fInstallInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"n\n" +
	"\rInstallInputs\x12]\n" +
	"\x0einstall_inputs\x18\x01 \x03(\v2\x1a.variables.v1.InstallInputB\x1a\x9a\x84\x9e\x03\x15faker:\"installInputs\"R\rinstallInputsB\xbd\x01\n" +
	"\x10com.variables.v1B\x12InstallInputsProtoP\x01ZDgithub.com/nuonco/nuon/pkg/types/components/variables/v1;variablesv1\xa2\x02\x03VXX\xaa\x02\fVariables.V1\xca\x02\fVariables\\V1\xe2\x02\x18Variables\\V1\\GPBMetadata\xea\x02\rVariables::V1b\x06proto3"

var (
	file_variables_v1_install_inputs_proto_rawDescOnce sync.Once
	file_variables_v1_install_inputs_proto_rawDescData []byte
)

func file_variables_v1_install_inputs_proto_rawDescGZIP() []byte {
	file_variables_v1_install_inputs_proto_rawDescOnce.Do(func() {
		file_variables_v1_install_inputs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_variables_v1_install_inputs_proto_rawDesc), len(file_variables_v1_install_inputs_proto_rawDesc)))
	})
	return file_variables_v1_install_inputs_proto_rawDescData
}

var file_variables_v1_install_inputs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_variables_v1_install_inputs_proto_goTypes = []any{
	(*InstallInput)(nil),  // 0: variables.v1.InstallInput
	(*InstallInputs)(nil), // 1: variables.v1.InstallInputs
}
var file_variables_v1_install_inputs_proto_depIdxs = []int32{
	0, // 0: variables.v1.InstallInputs.install_inputs:type_name -> variables.v1.InstallInput
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_variables_v1_install_inputs_proto_init() }
func file_variables_v1_install_inputs_proto_init() {
	if File_variables_v1_install_inputs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_variables_v1_install_inputs_proto_rawDesc), len(file_variables_v1_install_inputs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_variables_v1_install_inputs_proto_goTypes,
		DependencyIndexes: file_variables_v1_install_inputs_proto_depIdxs,
		MessageInfos:      file_variables_v1_install_inputs_proto_msgTypes,
	}.Build()
	File_variables_v1_install_inputs_proto = out.File
	file_variables_v1_install_inputs_proto_goTypes = nil
	file_variables_v1_install_inputs_proto_depIdxs = nil
}
