---
name: build-base-images
on:
  workflow_call:
    inputs:
      service:
        type: string
        required: true
      disable_github_oidc:
        type: boolean
        required: false
        default: true
    outputs: {}

defaults:
  run:
    shell: bash

jobs:
  build-base:
    name: build-base
    runs-on: build-only
    timeout-minutes: 15
    env:
      NO_CACHE: ${{ contains(github.event.pull_request.labels.*.name, 'no-cache') }}
      NO_REMOTE_BUILDKIT: ${{ contains(github.event.pull_request.labels.*.name, 'no-remote-buildkit') }}
      DISABLE_GITHUB_OIDC: ${{ inputs.disable_github_oidc }}
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup nuonctl
        uses: ./actions/setup-nuonctl

      - name: Use nuon buildkit in infra-shared-ci
        if: ${{ env.NO_REMOTE_BUILDKIT != 'true' }}
        run: |
         CI=true nuonctl builds driver ctl-api && nuonctl builds driver-health ctl-api || docker buildx ls

      - name: 📦 Build base images
        run: |
         CI=true nuonctl builds base \
           ${{inputs.service}}

