# workflow jobs for testing/linting and verifying changes to go packages
---
name: pkg
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  changes:
    name: 🔍 changes
    runs-on: ubuntu-latest
    outputs:
      pkg: ${{ steps.filter.outputs.pkg }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            pkg:
              - 'pkg/**'
              - .github/workflows/pkg.yml
              - go.mod
              - go.sum
  # TODO: add lint job once .golangci.yml is migrated to v2 format
  test:
    name: 🌏 test
    needs: changes
    if: ${{ needs.changes.outputs.pkg == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup nuonctl
        uses: ./actions/setup-nuonctl

      - name: 🧪 Tests
        run: CI=true nuonctl tests run-all pkg

  update_status:
    name: update status
    needs:
      - test
    if: github.event_name == 'pull_request' && always()
    runs-on: ubuntu-latest
    steps:
      - uses: martialonline/workflow-status@v4.2
        id: check
      - name: Update status
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: pkg ✅
          status: ${{steps.check.outputs.status}}
          ignoreForks: "false"
