# workflows for building/testing/deploying services
---
name: services
"on":
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: read
  packages: write
  pull-requests: write
  statuses: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  # NOTE(jm): we only want to "cancel" in flight jobs if pushing to an existing PR. If this is running on main, do not
  # cancel previous jobs.
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'promote') }}
    outputs:
      services: ${{ steps.filter.outputs.changes }}
      git_ref: ${{ steps.git_ref.outputs.git_ref }}
      auto_deploy: ${{ steps.auto_deploy.outputs.label_check == 'success' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          sparse-checkout: ci-triggers.yml
          sparse-checkout-cone-mode: false

      - name: read ci triggers file
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: ci_triggers
        with:
          config: ci-triggers.yml

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: ${{ steps.ci_triggers.outputs['services'] }}

      - name: Set git_ref output
        id: git_ref
        run: |
          SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          echo "git_ref=${SHA::7}" >> $GITHUB_OUTPUT

      - uses: docker://agilepathway/pull-request-label-checker:latest
        id: auto_deploy
        if: ${{ github.event_name == 'pull_request' }}
        with:
          any_of: auto-deploy
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          allow_failure: true

  pkg_lint:
    name: 🔍 Lint pkg
    needs:
      - prepare
    if: ${{ !cancelled() && !contains(github.event.pull_request.labels.*.name, 'promote') && needs.prepare.outputs.services != '[]' && needs.prepare.outputs.services != '' && (contains(needs.prepare.outputs.services, 'ctl-api') || contains(needs.prepare.outputs.services, 'runner') || contains(needs.prepare.outputs.services, 'cli') || contains(needs.prepare.outputs.services, 'lsp') || contains(needs.prepare.outputs.services, 'workers-')) }}
    runs-on: build-only
    timeout-minutes: 15
    env:
      NO_CACHE: ${{ contains(github.event.pull_request.labels.*.name, 'no-cache') }}
      NO_REMOTE_BUILDKIT: ${{ contains(github.event.pull_request.labels.*.name, 'no-remote-buildkit') }}
      DISABLE_GITHUB_OIDC: ${{ github.repository != 'nuonco/nuon' }}
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup nuonctl
        uses: ./actions/setup-nuonctl
      - name: Setup BuildKit
        if: ${{ env.NO_REMOTE_BUILDKIT != 'true' }}
        run: |
          CI=true nuonctl builds driver ctl-api && nuonctl builds driver-health ctl-api || docker buildx ls
      - name: 🔍 Lint pkg
        run: |
          CI=true nuonctl builds pkg-lint

  services:
    name: 🚢
    needs:
      - prepare
    if: ${{ !cancelled() && !contains(github.event.pull_request.labels.*.name, 'promote') && needs.prepare.outputs.services != '[]' && needs.prepare.outputs.services != '' }}
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJSON(needs.prepare.outputs.services) }}
    uses: ./.github/workflows/service.yml
    with:
      service: ${{matrix.service}}
      prod: false
      stage: ${{ github.event_name != 'pull_request' || needs.prepare.outputs.auto_deploy == 'true'}}
      tag: ${{ needs.prepare.outputs.git_ref }}
      disable_github_oidc: ${{ github.repository != 'nuonco/nuon' }}
    secrets: inherit

  update_status:
    name: update status
    if: github.event_name == 'pull_request' && always()
    needs:
      - services
    runs-on: ubuntu-latest
    steps:
      - uses: martialonline/workflow-status@v4.2
        id: check
      - name: Update status
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          name: services ✅
          status: ${{steps.check.outputs.status}}          
